# LM Studio 四模型批量 CNC test 评测

这个 notebook 与 `main_pipeline_demo1.ipynb` 隔离，复用同一套 prompt、RAG、generation 和 evaluation 代码。

运行分为六个独立阶段：

1. **Smoke 批量切换**：逐个加载模型，使用 `Heavy rain caused flooding in the region.` 调用 LM Studio 原生 API，确认 `reasoning=off`、reasoning token 为 0、没有 `<think>`，并能解析出正类 causal JSON；每个模型测试后立即卸载。即使一个模型失败，也继续测试其余模型。
2. **正式批量评测**：只有手动设置 `RUN_BATCH_EVAL=True` 才会开始。逐个加载模型、运行固定 `cnc_sft_test`、保存独立报告并卸载。该阶段既有四模型结果已经完成，开关现保持关闭。
3. **Qwen 家族 RAG3 补跑**：将在 Qwen 27B validation 消融中选出的 `k=3` 家族参数应用到 Qwen 35B A3B 和 Qwen 27B No Thinking 的完整 test，不重跑 Gemma。原运行中 35B 已正常完成，27B 中途出现异常。
4. **Qwen 27B reload100 历史补跑**：曾只重跑 Qwen3.6 27B No Thinking，现已终止并保持关闭。
5. **cache_prompt 定点诊断**：关闭 prompt cache，仅运行固定 test 第 590–636 条以复现已知异常区间。
6. **Qwen 27B 正式续跑**：复用 progress 500/1038 保存的原始计数，只对第 501–1038 条关闭 prompt cache 后补跑，再按 TP/FP/FN/TN 合并完整 test 指标。

CNC RAG 使用更新后的 train-only support；每次在固定 SFT test 上启用前都会通过 manifest 和精确 sample ID 检查验证 test overlap 为 0。

In [1]:
# ===== 全局配置：运行前先检查本单元格 =====
import json
import logging
import sys
from collections.abc import Iterable, Iterator
from html import escape
from pathlib import Path
from typing import Any

import pandas as pd
from IPython.display import HTML, display

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == 'notebooks':
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

if 'master_thesis' not in sys.executable.lower():
    raise RuntimeError('请切换到 Master_thesis kernel，重启 kernel 后从第一格重新运行。')

from src.data_io import load_dataset
from src.eval_pipeline import EvalRunConfig, run_stream_eval
from src.generator import generate, parse_output
from src.llm_client import LLMClient
from src.retriever import resolve_rag_cache_paths

logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')
LOGGER = logging.getLogger('lmstudio_batch_cnc_test')
logging.getLogger('src.llm_client').setLevel(logging.WARNING)


def _notebook_progress(
    iterable: Iterable[Any],
    *,
    total: int,
    desc: str,
) -> Iterator[Any]:
    safe_desc = escape(desc)
    safe_total = max(total, 1)

    def render(completed: int) -> HTML:
        percent = min(completed / safe_total * 100, 100.0)
        return HTML(
            f"<div style='width:100%'>"
            f"<div>{safe_desc}: {completed}/{total} ({percent:.1f}%)</div>"
            f"<progress value='{completed}' max='{safe_total}' "
            f"style='width:100%;height:18px'></progress></div>"
        )

    handle = display(render(0), display_id=True)
    for completed, item in enumerate(iterable, 1):
        yield item
        if handle is not None:
            handle.update(render(completed))

LMSTUDIO_BASE_URL = 'http://127.0.0.1:1234/v1'
LMSTUDIO_API_KEY = 'lm-studio'
MODEL_LOAD_TIMEOUT = 1200
LLM_TIMEOUT = 600
LLM_RETRY_TIMES = 3
CONTEXT_LENGTH = 8192
MAX_TOKENS = 2048
TEMPERATURE = 0.0

DATASET_NAME = 'cnc_sft_test'
EVAL_SAMPLE_N = None  # None = 固定 test 全部 1038 条；调试时可临时设为较小整数。
EVAL_PROGRESS_EVERY = 100
EVAL_MAX_WORKERS = 1
REPORT_DIR = Path('results') / 'eval_report' / 'lmstudio_batch_base_test'
RUN_BATCH_EVAL = False  # 四模型既有 test 已完成；不要为本次 Qwen RAG3 补跑重新开启。
REQUIRE_ALL_SMOKE_PASS = True

# 四个模型分别保留自己的 prompt/RAG 配置。当前主比较与微调模型一致，统一 RAG off。
# Gemma 26B 尚无混合正负 CNC 全集的独立最佳 prompt，因此先沿用 Gemma 系列的 v9.8。
MODEL_RUNS: list[dict[str, Any]] = [
    {
        'display_name': 'Qwen3.6 35B A3B',
        'model_key': 'qwen/qwen3.6-35b-a3b',
        'prompt_name': 'v9.6',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 1,
    },
    {
        'display_name': 'Qwen3.6 27B No Thinking',
        'model_key': 'local/qwen3.6-27b-no-thinking',
        'prompt_name': 'v9.6',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 1,
    },
    {
        'display_name': 'Gemma 4 26B A4B QAT',
        'model_key': 'google/gemma-4-26b-a4b-qat',
        'prompt_name': 'v9.8',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 1,
    },
    {
        'display_name': 'Gemma 4 31B QAT',
        'model_key': 'google/gemma-4-31b-qat',
        'prompt_name': 'v9.8',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 1,
    },
]

display(pd.DataFrame(MODEL_RUNS))

,display_name,model_key,prompt_name,use_rag,rag_database,rag_mode,rag_top_k
0,Qwen3.6 35B A3B,qwen/qwen3.6-35b-a3b,v9.6,True,cnc,knn_pattern,1
1,Qwen3.6 27B No Thinking,local/qwen3.6-27b-no-thinking,v9.6,True,cnc,knn_pattern,1
2,Gemma 4 26B A4B QAT,google/gemma-4-26b-a4b-qat,v9.8,True,cnc,knn_pattern,1
3,Gemma 4 31B QAT,google/gemma-4-31b-qat,v9.8,True,cnc,knn_pattern,1

In [2]:
# ===== LM Studio 管理 API 与四个 model key 预检（不加载模型） =====
manager = LLMClient(
    provider='lmstudio',
    base_url=LMSTUDIO_BASE_URL,
    model=MODEL_RUNS[0]['model_key'],
    api_key=LMSTUDIO_API_KEY,
    temperature=TEMPERATURE,
    max_tokens=MAX_TOKENS,
    context_length=CONTEXT_LENGTH,
    reasoning='off',
    timeout=MODEL_LOAD_TIMEOUT,
    retry_times=LLM_RETRY_TIMES,
)

inventory = manager.list_local_models()
inventory_by_key = {str(item['key']): item for item in inventory if item.get('key')}
target_keys = [str(run['model_key']) for run in MODEL_RUNS]
missing_keys = [key for key in target_keys if key not in inventory_by_key]
if missing_keys:
    raise RuntimeError(f'LM Studio 中找不到目标模型：{missing_keys}')

inventory_rows: list[dict[str, Any]] = []
for run in MODEL_RUNS:
    item = inventory_by_key[str(run['model_key'])]
    reasoning = item.get('capabilities', {}).get('reasoning', {})
    allowed = reasoning.get('allowed_options', [])
    inventory_rows.append({
        'model': run['display_name'],
        'model_key': run['model_key'],
        'quantization': item.get('quantization', {}).get('name'),
        'params': item.get('params_string'),
        'reasoning_default': reasoning.get('default'),
        'reasoning_off_capability': (
            'advertised' if 'off' in allowed
            else 'not_supported' if allowed
            else 'smoke_required'
        ),
        'loaded_instances': len(item.get('loaded_instances', [])),
    })

inventory_df = pd.DataFrame(inventory_rows)
display(inventory_df)
unsupported = inventory_df.loc[
    inventory_df['reasoning_off_capability'] == 'not_supported', 'model_key'
].tolist()
if unsupported:
    raise RuntimeError(f'以下模型不支持 reasoning=off：{unsupported}')
LOGGER.info('LM Studio 管理 API 与四个目标 model key 检查通过；smoke_required 将由实际生成验证。')

,model,model_key,quantization,params,reasoning_default,reasoning_off_capability,loaded_instances
0,Qwen3.6 35B A3B,qwen/qwen3.6-35b-a3b,Q4_K_M,35B-A3B,off,advertised,0
1,Qwen3.6 27B No Thinking,local/qwen3.6-27b-no-thinking,Q4_K_M,27B,off,advertised,0
2,Gemma 4 26B A4B QAT,google/gemma-4-26b-a4b-qat,Q4_0,26B-A4B,off,advertised,0
3,Gemma 4 31B QAT,google/gemma-4-31b-qat,Q4_0,31B,off,advertised,0

2026-08-26 16:28:14,424 | INFO | LM Studio 管理 API 与四个目标 model key 检查通过；smoke_required 将由实际生成验证。

In [3]:
# ===== Smoke 批量切换辅助函数 =====
SMOKE_TEXT = 'Heavy rain caused flooding in the region.'
SMOKE_SYSTEM_PROMPT = (
    'Extract causal relations and output one strict JSON object only. '
    'Use schema {\"has_causal\": true, \"triples\": '    '[{\"cause\": {\"span\": \"...\"}, \"relation\": \"caused\", '    '\"effect\": {\"span\": \"...\"}}]}. '    'Do not output reasoning, Markdown, or any text outside the JSON.'
)


def _message_text(payload: dict[str, Any]) -> str:
    return '\n'.join(
        str(item.get('content', ''))
        for item in payload.get('output', [])
        if isinstance(item, dict) and item.get('type') == 'message'
    ).strip()


def run_smoke_batch(
    model_runs: list[dict[str, Any]],
    lmstudio: LLMClient,
) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for position, run in enumerate(model_runs, 1):
        row: dict[str, Any] = {
            'order': position,
            'model': run['display_name'],
            'model_key': run['model_key'],
            'load': False,
            'reasoning_tokens': None,
            'no_reasoning': False,
            'causal_json': False,
            'unload': False,
            'passed': False,
            'error': '',
        }
        LOGGER.info('[smoke %s/%s] 准备加载 %s', position, len(model_runs), run['model_key'])
        try:
            lmstudio.unload_all_models()
            load_result = lmstudio.load_model(
                str(run['model_key']),
                context_length=CONTEXT_LENGTH,
            )
            instance_id = str(load_result['instance_id'])
            row['instance_id'] = instance_id
            row['load_config'] = json.dumps(load_result.get('load_config', {}), ensure_ascii=False)
            row['load'] = load_result.get('status') == 'loaded'

            smoke_payload = lmstudio.chat_rest(
                SMOKE_TEXT,
                model=instance_id,
                system_prompt=SMOKE_SYSTEM_PROMPT,
                reasoning='off',
                max_output_tokens=512,
            )
            content = _message_text(smoke_payload)
            reasoning_items = [
                item
                for item in smoke_payload.get('output', [])
                if isinstance(item, dict) and item.get('type') == 'reasoning'
            ]
            reasoning_tokens = smoke_payload.get('stats', {}).get('reasoning_output_tokens')
            row['reasoning_tokens'] = reasoning_tokens
            row['no_reasoning'] = (
                reasoning_tokens == 0
                and not reasoning_items
                and '<think>' not in content.lower()
            )
            parsed = parse_output(content)
            row['causal_json'] = bool(parsed.get('has_causal')) and bool(parsed.get('triples'))
            row['raw_output'] = content
            row['passed'] = bool(row['load'] and row['no_reasoning'] and row['causal_json'])
        except Exception as exc:
            row['error'] = f'{type(exc).__name__}: {exc}'
            LOGGER.exception('[smoke %s/%s] %s 失败', position, len(model_runs), run['model_key'])
        finally:
            try:
                lmstudio.unload_all_models()
                row['unload'] = True
            except Exception as unload_exc:
                row['passed'] = False
                unload_message = f'{type(unload_exc).__name__}: {unload_exc}'
                row['error'] = '; '.join(part for part in [row['error'], unload_message] if part)
                LOGGER.exception('[smoke %s/%s] 卸载失败', position, len(model_runs))
        results.append(row)
    return results

In [4]:
# ===== 阶段 1：四模型逐个 load -> smoke -> unload =====
SMOKE_RESULTS = run_smoke_batch(MODEL_RUNS, manager)
smoke_df = pd.DataFrame(SMOKE_RESULTS)
display(smoke_df[[
    'order', 'model', 'model_key', 'load', 'reasoning_tokens',
    'no_reasoning', 'causal_json', 'unload', 'passed', 'error',
]])
LOGGER.info('Smoke 通过：%s/%s', int(smoke_df['passed'].sum()), len(smoke_df))

2026-08-26 16:28:35,905 | INFO | [smoke 1/4] 准备加载 qwen/qwen3.6-35b-a3b
2026-08-26 16:28:57,871 | INFO | [smoke 2/4] 准备加载 local/qwen3.6-27b-no-thinking
2026-08-26 16:29:16,030 | INFO | [smoke 3/4] 准备加载 google/gemma-4-26b-a4b-qat
2026-08-26 16:29:30,840 | INFO | [smoke 4/4] 准备加载 google/gemma-4-31b-qat

,order,model,model_key,load,reasoning_tokens,no_reasoning,causal_json,unload,passed,error
0,1,Qwen3.6 35B A3B,qwen/qwen3.6-35b-a3b,True,0,True,True,True,True,
1,2,Qwen3.6 27B No Thinking,local/qwen3.6-27b-no-thinking,True,0,True,True,True,True,
2,3,Gemma 4 26B A4B QAT,google/gemma-4-26b-a4b-qat,True,0,True,True,True,True,
3,4,Gemma 4 31B QAT,google/gemma-4-31b-qat,True,0,True,True,True,True,

2026-08-26 16:29:48,965 | INFO | Smoke 通过：4/4

## 阶段 2：正式固定 test 批量评测

先确认上面的四行 smoke 均为 `passed=True`。正式评测不会自动开始；回到全局配置，将 `RUN_BATCH_EVAL` 改为 `True`，再运行下面两个单元格。

每个模型都使用自己的配置行。正式评测使用模型定义中的 `Enable Thinking=False`；smoke 另行通过原生 API 验证 `reasoning=off`。每个模型结束后，无论成功或失败，都会进入卸载步骤。

In [5]:
# ===== 正式批量评测辅助函数 =====
def _extra_body_for_run(run: dict[str, Any]) -> dict[str, Any]:
    return {'cache_prompt': False, **(run.get('llm_extra_body') or {})}


def _rag_paths_for_run(run: dict[str, Any]) -> tuple[Path | None, Path | None]:
    if not run['use_rag']:
        return None, None

    metadata_path, embeddings_path = resolve_rag_cache_paths(str(run['rag_database']))
    if DATASET_NAME == 'cnc_sft_test' and str(run['rag_database']) == 'cnc':
        sft_manifest = json.loads((PROJECT_ROOT / 'Data/CNC_sft/split_manifest.json').read_text(encoding='utf-8'))
        rag_manifest = json.loads((PROJECT_ROOT / 'RAG Database/cnc_split_manifest.json').read_text(encoding='utf-8'))
        test_ids = {str(sample_id) for sample_id in sft_manifest['split_ids']['test']}
        overlap = test_ids.intersection(str(sample_id) for sample_id in rag_manifest['support_ids'])
        if overlap:
            raise RuntimeError(
                f'拒绝在 cnc_sft_test 上使用现有 CNC RAG：support 与 test 有 {len(overlap)} 个精确 ID 重叠。'
            )
    return metadata_path, embeddings_path


def _load_eval_client(run: dict[str, Any]) -> tuple[str, LLMClient]:
    run_context_length = int(run.get('context_length', CONTEXT_LENGTH))
    run_parallel = run.get('parallel')
    run_offload_kv = bool(run.get('offload_kv_cache_to_gpu', True))
    load_result = manager.load_model(
        str(run['model_key']),
        context_length=run_context_length,
        parallel=None if run_parallel is None else int(run_parallel),
        offload_kv_cache_to_gpu=run_offload_kv,
    )
    load_config = load_result.get('load_config', {})
    actual_context = int(load_config.get('context_length', 0))
    actual_parallel = load_config.get('parallel')
    actual_offload_kv = load_config.get('offload_kv_cache_to_gpu')
    if (
        actual_context != run_context_length
        or (run_parallel is not None and int(actual_parallel or 0) != int(run_parallel))
        or actual_offload_kv is not run_offload_kv
    ):
        raise RuntimeError(
            '模型实际加载配置与目标不一致：'
            f'context={actual_context}/{run_context_length}, '
            f'parallel={actual_parallel}/{run_parallel}, '
            f'kv_cache_gpu={actual_offload_kv}/{run_offload_kv}。'
        )
    instance_id = str(load_result['instance_id'])
    client = LLMClient(
        provider='lmstudio',
        base_url=LMSTUDIO_BASE_URL,
        model=instance_id,
        api_key=LMSTUDIO_API_KEY,
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
        context_length=run_context_length,
        extra_body=_extra_body_for_run(run),
        timeout=LLM_TIMEOUT,
        retry_times=LLM_RETRY_TIMES,
    )
    return instance_id, client


def _summary_row(run: dict[str, Any], report: dict[str, Any]) -> dict[str, Any]:
    detection = report['detection']
    strict = report['extraction']['strict_token_f1']
    anchor = report['extraction']['anchor_window']
    return {
        'status': 'completed',
        'model': run['display_name'],
        'model_key': run['model_key'],
        'prompt': run['prompt_name'],
        'rag': 'off' if not run['use_rag'] else f"{run['rag_mode']}-k{run['rag_top_k']}",
        'temperature': TEMPERATURE,
        'context_length': int(run.get('context_length', CONTEXT_LENGTH)),
        'max_tokens': MAX_TOKENS,
        'parallel': run.get('parallel', 'model_default'),
        'reload_every_samples': int(run.get('reload_every_samples', 0) or 0),
        'cache_prompt': _extra_body_for_run(run)['cache_prompt'],
        'offload_kv_cache_to_gpu': bool(run.get('offload_kv_cache_to_gpu', True)),
        'reasoning': 'model_default_off',
        'n_samples': report['n_samples'],
        'n_causal_gold': report['n_causal_gold'],
        'n_causal_pred': report['n_causal_pred'],
        'detection_tp': detection['tp'],
        'detection_tn': detection['tn'],
        'detection_fp': detection['fp'],
        'detection_fn': detection['fn'],
        'all_n_eval_samples': strict['all_samples']['n_eval_samples'],
        'all_n_gold_triples': strict['all_samples']['n_gold_triples'],
        'all_n_pred_triples': strict['all_samples']['n_pred_triples'],
        'strict_all_tp': strict['all_samples']['tp'],
        'strict_all_fp': strict['all_samples']['fp'],
        'strict_all_fn': strict['all_samples']['fn'],
        'anchor_all_tp': anchor['all_samples']['tp'],
        'anchor_all_fp': anchor['all_samples']['fp'],
        'anchor_all_fn': anchor['all_samples']['fn'],
        'detected_n_eval_samples': strict['detected_only']['n_eval_samples'],
        'detected_n_gold_triples': strict['detected_only']['n_gold_triples'],
        'detected_n_pred_triples': strict['detected_only']['n_pred_triples'],
        'strict_detected_tp': strict['detected_only']['tp'],
        'strict_detected_fp': strict['detected_only']['fp'],
        'strict_detected_fn': strict['detected_only']['fn'],
        'anchor_detected_tp': anchor['detected_only']['tp'],
        'anchor_detected_fp': anchor['detected_only']['fp'],
        'anchor_detected_fn': anchor['detected_only']['fn'],
        'detection_precision': detection['precision'],
        'detection_recall': detection['recall'],
        'detection_f1': detection['f1'],
        'strict_all_precision': strict['all_samples']['precision'],
        'strict_all_recall': strict['all_samples']['recall'],
        'strict_all_f1': strict['all_samples']['f1'],
        'anchor_all_precision': anchor['all_samples']['precision'],
        'anchor_all_recall': anchor['all_samples']['recall'],
        'anchor_all_f1': anchor['all_samples']['f1'],
        'strict_detected_only_f1': strict['detected_only']['f1'],
        'anchor_detected_only_f1': anchor['detected_only']['f1'],
        'report_path': report.get('report_path', ''),
        'error': '',
    }


def run_formal_batch(
    model_runs: list[dict[str, Any]],
    *,
    existing_retrievers: dict[str, Any] | None = None,
    samples_override: list[dict[str, Any]] | None = None,
    require_all_smoke: bool = REQUIRE_ALL_SMOKE_PASS,
) -> list[dict[str, Any]]:
    if require_all_smoke:
        if 'SMOKE_RESULTS' not in globals():
            raise RuntimeError('请先运行四模型 smoke 单元格。')
        failed_smokes = [row['model_key'] for row in SMOKE_RESULTS if not row['passed']]
        if failed_smokes:
            raise RuntimeError(f'以下模型 smoke 未通过，正式评测未启动：{failed_smokes}')

    samples = (
        samples_override
        if samples_override is not None
        else load_dataset(DATASET_NAME, n=EVAL_SAMPLE_N)
    )
    rows: list[dict[str, Any]] = []
    for position, run in enumerate(model_runs, 1):
        LOGGER.info('[eval %s/%s] 开始 %s', position, len(model_runs), run['model_key'])
        try:
            manager.unload_all_models()
            metadata_path, embeddings_path = _rag_paths_for_run(run)
            run_id = str(run.get('run_id', run['model_key']))
            run_context_length = int(run.get('context_length', CONTEXT_LENGTH))
            reload_every_samples = int(run.get('reload_every_samples', 0) or 0)
            if reload_every_samples < 0:
                raise ValueError('reload_every_samples 不能为负数。')
            if reload_every_samples and EVAL_MAX_WORKERS != 1:
                raise RuntimeError('周期性模型重载要求 EVAL_MAX_WORKERS=1，以确保按样本计数。')
            instance_id, client = _load_eval_client(run)
            completed_samples = 0

            def generate_with_periodic_reload(**generator_kwargs: Any) -> dict[str, Any]:
                nonlocal instance_id, client, completed_samples
                if (
                    reload_every_samples
                    and completed_samples > 0
                    and completed_samples % reload_every_samples == 0
                ):
                    LOGGER.info(
                        '[eval] 已完成 %s 条，重新加载 %s 后继续。',
                        completed_samples,
                        run['model_key'],
                    )
                    manager.unload_all_models()
                    instance_id, client = _load_eval_client(run)
                generator_kwargs['client'] = client
                prediction = generate(**generator_kwargs)
                completed_samples += 1
                return prediction
            eval_config = EvalRunConfig(
                project_root=PROJECT_ROOT,
                model=instance_id,
                dataset=DATASET_NAME,
                prompt_name=str(run['prompt_name']),
                use_rag=bool(run['use_rag']),
                rag_mode=str(run['rag_mode']),
                rag_top_k=int(run['rag_top_k']),
                temperature=TEMPERATURE,
                max_tokens=MAX_TOKENS,
                primary_metric=str(run.get('primary_metric', 'anchor_window')),
                progress_every=EVAL_PROGRESS_EVERY,
                max_workers=EVAL_MAX_WORKERS,
                llm_provider='lmstudio',
                llm_base_url=LMSTUDIO_BASE_URL,
                context_length=run_context_length,
                reasoning_effort=None,
                llm_extra_body=_extra_body_for_run(run),
                api_key_source='lmstudio-default',
                save_report=True,
                report_dir=REPORT_DIR,
                report_detail_limit=200,
                report_detail_mode='errors',
                report_error_metric=str(run.get('primary_metric', 'anchor_window')),
                metadata_path=metadata_path,
                embeddings_path=embeddings_path,
            )
            report = run_stream_eval(
                samples=samples,
                label=str(run.get('label', f"{run['display_name']} CNC fixed test")),
                client=client,
                config=eval_config,
                generator=generate_with_periodic_reload,
                existing_retriever=(existing_retrievers or {}).get(run_id),
                progress_factory=_notebook_progress,
                emit=LOGGER.info,
            )
            rows.append(_summary_row(run, report))
        except Exception as exc:
            LOGGER.exception('[eval %s/%s] %s 失败', position, len(model_runs), run['model_key'])
            rows.append({
                'status': 'failed',
                'model': run['display_name'],
                'model_key': run['model_key'],
                'prompt': run['prompt_name'],
                'rag': 'off' if not run['use_rag'] else f"{run['rag_mode']}-k{run['rag_top_k']}",
                'temperature': TEMPERATURE,
                'context_length': CONTEXT_LENGTH,
                'max_tokens': MAX_TOKENS,
                'parallel': run.get('parallel', 'model_default'),
                'reload_every_samples': int(run.get('reload_every_samples', 0) or 0),
                'cache_prompt': _extra_body_for_run(run)['cache_prompt'],
                'reasoning': 'model_default_off',
                'error': f'{type(exc).__name__}: {exc}',
            })
        finally:
            try:
                manager.unload_all_models()
            except Exception:
                LOGGER.exception('[eval %s/%s] 评测后卸载失败', position, len(model_runs))
    return rows

In [6]:
# ===== 阶段 2：正式批量评测（默认不会运行） =====
if not RUN_BATCH_EVAL:
    LOGGER.warning('正式批量评测未启动。确认 smoke 后，将 RUN_BATCH_EVAL 改为 True。')
else:
    BATCH_RESULTS = run_formal_batch(MODEL_RUNS)
    batch_summary_df = pd.DataFrame(BATCH_RESULTS)
    display(batch_summary_df)

2026-08-26 16:30:19,137 | INFO | [eval 1/4] 开始 qwen/qwen3.6-35b-a3b
2026-08-26 16:30:37,720 | INFO | Pattern examples 已加载：path=D:\Master thesis\RAG Database\cnc_examples.jsonl examples=600
2026-08-26 16:30:37,733 | INFO | KNN cache 已加载：examples=600 path=D:\Master thesis\RAG Database\cnc_examples.jsonl embedding_device=cpu

D:\Anaconda3\envs\Master_thesis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-26 16:30:49,693 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:49,724 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 16:30:49,880 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:49,910 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 16:30:49,913 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-08-26 16:30:50,063 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:50,091 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 16:30:50,254 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:50,282 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-08-26 16:30:50,437 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:50,467 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 16:30:50,637 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:50,666 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-26 16:30:50,877 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-26 16:30:51,077 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:51,105 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 7747.12it/s]
2026-08-26 16:30:51,432 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 16:30:51,589 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 16:30:51,750 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 16:30:51,908 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 16:30:52,085 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:52,114 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 16:30:52,270 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:52,299 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 16:30:52,462 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:52,490 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 16:30:52,647 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:52,675 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 16:30:52,838 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-26 16:30:53,052 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-26 16:30:53,282 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 16:30:53,312 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-26 16:30:53,490 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-08-26 16:30:57,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:30:58,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:01,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:03,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:04,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:07,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:08,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:10,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:11,135 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:13,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:16,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:17,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:21,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:24,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:25,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:25,963 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:26,979 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:29,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:32,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:31:35,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:35,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:36,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:37,787 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:38,774 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:39,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:40,581 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:42,864 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:43,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:46,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:47,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:49,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:50,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:51,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:52,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:54,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:55,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:31:59,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:01,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:02,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:05,135 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:07,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:09,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:12,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:14,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:15,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:16,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:18,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:19,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:22,359 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:24,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:24,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:27,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:28,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:29,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:30,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:33,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:35,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:38,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:41,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:43,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:45,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:48,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:50,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:52,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:53,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:56,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:58,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:32:59,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:02,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:03,083 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:04,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:04,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:07,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:09,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:11,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:12,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:13,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:15,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:16,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:19,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:21,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:22,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:23,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:27,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:28,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:30,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:32,397 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:33,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:34,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:35,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:37,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:41,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:43,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:33:46,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:48,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:49,365 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:52,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:54,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:56,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:58,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:33:58,959 | INFO |
2026-08-26 16:33:58,960 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 100/1038 ================
样本总数: 100
  Gold 含因果: 57 | Pred 含因果: 56
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.770
  Precision: 0.804
  Recall   : 0.789
  F1       : 0.796
  (TP=45, TN=32, FP=11, FN=12)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 100
    Gold triples: 81 | Pred triples: 65
    Precision: 0.569
    Recall   : 0.457
    F1       : 0.507
    (TP=37, FP=28, FN=44)
  [anchor_window] (primary)
    样本数: 100
    Gold triples: 81 | Pred triples: 65
    Precision: 0.446
    Recall   : 0.358
    F1       : 0.397
    (TP=29, FP=36, FN=52)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 45
    Gold triples: 67 | Pred triples: 54
    Precision: 0.685
    Recall   : 0.552
    F1       : 0.612
    (TP=37, FP=17, FN=30)
  [anchor_window] (primary)
    样本数: 45
    Gold triples: 67 | Pred triples: 54
    Precision: 0.537
    Recall   : 0.433
    F1       : 0.479
    (TP=29, FP=25, FN=38)
================================================
2026-08-26 16:33:59,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:00,893 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:01,815 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:03,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:04,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:05,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:06,838 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:07,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:10,364 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:11,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:14,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:17,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:19,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:20,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:22,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:23,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:25,328 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:26,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:27,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:29,245 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:30,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:33,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:35,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:38,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:39,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:42,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:44,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:46,000 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:48,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:49,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:52,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:53,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:54,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:56,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:59,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:34:59,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:00,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:01,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:04,459 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:05,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:06,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:09,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:10,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:12,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:14,898 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:15,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:16,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:17,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:18,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:21,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:23,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:25,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:26,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:29,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:29,914 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:35:30,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:34,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:34,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:35,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:37,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:40,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:42,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:43,073 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:45,787 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:48,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:49,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:51,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:53,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:54,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:56,851 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:35:59,241 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:00,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:01,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:03,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:05,316 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:07,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:08,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:09,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:10,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:11,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:13,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:14,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:15,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:16,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:18,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:19,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:21,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:23,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:25,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:28,095 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:30,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:33,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:34,067 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:35,873 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:38,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:38,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:39,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:40,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:41,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:44,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:44,179 | INFO |
2026-08-26 16:36:44,179 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 200/1038 ================
样本总数: 200
  Gold 含因果: 107 | Pred 含因果: 105
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.810
  Precision: 0.829
  Recall   : 0.813
  F1       : 0.821
  (TP=87, TN=75, FP=18, FN=20)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 200
    Gold triples: 147 | Pred triples: 119
    Precision: 0.546
    Recall   : 0.442
    F1       : 0.489
    (TP=65, FP=54, FN=82)
  [anchor_window] (primary)
    样本数: 200
    Gold triples: 147 | Pred triples: 119
    Precision: 0.437
    Recall   : 0.354
    F1       : 0.391
    (TP=52, FP=67, FN=95)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 87
    Gold triples: 125 | Pred triples: 100
    Precision: 0.650
    Recall   : 0.520
    F1       : 0.578
    (TP=65, FP=35, FN=60)
  [anchor_window] (primary)
    样本数: 87
    Gold triples: 125 | Pred triples: 100
    Precision: 0.520
    Recall   : 0.416
    F1       : 0.462
    (TP=52, FP=48, FN=73)
================================================
2026-08-26 16:36:49,351 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:50,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:51,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:53,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:54,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:57,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:36:59,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:00,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:01,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:01,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:03,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:06,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:07,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:08,351 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:10,646 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:12,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:15,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:37:16,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:16,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:17,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:18,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:21,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:22,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:23,002 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:23,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:26,522 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:28,825 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:29,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:30,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:31,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:33,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:35,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:37,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:38,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:39,755 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:40,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:42,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:45,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:45,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:46,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:47,755 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:50,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:52,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:54,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:55,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:56,241 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:58,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:37:59,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:02,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:03,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:05,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:07,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:08,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:09,211 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:11,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:12,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:13,614 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:16,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:17,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:17,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:18,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:19,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:22,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:24,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:27,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:29,271 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:31,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:33,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:35,328 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:36,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:38,073 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:39,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:40,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:42,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:43,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:45,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:46,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:47,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:49,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:50,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:53,313 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:54,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:38:56,867 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:02,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:03,046 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:04,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:07,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:09,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:10,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:12,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:13,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:39:15,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:18,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:20,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:21,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:23,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:24,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:25,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:26,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:27,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:27,185 | INFO |
2026-08-26 16:39:27,186 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 300/1038 ================
样本总数: 300
  Gold 含因果: 155 | Pred 含因果: 153
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.780
  Precision: 0.791
  Recall   : 0.781
  F1       : 0.786
  (TP=121, TN=113, FP=32, FN=34)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 300
    Gold triples: 214 | Pred triples: 171
    Precision: 0.520
    Recall   : 0.416
    F1       : 0.462
    (TP=89, FP=82, FN=125)
  [anchor_window] (primary)
    样本数: 300
    Gold triples: 214 | Pred triples: 171
    Precision: 0.392
    Recall   : 0.313
    F1       : 0.348
    (TP=67, FP=104, FN=147)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 121
    Gold triples: 177 | Pred triples: 138
    Precision: 0.645
    Recall   : 0.503
    F1       : 0.565
    (TP=89, FP=49, FN=88)
  [anchor_window] (primary)
    样本数: 121
    Gold triples: 177 | Pred triples: 138
    Precision: 0.486
    Recall   : 0.379
    F1       : 0.425
    (TP=67, FP=71, FN=110)
================================================
2026-08-26 16:39:29,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:31,657 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:32,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:34,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:35,455 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:36,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:38,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:39,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:40,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:43,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:45,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:48,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:51,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:52,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:54,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:55,914 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:39:58,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:01,625 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:02,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:03,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:04,463 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:05,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:06,246 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:07,155 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:10,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:13,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:14,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:15,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:17,799 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:20,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:21,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:23,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:26,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:28,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:29,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:31,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:32,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:32,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:34,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:36,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:36,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:39,167 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:41,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:44,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:46,987 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:48,844 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:49,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:50,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:53,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:55,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:40:58,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:01,536 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:03,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:41:04,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:06,438 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:09,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:11,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:16,571 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:17,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:19,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:22,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:24,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:25,275 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:26,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:27,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:27,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:30,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:30,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:32,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:33,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:35,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:39,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:41,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:42,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:45,063 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:45,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:48,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:51,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:52,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:53,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:54,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:54,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:55,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:56,800 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:57,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:41:58,675 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:02,147 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:03,168 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:05,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:06,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:08,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:09,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:12,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:14,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:16,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:17,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:19,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:20,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:22,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:23,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:23,691 | INFO |
2026-08-26 16:42:23,692 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 400/1038 ================
样本总数: 400
  Gold 含因果: 202 | Pred 含因果: 206
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.810
  Precision: 0.806
  Recall   : 0.822
  F1       : 0.814
  (TP=166, TN=158, FP=40, FN=36)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 400
    Gold triples: 279 | Pred triples: 233
    Precision: 0.515
    Recall   : 0.430
    F1       : 0.469
    (TP=120, FP=113, FN=159)
  [anchor_window] (primary)
    样本数: 400
    Gold triples: 279 | Pred triples: 233
    Precision: 0.399
    Recall   : 0.333
    F1       : 0.363
    (TP=93, FP=140, FN=186)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 166
    Gold triples: 238 | Pred triples: 190
    Precision: 0.632
    Recall   : 0.504
    F1       : 0.561
    (TP=120, FP=70, FN=118)
  [anchor_window] (primary)
    样本数: 166
    Gold triples: 238 | Pred triples: 190
    Precision: 0.489
    Recall   : 0.391
    F1       : 0.435
    (TP=93, FP=97, FN=145)
================================================
2026-08-26 16:42:24,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:26,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:28,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:30,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:30,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:31,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:33,738 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:34,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:39,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:41,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:43,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:44,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:45,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:46,183 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:47,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:42:48,059 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:50,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:52,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:53,825 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:54,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:42:57,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:00,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:00,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:02,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:04,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:05,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:06,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:07,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:09,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:12,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:14,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:15,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:18,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:19,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:21,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:22,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:25,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:27,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:28,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:30,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:34,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:36,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:37,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:39,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:41,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:43,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:45,814 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:46,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:47,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:48,514 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:51,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:52,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:55,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:58,549 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:43:59,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:01,776 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:03,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:06,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:08,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:10,714 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:14,391 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:16,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:19,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:21,740 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:24,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:26,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:28,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:29,936 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:32,245 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:34,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:36,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:37,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:39,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:41,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:43,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:46,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:47,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:48,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:50,847 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:53,143 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:55,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:56,147 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:58,256 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:59,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:44:59,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:01,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:02,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:04,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:05,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:45:08,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:11,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:15,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:16,254 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:17,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:19,328 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:21,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:24,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:26,893 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:28,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:31,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:31,006 | INFO |
2026-08-26 16:45:31,007 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 500/1038 ================
样本总数: 500
  Gold 含因果: 266 | Pred 含因果: 269
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.802
  Precision: 0.810
  Recall   : 0.820
  F1       : 0.815
  (TP=218, TN=183, FP=51, FN=48)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 500
    Gold triples: 369 | Pred triples: 305
    Precision: 0.498
    Recall   : 0.412
    F1       : 0.451
    (TP=152, FP=153, FN=217)
  [anchor_window] (primary)
    样本数: 500
    Gold triples: 369 | Pred triples: 305
    Precision: 0.407
    Recall   : 0.336
    F1       : 0.368
    (TP=124, FP=181, FN=245)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 218
    Gold triples: 314 | Pred triples: 249
    Precision: 0.610
    Recall   : 0.484
    F1       : 0.540
    (TP=152, FP=97, FN=162)
  [anchor_window] (primary)
    样本数: 218
    Gold triples: 314 | Pred triples: 249
    Precision: 0.498
    Recall   : 0.395
    F1       : 0.440
    (TP=124, FP=125, FN=190)
================================================
2026-08-26 16:45:33,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:34,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:35,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:37,357 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:38,348 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:42,590 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:44,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:45,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:46,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:49,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:51,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:52,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:54,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:56,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:45:58,859 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:02,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:03,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:06,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:08,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:09,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:12,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:13,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:15,515 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:16,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:17,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:19,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:22,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:24,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:25,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:26,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:28,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:32,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:33,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:35,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:38,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:41,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:42,142 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:44,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:46,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:48,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:50,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:52,946 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:55,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:57,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:57,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:46:58,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:01,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:02,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:03,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:05,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:08,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:47:11,550 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:14,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:16,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:20,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:21,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:22,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:24,907 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:25,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:26,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:28,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:31,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:34,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:34,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:35,896 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:36,815 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:38,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:39,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:42,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:43,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:44,354 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:45,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:46,493 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:47,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:48,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:50,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:52,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:54,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:57,033 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:57,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:47:59,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:00,847 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:01,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:05,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:07,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:09,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:12,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:14,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:14,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:17,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:19,351 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:20,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:22,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:26,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:27,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:29,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:31,962 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:34,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:35,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:36,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:36,018 | INFO |
2026-08-26 16:48:36,018 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 600/1038 ================
样本总数: 600
  Gold 含因果: 317 | Pred 含因果: 327
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.803
  Precision: 0.804
  Recall   : 0.830
  F1       : 0.817
  (TP=263, TN=219, FP=64, FN=54)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 600
    Gold triples: 443 | Pred triples: 374
    Precision: 0.487
    Recall   : 0.411
    F1       : 0.446
    (TP=182, FP=192, FN=261)
  [anchor_window] (primary)
    样本数: 600
    Gold triples: 443 | Pred triples: 374
    Precision: 0.374
    Recall   : 0.316
    F1       : 0.343
    (TP=140, FP=234, FN=303)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 263
    Gold triples: 382 | Pred triples: 305
    Precision: 0.597
    Recall   : 0.476
    F1       : 0.530
    (TP=182, FP=123, FN=200)
  [anchor_window] (primary)
    样本数: 263
    Gold triples: 382 | Pred triples: 305
    Precision: 0.459
    Recall   : 0.366
    F1       : 0.408
    (TP=140, FP=165, FN=242)
================================================
2026-08-26 16:48:38,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:40,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:42,794 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:45,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:46,130 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:46,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:47,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:50,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:51,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:52,615 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:53,496 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:54,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:55,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:48:56,391 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:48:59,962 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:01,063 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:04,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:05,125 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:06,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:06,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:09,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:11,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:16,192 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:18,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:20,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:23,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:26,142 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:28,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:29,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:31,457 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:32,478 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:34,477 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:37,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:38,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:39,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:40,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:41,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:42,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:43,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:46,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:46,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:47,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:49,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:50,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:52,883 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:53,780 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:54,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:55,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:57,814 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:49:58,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:00,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:01,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:03,893 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:04,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:05,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:08,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:12,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:14,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:16,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:17,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:18,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:19,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:21,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:23,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:26,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:27,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:27,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:30,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:31,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:33,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:35,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:37,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:40,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:43,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:45,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:47,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:48,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:51,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:53,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:54,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:57,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:50:57,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:02,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:03,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:04,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:04,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:07,196 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:51:08,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:10,255 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:12,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:13,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:16,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:17,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:19,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:22,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:24,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:25,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:26,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:28,296 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:30,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:30,341 | INFO |
2026-08-26 16:51:30,341 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 700/1038 ================
样本总数: 700
  Gold 含因果: 373 | Pred 含因果: 380
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.799
  Precision: 0.805
  Recall   : 0.820
  F1       : 0.813
  (TP=306, TN=253, FP=74, FN=67)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 700
    Gold triples: 521 | Pred triples: 436
    Precision: 0.495
    Recall   : 0.415
    F1       : 0.451
    (TP=216, FP=220, FN=305)
  [anchor_window] (primary)
    样本数: 700
    Gold triples: 521 | Pred triples: 436
    Precision: 0.401
    Recall   : 0.336
    F1       : 0.366
    (TP=175, FP=261, FN=346)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 306
    Gold triples: 447 | Pred triples: 357
    Precision: 0.605
    Recall   : 0.483
    F1       : 0.537
    (TP=216, FP=141, FN=231)
  [anchor_window] (primary)
    样本数: 306
    Gold triples: 447 | Pred triples: 357
    Precision: 0.490
    Recall   : 0.391
    F1       : 0.435
    (TP=175, FP=182, FN=272)
================================================
2026-08-26 16:51:31,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:33,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:35,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:36,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:39,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:41,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:43,840 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:46,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:47,064 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:49,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:52,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:53,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:55,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:58,026 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:51:59,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:01,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:04,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:06,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:07,422 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:10,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:11,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:12,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:14,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:18,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:20,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:21,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:24,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:27,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:29,714 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:30,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:31,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:32,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:33,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:36,172 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:38,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:39,456 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:40,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:41,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:43,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:46,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:48,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:50,777 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:51,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:53,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:56,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:58,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:52:58,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:00,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:01,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:53:02,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:03,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:04,682 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:07,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:08,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:09,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:10,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:14,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:16,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:18,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:19,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:20,351 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:21,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:22,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:24,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:26,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:27,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:29,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:31,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:33,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:35,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:36,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:37,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:38,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:39,530 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:40,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:41,435 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:42,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:43,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:45,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:46,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:47,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:48,299 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:50,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:52,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:55,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:58,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:58,961 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:53:59,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:02,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:04,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:05,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:07,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:10,047 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:12,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:12,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:15,007 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:17,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:19,590 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:20,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:21,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:21,434 | INFO |
2026-08-26 16:54:21,435 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 800/1038 ================
样本总数: 800
  Gold 含因果: 423 | Pred 含因果: 433
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.802
  Precision: 0.806
  Recall   : 0.825
  F1       : 0.815
  (TP=349, TN=293, FP=84, FN=74)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 800
    Gold triples: 591 | Pred triples: 494
    Precision: 0.492
    Recall   : 0.411
    F1       : 0.448
    (TP=243, FP=251, FN=348)
  [anchor_window] (primary)
    样本数: 800
    Gold triples: 591 | Pred triples: 494
    Precision: 0.409
    Recall   : 0.342
    F1       : 0.372
    (TP=202, FP=292, FN=389)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 349
    Gold triples: 510 | Pred triples: 405
    Precision: 0.600
    Recall   : 0.476
    F1       : 0.531
    (TP=243, FP=162, FN=267)
  [anchor_window] (primary)
    样本数: 349
    Gold triples: 510 | Pred triples: 405
    Precision: 0.499
    Recall   : 0.396
    F1       : 0.442
    (TP=202, FP=203, FN=308)
================================================
2026-08-26 16:54:23,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:25,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:29,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:30,987 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:33,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:34,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:35,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:36,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:37,794 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:38,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:41,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:54:42,814 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:45,390 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:47,526 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:48,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:49,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:52,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:52,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:53,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:56,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:54:58,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:01,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:03,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:04,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:06,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:08,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:11,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:13,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:16,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:17,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:18,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:20,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:22,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:24,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:25,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:26,026 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:26,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:29,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:30,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:31,106 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:34,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:35,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:35,969 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:38,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:39,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:41,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:46,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:48,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:50,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:51,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:55,281 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:58,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:55:59,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:00,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:02,456 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:05,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:06,275 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:08,678 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:11,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:12,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:14,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:16,385 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:18,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:21,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:23,936 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:26,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:27,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:28,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:30,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:31,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:32,381 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:34,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:37,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:41,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:43,765 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:45,776 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:46,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:48,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:51,251 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:52,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:54,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:56,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:58,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:56:59,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:02,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:57:04,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:05,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:08,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:10,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:13,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:14,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:15,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:16,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:18,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:19,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:22,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:24,383 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:27,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:29,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:30,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:30,655 | INFO |
2026-08-26 16:57:30,656 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 900/1038 ================
样本总数: 900
  Gold 含因果: 480 | Pred 含因果: 495
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.799
  Precision: 0.802
  Recall   : 0.827
  F1       : 0.814
  (TP=397, TN=322, FP=98, FN=83)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 900
    Gold triples: 669 | Pred triples: 561
    Precision: 0.492
    Recall   : 0.413
    F1       : 0.449
    (TP=276, FP=285, FN=393)
  [anchor_window] (primary)
    样本数: 900
    Gold triples: 669 | Pred triples: 561
    Precision: 0.410
    Recall   : 0.344
    F1       : 0.374
    (TP=230, FP=331, FN=439)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 397
    Gold triples: 579 | Pred triples: 458
    Precision: 0.603
    Recall   : 0.477
    F1       : 0.532
    (TP=276, FP=182, FN=303)
  [anchor_window] (primary)
    样本数: 397
    Gold triples: 579 | Pred triples: 458
    Precision: 0.502
    Recall   : 0.397
    F1       : 0.444
    (TP=230, FP=228, FN=349)
================================================
2026-08-26 16:57:32,934 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:33,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:37,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:38,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:38,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:41,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:42,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:44,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:45,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:47,718 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:49,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:51,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:54,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:55,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:57,035 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:57:59,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:02,388 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:03,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:04,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:05,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:07,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:08,093 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:11,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:12,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:15,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:16,905 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:19,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:21,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:22,831 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:25,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:26,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:28,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:29,788 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:30,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:32,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:33,812 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:36,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:38,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:39,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:41,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:44,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:45,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:46,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:48,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:50,382 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:52,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:53,521 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 16:58:55,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:56,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:57,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:58:58,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:00,449 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:02,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:03,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:04,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:05,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:08,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:09,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:10,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:12,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:13,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:14,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:14,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:17,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:19,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:22,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:23,660 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:25,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:26,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:28,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:31,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:32,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:34,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:36,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:38,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:41,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:43,851 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:44,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:47,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:48,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:50,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:52,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:54,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:57,607 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 16:59:59,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:02,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:03,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:06,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:06,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:07,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:09,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:11,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:12,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:13,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:14,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:15,125 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:16,005 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:16,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:17,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:19,848 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:19,849 | INFO |
2026-08-26 17:00:19,851 | INFO | ================ Qwen3.6 35B A3B CNC fixed test progress 1000/1038 ================
样本总数: 1000
  Gold 含因果: 529 | Pred 含因果: 548
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.797
  Precision: 0.797
  Recall   : 0.826
  F1       : 0.812
  (TP=437, TN=360, FP=111, FN=92)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1000
    Gold triples: 739 | Pred triples: 618
    Precision: 0.485
    Recall   : 0.406
    F1       : 0.442
    (TP=300, FP=318, FN=439)
  [anchor_window] (primary)
    样本数: 1000
    Gold triples: 739 | Pred triples: 618
    Precision: 0.405
    Recall   : 0.338
    F1       : 0.368
    (TP=250, FP=368, FN=489)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 437
    Gold triples: 637 | Pred triples: 502
    Precision: 0.598
    Recall   : 0.471
    F1       : 0.527
    (TP=300, FP=202, FN=337)
  [anchor_window] (primary)
    样本数: 437
    Gold triples: 637 | Pred triples: 502
    Precision: 0.498
    Recall   : 0.392
    F1       : 0.439
    (TP=250, FP=252, FN=387)
================================================
2026-08-26 17:00:20,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:22,962 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:25,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:28,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:31,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:33,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:34,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:35,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:36,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:00:37,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:39,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:42,143 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:42,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:43,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:46,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:47,867 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:48,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:49,739 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:53,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:56,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:57,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:00:59,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:01,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:03,680 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:06,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:07,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:08,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:11,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:12,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:13,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:14,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:16,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:19,054 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:19,969 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:21,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:23,303 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:25,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:28,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:28,881 | INFO |
2026-08-26 17:01:28,881 | INFO | ================ Qwen3.6 35B A3B CNC fixed test final report ================
样本总数: 1038
  Gold 含因果: 548 | Pred 含因果: 568
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.802
  Precision: 0.801
  Recall   : 0.830
  F1       : 0.815
  (TP=455, TN=377, FP=113, FN=93)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1038
    Gold triples: 763 | Pred triples: 641
    Precision: 0.493
    Recall   : 0.414
    F1       : 0.450
    (TP=316, FP=325, FN=447)
  [anchor_window] (primary)
    样本数: 1038
    Gold triples: 763 | Pred triples: 641
    Precision: 0.407
    Recall   : 0.342
    F1       : 0.372
    (TP=261, FP=380, FN=502)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 455
    Gold triples: 660 | Pred triples: 523
    Precision: 0.604
    Recall   : 0.479
    F1       : 0.534
    (TP=316, FP=207, FN=344)
  [anchor_window] (primary)
    样本数: 455
    Gold triples: 660 | Pred triples: 523
    Precision: 0.499
    Recall   : 0.395
    F1       : 0.441
    (TP=261, FP=262, FN=399)
================================================
2026-08-26 17:01:28,882 | INFO | ================ 前 10 条样本判定 ================

--- id=1120 ---
text: They were attacking a student leader and a fighter .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2291 ---
text: Protesters have also surrounded the police headquarters twice in past weeks in noisy and emotionally charged protests in which young people spray-painted obscenities on its front wall and barricaded its entrances .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2733 ---
text: Authorities also rejected a request to hold one on Sunday in Sheung Wan , near where police fired teargas and rubber bullets on demonstrators who had defaced China ’ s representative office in Hong Kong last week .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "police fired teargas and rubber bullets on demonstrators who had defaced China ’ s representative office in Hong Kong last week"
    },
    "relation": "caused",
    "effect": {
      "span": "Authorities also rejected a request to hold one on Sunday in Sheung Wan"
    }
  }
]

--- id=2124 ---
text: On Tuesday we went to picket at the Western Cape Provincial Legislature after we had gone over a month without teachers .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 1}
gold_relations:
[
  {
    "cause": "we had gone over a month without teachers",
    "effect": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "we had gone over a month without teachers"
    },
    "relation": "caused",
    "effect": {
      "span": "we went to picket at the Western Cape Provincial Legislature"
    }
  }
]

--- id=450 ---
text: Protestors in Clashes With Police on Jammu-Pathankot NH During Eviction Drive 22nd February 2016 05:22 PM JAMMU : Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday , police said .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=777 ---
text: ANDHRA PRADESH ` Delay ' in compensation : ryots lay siege to MRO office March 14 , 2006 00:00 IST Staff Reporter Telugu Desam , CPI(M) leaders lead the protest VIJAYAWADA : Betel nut farmers from Garikaparru and Thotlavalluru villages under Thotlavalluru mandal laid siege to the Mandal Revenue Office on Monday .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "Delay ' in compensation"
    },
    "relation": "caused",
    "effect": {
      "span": "ryots lay siege to MRO office"
    }
  }
]

--- id=769 ---
text: The march was organised by the Federation of South African Women ( Fedsaw ) and led by Helen Joseph , Rahima Moosa , Sophie Williams and Lilian Ngoyi .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=542 ---
text: We totally support the ongoing strike since VAT imposed by the government is unjust but the business has to run if we are to recover losses , ” said a shop owner near Charminar .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "VAT imposed by the government is unjust",
    "effect": "We totally support the ongoing strike"
  },
  {
    "cause": "if we are to recover losses",
    "effect": "the business has to run"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "VAT imposed by the government is unjust"
    },
    "relation": "caused",
    "effect": {
      "span": "We totally support the ongoing strike"
    }
  }
]

--- id=1420 ---
text: The protest went on for more than two hours and shops on the highway were shut during that time .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1368 ---
text: According to one villager , officials have frozen that money to prevent villagers funding a journey to Beijing to continue their petitioning .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "to prevent villagers funding a journey to Beijing to continue their petitioning",
    "effect": "officials have frozen that money"
  },
  {
    "cause": "to continue their petitioning",
    "effect": "villagers funding a journey to Beijing"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "to prevent villagers funding a journey to Beijing to continue their petitioning"
    },
    "relation": "caused",
    "effect": {
      "span": "officials have frozen that money"
    }
  }
]

2026-08-26 17:01:28,898 | INFO | Eval report saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\qwen-qwen3.6-35b-a3b_cnc_sft_test-n1038_prompt-v9.6_rag-knn_pattern-k1_20260826-170128.md
2026-08-26 17:01:28,928 | INFO | [eval 2/4] 开始 local/qwen3.6-27b-no-thinking
2026-08-26 17:01:44,132 | INFO | Pattern examples 已加载：path=D:\Master thesis\RAG Database\cnc_examples.jsonl examples=600
2026-08-26 17:01:44,141 | INFO | KNN cache 已加载：examples=600 path=D:\Master thesis\RAG Database\cnc_examples.jsonl embedding_device=cpu

2026-08-26 17:01:44,400 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:44,428 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:01:44,598 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:44,627 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:01:44,630 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-08-26 17:01:44,778 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:44,822 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:01:44,976 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:45,005 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-08-26 17:01:45,160 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:45,189 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:01:45,348 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:45,378 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-26 17:01:45,536 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:01:45,693 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:45,723 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 7327.87it/s]
2026-08-26 17:01:45,957 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:01:46,113 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:01:46,281 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:01:46,432 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:01:46,590 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:46,627 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:01:46,790 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:46,821 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:01:46,980 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:47,010 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:01:47,169 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:47,199 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:01:47,397 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-26 17:01:47,609 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-26 17:01:47,813 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:01:47,845 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-26 17:01:48,008 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-08-26 17:01:49,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:50,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:51,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:53,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:54,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:57,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:01:58,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:01,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:01,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:04,514 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:05,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:06,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:09,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:12,076 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:14,522 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:15,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:16,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:18,660 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:23,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:24,223 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:24,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:02:25,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:27,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:28,761 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:29,613 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:30,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:33,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:33,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:37,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:37,934 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:40,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:41,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:42,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:43,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:46,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:46,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:52,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:54,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:02:55,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:00,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:03,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:06,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:09,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:12,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:13,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:14,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:14,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:15,640 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:18,794 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:21,129 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:21,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:24,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:25,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:26,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:27,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:30,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:33,364 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:36,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:39,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:42,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:44,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:47,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:50,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:50,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:51,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:53,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:56,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:03:57,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:00,456 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:01,201 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:01,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:04,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:06,640 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:09,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:11,869 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:12,745 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:13,500 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:14,348 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:15,256 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:20,397 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:23,037 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:23,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:24,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:27,599 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:28,444 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:31,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:33,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:34,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:35,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:35,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:36,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:39,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:42,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:44,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:47,329 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:04:48,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:51,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:54,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:57,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:59,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:04:59,746 | INFO |
2026-08-26 17:04:59,747 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 100/1038 ================
样本总数: 100
  Gold 含因果: 57 | Pred 含因果: 52
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.790
  Precision: 0.846
  Recall   : 0.772
  F1       : 0.807
  (TP=44, TN=35, FP=8, FN=13)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 100
    Gold triples: 81 | Pred triples: 56
    Precision: 0.518
    Recall   : 0.358
    F1       : 0.423
    (TP=29, FP=27, FN=52)
  [anchor_window] (primary)
    样本数: 100
    Gold triples: 81 | Pred triples: 56
    Precision: 0.500
    Recall   : 0.346
    F1       : 0.409
    (TP=28, FP=28, FN=53)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 44
    Gold triples: 65 | Pred triples: 47
    Precision: 0.617
    Recall   : 0.446
    F1       : 0.518
    (TP=29, FP=18, FN=36)
  [anchor_window] (primary)
    样本数: 44
    Gold triples: 65 | Pred triples: 47
    Precision: 0.596
    Recall   : 0.431
    F1       : 0.500
    (TP=28, FP=19, FN=37)
================================================
2026-08-26 17:05:00,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:01,243 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:01,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:04,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:05,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:06,036 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:06,788 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:07,542 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:08,422 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:09,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:11,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:14,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:17,352 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:20,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:22,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:23,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:25,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:26,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:28,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:31,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:32,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:34,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:37,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:40,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:41,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:42,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:44,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:47,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:50,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:53,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:56,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:56,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:05:57,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:00,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:01,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:01,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:02,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:03,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:06,493 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:07,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:07,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:11,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:12,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:14,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:17,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:18,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:19,293 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:20,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:20,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:23,728 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:26,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:27,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:28,124 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:30,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:33,124 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:33,851 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:36,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:06:37,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:37,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:39,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:42,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:45,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:45,076 | WARNING | 生成失败：sample_id=691 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:06:47,295 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:47,297 | WARNING | 生成失败：sample_id=691 attempt=2/2 error=未找到 JSON 对象
2026-08-26 17:06:47,297 | ERROR | 生成兜底：sample_id=691 error=未找到 JSON 对象
2026-08-26 17:06:48,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:48,956 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:51,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:52,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:55,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:56,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:56,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:06:59,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:02,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:03,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:05,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:08,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:10,950 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:13,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:14,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:17,554 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:18,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:20,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:22,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:25,567 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:26,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:27,168 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:29,382 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:30,289 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:32,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:34,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:36,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:37,618 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:40,202 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:43,286 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:45,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:47,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:50,470 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:51,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:52,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:52,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:53,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:56,337 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:07:56,338 | INFO |
2026-08-26 17:07:56,339 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 200/1038 ================
样本总数: 200
  Gold 含因果: 107 | Pred 含因果: 103
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.780
  Precision: 0.806
  Recall   : 0.776
  F1       : 0.790
  (TP=83, TN=73, FP=20, FN=24)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 200
    Gold triples: 147 | Pred triples: 107
    Precision: 0.523
    Recall   : 0.381
    F1       : 0.441
    (TP=56, FP=51, FN=91)
  [anchor_window] (primary)
    样本数: 200
    Gold triples: 147 | Pred triples: 107
    Precision: 0.505
    Recall   : 0.367
    F1       : 0.425
    (TP=54, FP=53, FN=93)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 83
    Gold triples: 119 | Pred triples: 86
    Precision: 0.651
    Recall   : 0.471
    F1       : 0.546
    (TP=56, FP=30, FN=63)
  [anchor_window] (primary)
    样本数: 83
    Gold triples: 119 | Pred triples: 86
    Precision: 0.628
    Recall   : 0.454
    F1       : 0.527
    (TP=54, FP=32, FN=65)
================================================
2026-08-26 17:08:01,438 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:05,061 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:05,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:09,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:11,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:12,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:15,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:15,879 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:16,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:17,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:19,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:22,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:23,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:24,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:25,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:27,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:08:30,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:33,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:34,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:35,061 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:35,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:38,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:39,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:40,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:40,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:43,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:46,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:47,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:47,896 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:48,614 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:50,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:53,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:54,093 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:56,765 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:57,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:08:58,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:00,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:03,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:04,741 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:05,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:06,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:09,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:12,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:14,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:16,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:17,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:20,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:23,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:26,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:27,587 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:30,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:31,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:32,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:32,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:35,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:36,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:39,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:41,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:42,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:44,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:47,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:48,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:51,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:54,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:57,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:09:59,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:02,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:04,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:07,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:07,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:10,292 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:12,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:13,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:16,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:17,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:19,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:20,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:22,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:23,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:24,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:27,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:30,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:30,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:36,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:37,047 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:39,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:40,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:42,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:45,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:48,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:10:49,121 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:51,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:54,217 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:56,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:57,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:10:59,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:00,780 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:01,488 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:02,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:03,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:03,218 | INFO |
2026-08-26 17:11:03,218 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 300/1038 ================
样本总数: 300
  Gold 含因果: 155 | Pred 含因果: 158
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.777
  Precision: 0.778
  Recall   : 0.794
  F1       : 0.786
  (TP=123, TN=110, FP=35, FN=32)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 300
    Gold triples: 214 | Pred triples: 164
    Precision: 0.524
    Recall   : 0.402
    F1       : 0.455
    (TP=86, FP=78, FN=128)
  [anchor_window] (primary)
    样本数: 300
    Gold triples: 214 | Pred triples: 164
    Precision: 0.500
    Recall   : 0.383
    F1       : 0.434
    (TP=82, FP=82, FN=132)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 123
    Gold triples: 178 | Pred triples: 128
    Precision: 0.672
    Recall   : 0.483
    F1       : 0.562
    (TP=86, FP=42, FN=92)
  [anchor_window] (primary)
    样本数: 123
    Gold triples: 178 | Pred triples: 128
    Precision: 0.641
    Recall   : 0.461
    F1       : 0.536
    (TP=82, FP=46, FN=96)
================================================
2026-08-26 17:11:06,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:08,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:09,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:12,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:12,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:13,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:16,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:16,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:17,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:21,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:24,299 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:27,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:27,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:28,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:31,086 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:31,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:34,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:37,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:37,995 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:38,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:39,422 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:40,296 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:40,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:41,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:45,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:48,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:49,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:50,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:53,115 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:58,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:11:59,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:01,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:05,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:07,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:08,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:11,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:11,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:12,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:15,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:15,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:16,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:19,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:20,218 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:22,488 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:24,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:27,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:28,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:28,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:29,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:30,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:31,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:34,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:12:36,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:37,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:39,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:44,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:46,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:53,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:55,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:12:57,831 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:01,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:03,829 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:04,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:05,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:06,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:06,873 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:09,455 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:10,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:12,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:13,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:16,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:19,798 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:23,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:24,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:27,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:27,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:31,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:34,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:35,831 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:36,680 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:37,526 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:38,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:38,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:39,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:40,455 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:41,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:45,589 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:46,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:48,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:49,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:52,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:54,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:13:58,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:03,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:04,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:05,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:07,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:08,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:08,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:09,581 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:09,582 | INFO |
2026-08-26 17:14:09,583 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 400/1038 ================
样本总数: 400
  Gold 含因果: 202 | Pred 含因果: 206
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.805
  Precision: 0.801
  Recall   : 0.817
  F1       : 0.809
  (TP=165, TN=157, FP=41, FN=37)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 400
    Gold triples: 279 | Pred triples: 217
    Precision: 0.498
    Recall   : 0.387
    F1       : 0.435
    (TP=108, FP=109, FN=171)
  [anchor_window] (primary)
    样本数: 400
    Gold triples: 279 | Pred triples: 217
    Precision: 0.493
    Recall   : 0.384
    F1       : 0.431
    (TP=107, FP=110, FN=172)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 165
    Gold triples: 235 | Pred triples: 175
    Precision: 0.617
    Recall   : 0.460
    F1       : 0.527
    (TP=108, FP=67, FN=127)
  [anchor_window] (primary)
    样本数: 165
    Gold triples: 235 | Pred triples: 175
    Precision: 0.611
    Recall   : 0.455
    F1       : 0.522
    (TP=107, FP=68, FN=128)
================================================
2026-08-26 17:14:12,696 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:14,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:15,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:18,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:18,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:19,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:21,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:22,812 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:26,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:29,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:31,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:32,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:33,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:34,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:14:35,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:35,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:38,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:41,741 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:42,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:44,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:48,128 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:52,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:52,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:53,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:56,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:57,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:58,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:14:59,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:01,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:05,083 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:07,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:08,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:10,847 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:11,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:15,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:15,740 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:18,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:21,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:21,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:24,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:28,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:31,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:32,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:34,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:37,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:40,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:43,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:44,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:45,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:45,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:46,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:47,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:50,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:53,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:54,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:54,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:15:57,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:00,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:03,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:05,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:08,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:11,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:14,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:17,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:20,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:22,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:25,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:26,072 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:29,303 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:31,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:34,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:35,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:35,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:38,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:41,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:44,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:44,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:45,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:49,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:50,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:51,773 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:54,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:56,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:57,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:16:58,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:00,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:01,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:04,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:17:04,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:05,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:08,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:12,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:13,728 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:14,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:17,218 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:20,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:23,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:26,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:29,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:31,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:31,735 | INFO |
2026-08-26 17:17:31,735 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 500/1038 ================
样本总数: 500
  Gold 含因果: 266 | Pred 含因果: 266
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.796
  Precision: 0.808
  Recall   : 0.808
  F1       : 0.808
  (TP=215, TN=183, FP=51, FN=51)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 500
    Gold triples: 369 | Pred triples: 281
    Precision: 0.509
    Recall   : 0.388
    F1       : 0.440
    (TP=143, FP=138, FN=226)
  [anchor_window] (primary)
    样本数: 500
    Gold triples: 369 | Pred triples: 281
    Precision: 0.537
    Recall   : 0.409
    F1       : 0.465
    (TP=151, FP=130, FN=218)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 215
    Gold triples: 309 | Pred triples: 229
    Precision: 0.624
    Recall   : 0.463
    F1       : 0.532
    (TP=143, FP=86, FN=166)
  [anchor_window] (primary)
    样本数: 215
    Gold triples: 309 | Pred triples: 229
    Precision: 0.659
    Recall   : 0.489
    F1       : 0.561
    (TP=151, FP=78, FN=158)
================================================
2026-08-26 17:17:34,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:35,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:36,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:38,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:39,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:43,026 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:45,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:46,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:47,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:51,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:52,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:53,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:55,773 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:56,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:17:58,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:01,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:02,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:06,995 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:09,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:10,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:12,839 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:13,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:16,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:17,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:17,693 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:20,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:25,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:28,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:29,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:30,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:30,848 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:35,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:36,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:39,063 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:42,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:42,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:43,605 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:46,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:49,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:50,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:52,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:54,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:57,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:58,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:59,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:18:59,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:02,549 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:03,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:03,961 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:06,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:19:09,578 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:12,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:15,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:17,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:22,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:23,571 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:26,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:27,292 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:28,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:30,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:33,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:33,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:36,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:37,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:38,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:38,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:39,650 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:40,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:43,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:44,241 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:45,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:45,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:48,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:49,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:49,729 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:50,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:53,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:55,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:58,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:19:59,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:01,776 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:02,513 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:03,251 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:06,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:08,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:11,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:14,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:16,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:17,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:20,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:22,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:23,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:24,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:27,536 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:28,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:30,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:31,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:32,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:35,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:35,699 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:35,701 | INFO |
2026-08-26 17:20:35,701 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 600/1038 ================
样本总数: 600
  Gold 含因果: 317 | Pred 含因果: 316
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.798
  Precision: 0.810
  Recall   : 0.808
  F1       : 0.809
  (TP=256, TN=223, FP=60, FN=61)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 600
    Gold triples: 443 | Pred triples: 337
    Precision: 0.522
    Recall   : 0.397
    F1       : 0.451
    (TP=176, FP=161, FN=267)
  [anchor_window] (primary)
    样本数: 600
    Gold triples: 443 | Pred triples: 337
    Precision: 0.543
    Recall   : 0.413
    F1       : 0.469
    (TP=183, FP=154, FN=260)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 256
    Gold triples: 371 | Pred triples: 276
    Precision: 0.638
    Recall   : 0.474
    F1       : 0.544
    (TP=176, FP=100, FN=195)
  [anchor_window] (primary)
    样本数: 256
    Gold triples: 371 | Pred triples: 276
    Precision: 0.663
    Recall   : 0.493
    F1       : 0.566
    (TP=183, FP=93, FN=188)
================================================
2026-08-26 17:20:36,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:39,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:42,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:44,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:45,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:46,391 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:47,130 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:49,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:50,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:51,086 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:51,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:52,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:20:55,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:56,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:20:59,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:01,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:03,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:04,501 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:05,348 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:06,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:08,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:11,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:17,551 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:20,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:22,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:26,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:29,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:32,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:32,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:35,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:36,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:37,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:40,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:43,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:44,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:45,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:47,515 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:50,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:51,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:53,911 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:54,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:55,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:57,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:21:58,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:01,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:01,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:02,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:04,886 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:07,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:08,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:11,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:11,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:14,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:14,738 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:15,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:19,167 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:23,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:23,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:26,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:27,678 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:28,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:29,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:31,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:34,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:37,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:38,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:39,240 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:42,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:43,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:45,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:46,385 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:47,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:53,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:55,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:22:58,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:23:01,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:23:52,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:23:52,049 | WARNING | 生成失败：sample_id=882 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:24:42,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:24:42,326 | WARNING | 生成失败：sample_id=882 attempt=2/2 error=未找到 JSON 对象
2026-08-26 17:24:42,326 | ERROR | 生成兜底：sample_id=882 error=未找到 JSON 对象
2026-08-26 17:24:48,444 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:24:48,445 | WARNING | 生成失败：sample_id=1533 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:24:51,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:24:54,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:24:54,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:24:57,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:24:58,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:02,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:02,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:03,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:04,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:07,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:07,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:08,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:11,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:11,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:15,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:15,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:18,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:21,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:24,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:26,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:27,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:29,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:32,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:32,196 | INFO |
2026-08-26 17:25:32,197 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 700/1038 ================
样本总数: 700
  Gold 含因果: 373 | Pred 含因果: 369
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.797
  Precision: 0.813
  Recall   : 0.804
  F1       : 0.809
  (TP=300, TN=258, FP=69, FN=73)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 700
    Gold triples: 521 | Pred triples: 395
    Precision: 0.547
    Recall   : 0.415
    F1       : 0.472
    (TP=216, FP=179, FN=305)
  [anchor_window] (primary)
    样本数: 700
    Gold triples: 521 | Pred triples: 395
    Precision: 0.562
    Recall   : 0.426
    F1       : 0.485
    (TP=222, FP=173, FN=299)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 300
    Gold triples: 436 | Pred triples: 325
    Precision: 0.665
    Recall   : 0.495
    F1       : 0.568
    (TP=216, FP=109, FN=220)
  [anchor_window] (primary)
    样本数: 300
    Gold triples: 436 | Pred triples: 325
    Precision: 0.683
    Recall   : 0.509
    F1       : 0.583
    (TP=222, FP=103, FN=214)
================================================
2026-08-26 17:25:32,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:35,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:37,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:38,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:41,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:44,243 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:46,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:49,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:50,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:54,255 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:56,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:57,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:58,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:59,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:25:59,825 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:03,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:05,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:06,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:07,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:10,956 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:11,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:12,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:13,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:15,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:18,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:19,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:23,271 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:26,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:29,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:30,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:31,277 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:32,172 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:32,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:36,119 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:36,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:37,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:38,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:39,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:41,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:44,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:48,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:53,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:53,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:26:56,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:57,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:26:59,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:00,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:01,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:03,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:04,469 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:05,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:05,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:09,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:10,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:10,879 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:11,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:16,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:17,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:20,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:20,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:21,554 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:22,254 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:23,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:25,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:27,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:28,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:31,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:32,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:35,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:37,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:38,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:39,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:39,946 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:40,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:41,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:42,073 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:42,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:43,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:46,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:46,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:47,660 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:48,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:49,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:52,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:55,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:27:59,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:00,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:01,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:04,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:06,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:07,381 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:08,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:11,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:12,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:12,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:15,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:16,128 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:19,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:19,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:20,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:20,546 | INFO |
2026-08-26 17:28:20,546 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 800/1038 ================
样本总数: 800
  Gold 含因果: 423 | Pred 含因果: 410
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.796
  Precision: 0.817
  Recall   : 0.792
  F1       : 0.804
  (TP=335, TN=302, FP=75, FN=88)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 800
    Gold triples: 591 | Pred triples: 440
    Precision: 0.552
    Recall   : 0.411
    F1       : 0.471
    (TP=243, FP=197, FN=348)
  [anchor_window] (primary)
    样本数: 800
    Gold triples: 591 | Pred triples: 440
    Precision: 0.566
    Recall   : 0.421
    F1       : 0.483
    (TP=249, FP=191, FN=342)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 335
    Gold triples: 488 | Pred triples: 364
    Precision: 0.668
    Recall   : 0.498
    F1       : 0.570
    (TP=243, FP=121, FN=245)
  [anchor_window] (primary)
    样本数: 335
    Gold triples: 488 | Pred triples: 364
    Precision: 0.684
    Recall   : 0.510
    F1       : 0.585
    (TP=249, FP=115, FN=239)
================================================
2026-08-26 17:28:23,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:24,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:28,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:30,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:33,186 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:28:34,033 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:36,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:36,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:41,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:42,254 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:46,064 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:46,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:51,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:53,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:54,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:55,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:57,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:58,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:28:59,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:02,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:05,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:07,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:10,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:11,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:14,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:14,822 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:17,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:20,275 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:23,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:24,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:24,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:26,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:29,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:32,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:32,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:35,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:35,851 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:38,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:39,240 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:40,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:43,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:44,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:45,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:45,951 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:48,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:50,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:53,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:56,449 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:59,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:29:59,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:30:50,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:30:50,633 | WARNING | 生成失败：sample_id=679 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:31:01,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:05,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:05,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:06,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:07,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:10,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:11,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:11,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:14,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:15,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:16,286 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:18,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:19,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:20,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:21,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:25,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:27,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:28,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:29,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:29,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:30,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:31,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:34,961 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:39,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:42,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:44,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:45,657 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:31:48,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:51,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:51,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:54,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:57,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:31:59,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:00,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:05,031 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:08,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:09,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:12,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:16,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:19,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:20,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:20,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:21,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:22,477 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:23,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:24,206 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:26,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:30,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:33,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:34,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:34,068 | INFO |
2026-08-26 17:32:34,068 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 900/1038 ================
样本总数: 900
  Gold 含因果: 480 | Pred 含因果: 463
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.790
  Precision: 0.814
  Recall   : 0.785
  F1       : 0.800
  (TP=377, TN=334, FP=86, FN=103)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 900
    Gold triples: 669 | Pred triples: 501
    Precision: 0.553
    Recall   : 0.414
    F1       : 0.474
    (TP=277, FP=224, FN=392)
  [anchor_window] (primary)
    样本数: 900
    Gold triples: 669 | Pred triples: 501
    Precision: 0.571
    Recall   : 0.428
    F1       : 0.489
    (TP=286, FP=215, FN=383)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 377
    Gold triples: 550 | Pred triples: 413
    Precision: 0.671
    Recall   : 0.504
    F1       : 0.575
    (TP=277, FP=136, FN=273)
  [anchor_window] (primary)
    样本数: 377
    Gold triples: 550 | Pred triples: 413
    Precision: 0.692
    Recall   : 0.520
    F1       : 0.594
    (TP=286, FP=127, FN=264)
================================================
2026-08-26 17:32:36,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:39,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:40,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:43,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:43,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:46,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:47,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:50,152 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:52,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:54,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:57,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:32:59,444 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:00,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:00,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:03,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:07,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:09,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:10,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:11,258 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:12,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:14,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:15,152 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:19,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:20,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:24,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:25,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:28,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:31,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:31,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:34,765 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:35,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:38,435 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:39,129 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:39,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:42,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:43,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:45,590 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:48,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:48,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:33:51,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:54,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:55,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:55,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:33:58,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:00,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:04,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:04,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:07,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:08,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:08,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:09,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:12,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:15,254 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:16,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:16,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:17,455 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:22,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:22,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:23,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:25,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:26,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:27,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:28,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:30,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:33,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:37,383 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:38,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:40,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:41,473 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:42,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:44,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:45,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:48,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:50,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:53,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:54,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:57,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:58,067 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:34:58,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:01,463 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:04,155 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:06,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:09,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:10,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:12,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:16,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:17,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:19,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:20,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:21,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:23,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:25,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:26,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:27,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:27,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:30,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:30,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:31,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:32,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:34,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:34,333 | INFO |
2026-08-26 17:35:34,333 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test progress 1000/1038 ================
样本总数: 1000
  Gold 含因果: 529 | Pred 含因果: 515
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.788
  Precision: 0.808
  Recall   : 0.786
  F1       : 0.797
  (TP=416, TN=372, FP=99, FN=113)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1000
    Gold triples: 739 | Pred triples: 556
    Precision: 0.550
    Recall   : 0.414
    F1       : 0.473
    (TP=306, FP=250, FN=433)
  [anchor_window] (primary)
    样本数: 1000
    Gold triples: 739 | Pred triples: 556
    Precision: 0.576
    Recall   : 0.433
    F1       : 0.494
    (TP=320, FP=236, FN=419)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 416
    Gold triples: 608 | Pred triples: 455
    Precision: 0.673
    Recall   : 0.503
    F1       : 0.576
    (TP=306, FP=149, FN=302)
  [anchor_window] (primary)
    样本数: 416
    Gold triples: 608 | Pred triples: 455
    Precision: 0.703
    Recall   : 0.526
    F1       : 0.602
    (TP=320, FP=135, FN=288)
================================================
2026-08-26 17:35:35,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:35:37,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:40,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:44,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:46,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:49,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:50,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:51,251 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:51,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:52,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:55,599 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:58,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:35:59,093 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:01,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:04,905 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:05,798 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:06,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:07,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:11,624 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:15,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:16,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:18,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:21,128 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:23,961 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:27,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:28,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:29,263 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:29,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:30,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:31,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:32,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:35,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:37,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:38,632 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:39,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:41,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:44,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:47,513 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:36:47,516 | INFO |
2026-08-26 17:36:47,517 | INFO | ================ Qwen3.6 27B No Thinking CNC fixed test final report ================
样本总数: 1038
  Gold 含因果: 548 | Pred 含因果: 535
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.793
  Precision: 0.811
  Recall   : 0.792
  F1       : 0.801
  (TP=434, TN=389, FP=101, FN=114)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1038
    Gold triples: 763 | Pred triples: 577
    Precision: 0.553
    Recall   : 0.418
    F1       : 0.476
    (TP=319, FP=258, FN=444)
  [anchor_window] (primary)
    样本数: 1038
    Gold triples: 763 | Pred triples: 577
    Precision: 0.579
    Recall   : 0.438
    F1       : 0.499
    (TP=334, FP=243, FN=429)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 434
    Gold triples: 631 | Pred triples: 474
    Precision: 0.673
    Recall   : 0.506
    F1       : 0.577
    (TP=319, FP=155, FN=312)
  [anchor_window] (primary)
    样本数: 434
    Gold triples: 631 | Pred triples: 474
    Precision: 0.705
    Recall   : 0.529
    F1       : 0.605
    (TP=334, FP=140, FN=297)
================================================
2026-08-26 17:36:47,518 | INFO | ================ 前 10 条样本判定 ================

--- id=1120 ---
text: They were attacking a student leader and a fighter .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2291 ---
text: Protesters have also surrounded the police headquarters twice in past weeks in noisy and emotionally charged protests in which young people spray-painted obscenities on its front wall and barricaded its entrances .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2733 ---
text: Authorities also rejected a request to hold one on Sunday in Sheung Wan , near where police fired teargas and rubber bullets on demonstrators who had defaced China ’ s representative office in Hong Kong last week .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2124 ---
text: On Tuesday we went to picket at the Western Cape Provincial Legislature after we had gone over a month without teachers .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 1}
gold_relations:
[
  {
    "cause": "we had gone over a month without teachers",
    "effect": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "we had gone over a month without teachers"
    },
    "relation": "caused",
    "effect": {
      "span": "we went to picket at the Western Cape Provincial Legislature"
    }
  }
]

--- id=450 ---
text: Protestors in Clashes With Police on Jammu-Pathankot NH During Eviction Drive 22nd February 2016 05:22 PM JAMMU : Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday , police said .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=777 ---
text: ANDHRA PRADESH ` Delay ' in compensation : ryots lay siege to MRO office March 14 , 2006 00:00 IST Staff Reporter Telugu Desam , CPI(M) leaders lead the protest VIJAYAWADA : Betel nut farmers from Garikaparru and Thotlavalluru villages under Thotlavalluru mandal laid siege to the Mandal Revenue Office on Monday .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "` Delay ' in compensation"
    },
    "relation": "caused",
    "effect": {
      "span": "Betel nut farmers from Garikaparru and Thotlavalluru villages under Thotlavalluru mandal laid siege to the Mandal Revenue Office on Monday"
    }
  }
]

--- id=769 ---
text: The march was organised by the Federation of South African Women ( Fedsaw ) and led by Helen Joseph , Rahima Moosa , Sophie Williams and Lilian Ngoyi .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=542 ---
text: We totally support the ongoing strike since VAT imposed by the government is unjust but the business has to run if we are to recover losses , ” said a shop owner near Charminar .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "VAT imposed by the government is unjust",
    "effect": "We totally support the ongoing strike"
  },
  {
    "cause": "if we are to recover losses",
    "effect": "the business has to run"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "VAT imposed by the government is unjust"
    },
    "relation": "caused",
    "effect": {
      "span": "We totally support the ongoing strike"
    }
  }
]

--- id=1420 ---
text: The protest went on for more than two hours and shops on the highway were shut during that time .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1368 ---
text: According to one villager , officials have frozen that money to prevent villagers funding a journey to Beijing to continue their petitioning .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "to prevent villagers funding a journey to Beijing to continue their petitioning",
    "effect": "officials have frozen that money"
  },
  {
    "cause": "to continue their petitioning",
    "effect": "villagers funding a journey to Beijing"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "to prevent villagers funding a journey to Beijing to continue their petitioning"
    },
    "relation": "caused",
    "effect": {
      "span": "officials have frozen that money"
    }
  }
]

2026-08-26 17:36:47,533 | INFO | Eval report saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\local-qwen3.6-27b-no-thinking_cnc_sft_test-n1038_prompt-v9.6_rag-knn_pattern-k1_20260826-173647.md
2026-08-26 17:36:47,534 | INFO | Generation failure outputs saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\local-qwen3.6-27b-no-thinking_cnc_sft_test-n1038_prompt-v9.6_rag-knn_pattern-k1_20260826-173647_generation_failures.jsonl
2026-08-26 17:36:47,553 | INFO | [eval 3/4] 开始 google/gemma-4-26b-a4b-qat
2026-08-26 17:37:00,766 | INFO | Pattern examples 已加载：path=D:\Master thesis\RAG Database\cnc_examples.jsonl examples=600
2026-08-26 17:37:00,776 | INFO | KNN cache 已加载：examples=600 path=D:\Master thesis\RAG Database\cnc_examples.jsonl embedding_device=cpu

2026-08-26 17:37:01,046 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:01,073 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:37:01,234 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:01,263 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:37:01,267 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-08-26 17:37:01,418 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:01,446 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:37:01,599 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:01,629 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-08-26 17:37:01,787 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:01,818 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:37:01,975 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:02,004 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-26 17:37:02,164 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:37:02,342 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:02,371 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 6846.92it/s]
2026-08-26 17:37:02,603 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:37:02,760 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:37:02,919 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:37:03,073 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:37:03,232 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:03,264 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:37:03,418 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:03,449 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:37:03,603 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:03,632 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:37:03,787 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:03,816 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:37:03,977 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-26 17:37:04,143 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-26 17:37:04,334 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:37:04,363 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-26 17:37:04,546 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-08-26 17:37:05,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:06,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:07,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:08,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:09,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:10,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:10,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:11,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:11,950 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:12,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:13,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:14,344 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:15,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:16,626 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:17,258 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:17,647 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:18,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:18,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:20,192 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:21,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:21,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:37:21,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:22,391 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:23,397 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:24,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:24,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:25,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:25,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:26,581 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:27,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:28,036 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:28,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:28,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:29,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:30,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:30,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:31,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:32,397 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:32,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:33,741 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:34,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:35,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:35,987 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:36,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:37,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:37,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:38,587 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:38,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:39,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:40,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:40,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:41,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:42,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:42,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:42,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:43,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:44,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:45,533 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:46,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:47,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:47,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:48,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:49,436 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:50,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:50,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:51,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:52,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:52,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:53,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:54,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:54,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:55,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:55,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:56,608 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:57,464 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:57,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:58,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:58,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:37:59,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:00,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:01,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:01,488 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:01,879 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:02,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:03,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:04,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:04,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:05,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:05,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:06,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:06,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:07,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:08,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:09,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:09,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:38:10,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:11,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:12,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:12,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:13,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:13,789 | INFO |
2026-08-26 17:38:13,790 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 100/1038 ================
样本总数: 100
  Gold 含因果: 57 | Pred 含因果: 66
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.790
  Precision: 0.773
  Recall   : 0.895
  F1       : 0.829
  (TP=51, TN=28, FP=15, FN=6)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 100
    Gold triples: 81 | Pred triples: 80
    Precision: 0.512
    Recall   : 0.506
    F1       : 0.509
    (TP=41, FP=39, FN=40)
  [anchor_window] (primary)
    样本数: 100
    Gold triples: 81 | Pred triples: 80
    Precision: 0.500
    Recall   : 0.494
    F1       : 0.497
    (TP=40, FP=40, FN=41)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 51
    Gold triples: 73 | Pred triples: 62
    Precision: 0.661
    Recall   : 0.562
    F1       : 0.607
    (TP=41, FP=21, FN=32)
  [anchor_window] (primary)
    样本数: 51
    Gold triples: 73 | Pred triples: 62
    Precision: 0.645
    Recall   : 0.548
    F1       : 0.593
    (TP=40, FP=22, FN=33)
================================================
2026-08-26 17:38:14,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:14,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:15,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:16,129 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:16,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:17,129 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:17,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:18,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:19,142 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:19,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:20,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:21,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:22,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:22,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:23,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:23,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:24,217 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:24,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:25,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:25,969 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:27,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:28,214 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:28,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:29,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:30,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:31,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:31,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:32,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:33,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:34,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:36,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:36,513 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:36,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:37,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:37,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:38,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:38,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:39,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:39,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:40,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:41,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:42,281 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:42,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:43,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:44,381 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:45,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:45,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:45,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:46,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:47,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:48,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:49,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:50,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:50,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:51,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:52,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:53,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:38:54,086 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:54,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:55,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:55,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:56,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:57,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:58,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:59,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:38:59,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:00,085 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:00,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:00,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:01,607 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:02,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:02,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:03,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:03,879 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:04,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:05,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:05,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:06,464 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:06,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:07,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:08,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:08,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:09,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:09,542 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:10,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:11,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:11,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:12,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:13,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:14,113 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:14,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:15,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:16,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:17,036 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:17,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:18,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:18,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:18,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:19,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:20,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:20,360 | INFO |
2026-08-26 17:39:20,361 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 200/1038 ================
样本总数: 200
  Gold 含因果: 107 | Pred 含因果: 134
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.775
  Precision: 0.731
  Recall   : 0.916
  F1       : 0.813
  (TP=98, TN=57, FP=36, FN=9)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 200
    Gold triples: 147 | Pred triples: 159
    Precision: 0.491
    Recall   : 0.531
    F1       : 0.510
    (TP=78, FP=81, FN=69)
  [anchor_window] (primary)
    样本数: 200
    Gold triples: 147 | Pred triples: 159
    Precision: 0.484
    Recall   : 0.524
    F1       : 0.503
    (TP=77, FP=82, FN=70)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 98
    Gold triples: 136 | Pred triples: 119
    Precision: 0.655
    Recall   : 0.574
    F1       : 0.612
    (TP=78, FP=41, FN=58)
  [anchor_window] (primary)
    样本数: 98
    Gold triples: 136 | Pred triples: 119
    Precision: 0.647
    Recall   : 0.566
    F1       : 0.604
    (TP=77, FP=42, FN=59)
================================================
2026-08-26 17:39:21,632 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:22,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:22,773 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:23,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:24,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:25,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:25,743 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:26,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:26,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:27,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:27,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:28,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:29,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:29,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:30,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:31,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:32,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:33,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:33,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:39:34,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:34,822 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:35,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:35,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:36,303 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:36,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:37,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:38,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:38,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:39,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:40,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:40,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:41,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:41,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:42,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:42,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:43,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:43,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:44,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:45,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:45,583 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:45,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:46,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:47,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:48,299 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:48,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:49,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:50,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:51,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:52,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:52,583 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:53,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:53,829 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:54,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:54,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:55,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:55,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:56,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:57,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:57,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:58,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:58,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:59,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:39:59,956 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:00,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:01,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:02,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:02,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:03,898 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:04,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:04,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:05,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:06,135 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:06,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:07,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:07,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:08,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:08,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:09,568 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:10,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:10,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:11,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:12,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:13,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:15,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:16,583 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:17,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:17,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:18,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:19,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:20,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:20,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:21,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:22,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:40:22,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:23,125 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:23,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:24,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:24,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:25,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:25,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:25,463 | INFO |
2026-08-26 17:40:25,464 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 300/1038 ================
样本总数: 300
  Gold 含因果: 155 | Pred 含因果: 199
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.767
  Precision: 0.714
  Recall   : 0.916
  F1       : 0.802
  (TP=142, TN=88, FP=57, FN=13)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 300
    Gold triples: 214 | Pred triples: 233
    Precision: 0.485
    Recall   : 0.528
    F1       : 0.506
    (TP=113, FP=120, FN=101)
  [anchor_window] (primary)
    样本数: 300
    Gold triples: 214 | Pred triples: 233
    Precision: 0.481
    Recall   : 0.523
    F1       : 0.501
    (TP=112, FP=121, FN=102)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 142
    Gold triples: 199 | Pred triples: 169
    Precision: 0.669
    Recall   : 0.568
    F1       : 0.614
    (TP=113, FP=56, FN=86)
  [anchor_window] (primary)
    样本数: 142
    Gold triples: 199 | Pred triples: 169
    Precision: 0.663
    Recall   : 0.563
    F1       : 0.609
    (TP=112, FP=57, FN=87)
================================================
2026-08-26 17:40:26,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:27,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:27,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:28,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:28,907 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:29,280 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:29,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:30,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:30,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:31,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:32,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:33,435 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:33,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:34,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:35,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:35,665 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:36,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:37,436 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:37,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:38,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:38,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:38,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:39,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:39,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:40,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:41,799 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:42,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:42,599 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:43,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:44,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:44,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:45,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:46,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:47,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:47,489 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:48,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:48,533 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:48,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:49,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:50,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:50,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:51,552 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:52,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:52,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:53,657 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:54,303 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:55,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:55,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:56,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:57,469 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:57,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:58,930 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:59,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:40:59,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:00,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:41:01,779 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:02,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:03,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:04,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:04,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:05,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:06,555 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:06,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:07,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:07,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:08,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:08,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:09,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:09,930 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:10,662 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:11,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:12,469 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:13,524 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:13,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:14,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:15,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:16,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:17,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:17,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:17,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:18,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:18,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:19,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:19,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:20,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:20,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:21,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:22,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:22,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:23,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:23,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:24,613 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:25,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:26,571 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:27,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:27,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:27,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:28,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:28,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:29,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:29,562 | INFO |
2026-08-26 17:41:29,563 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 400/1038 ================
样本总数: 400
  Gold 含因果: 202 | Pred 含因果: 260
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.790
  Precision: 0.727
  Recall   : 0.936
  F1       : 0.818
  (TP=189, TN=127, FP=71, FN=13)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 400
    Gold triples: 279 | Pred triples: 301
    Precision: 0.482
    Recall   : 0.520
    F1       : 0.500
    (TP=145, FP=156, FN=134)
  [anchor_window] (primary)
    样本数: 400
    Gold triples: 279 | Pred triples: 301
    Precision: 0.502
    Recall   : 0.541
    F1       : 0.521
    (TP=151, FP=150, FN=128)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 189
    Gold triples: 264 | Pred triples: 222
    Precision: 0.653
    Recall   : 0.549
    F1       : 0.597
    (TP=145, FP=77, FN=119)
  [anchor_window] (primary)
    样本数: 189
    Gold triples: 264 | Pred triples: 222
    Precision: 0.680
    Recall   : 0.572
    F1       : 0.621
    (TP=151, FP=71, FN=113)
================================================
2026-08-26 17:41:30,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:31,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:31,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:32,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:32,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:32,936 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:33,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:34,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:35,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:36,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:37,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:37,444 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:37,817 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:38,172 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:38,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:38,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:39,933 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:41:40,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:41,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:41,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:42,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:43,289 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:43,933 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:44,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:45,549 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:45,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:46,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:47,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:47,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:48,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:49,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:50,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:50,686 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:51,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:52,394 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:52,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:53,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:54,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:54,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:55,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:56,371 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:56,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:57,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:58,464 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:41:59,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:00,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:00,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:01,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:02,526 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:02,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:03,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:04,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:05,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:06,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:07,146 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:07,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:08,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:09,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:10,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:10,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:11,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:12,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:13,657 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:14,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:15,555 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:16,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:16,859 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:17,280 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:18,196 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:18,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:19,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:20,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:20,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:21,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:22,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:23,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:23,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:24,493 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:25,396 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:26,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:26,627 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:27,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:27,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:28,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:28,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:29,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:29,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:30,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:30,772 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:32,373 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:33,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:42:34,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:34,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:35,605 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:36,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:37,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:38,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:38,906 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:39,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:40,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:40,232 | INFO |
2026-08-26 17:42:40,232 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 500/1038 ================
样本总数: 500
  Gold 含因果: 266 | Pred 含因果: 337
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.786
  Precision: 0.736
  Recall   : 0.932
  F1       : 0.823
  (TP=248, TN=145, FP=89, FN=18)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 500
    Gold triples: 369 | Pred triples: 386
    Precision: 0.484
    Recall   : 0.507
    F1       : 0.495
    (TP=187, FP=199, FN=182)
  [anchor_window] (primary)
    样本数: 500
    Gold triples: 369 | Pred triples: 386
    Precision: 0.518
    Recall   : 0.542
    F1       : 0.530
    (TP=200, FP=186, FN=169)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 248
    Gold triples: 348 | Pred triples: 287
    Precision: 0.652
    Recall   : 0.537
    F1       : 0.589
    (TP=187, FP=100, FN=161)
  [anchor_window] (primary)
    样本数: 248
    Gold triples: 348 | Pred triples: 287
    Precision: 0.697
    Recall   : 0.575
    F1       : 0.630
    (TP=200, FP=87, FN=148)
================================================
2026-08-26 17:42:41,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:41,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:42,070 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:42,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:43,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:44,930 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:45,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:46,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:46,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:48,587 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:49,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:49,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:50,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:50,951 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:51,774 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:52,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:53,025 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:54,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:54,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:55,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:56,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:56,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:57,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:57,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:58,436 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:42:59,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:00,477 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:01,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:02,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:03,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:03,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:04,896 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:05,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:06,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:07,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:08,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:08,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:09,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:10,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:11,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:11,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:12,602 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:13,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:14,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:14,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:14,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:15,691 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:16,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:16,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:17,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:18,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:19,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:20,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:43:20,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:21,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:22,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:22,925 | WARNING | 生成失败：sample_id=701 attempt=1/2 error=Expecting ',' delimiter: line 1 column 359 (char 358)
2026-08-26 17:43:23,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:24,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:25,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:26,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:26,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:27,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:27,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:28,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:29,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:29,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:29,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:30,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:31,364 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:32,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:32,615 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:33,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:33,654 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:34,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:34,761 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:35,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:36,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:36,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:37,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:38,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:38,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:39,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:39,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:40,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:41,536 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:41,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:42,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:43,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:44,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:44,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:45,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:45,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:46,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:46,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:47,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:48,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:48,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:49,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:50,821 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:51,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:51,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:51,822 | INFO |
2026-08-26 17:43:51,823 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 600/1038 ================
样本总数: 600
  Gold 含因果: 317 | Pred 含因果: 407
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.780
  Precision: 0.727
  Recall   : 0.934
  F1       : 0.818
  (TP=296, TN=172, FP=111, FN=21)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 600
    Gold triples: 443 | Pred triples: 474
    Precision: 0.481
    Recall   : 0.515
    F1       : 0.497
    (TP=228, FP=246, FN=215)
  [anchor_window] (primary)
    样本数: 600
    Gold triples: 443 | Pred triples: 474
    Precision: 0.519
    Recall   : 0.555
    F1       : 0.537
    (TP=246, FP=228, FN=197)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 296
    Gold triples: 419 | Pred triples: 350
    Precision: 0.651
    Recall   : 0.544
    F1       : 0.593
    (TP=228, FP=122, FN=191)
  [anchor_window] (primary)
    样本数: 296
    Gold triples: 419 | Pred triples: 350
    Precision: 0.703
    Recall   : 0.587
    F1       : 0.640
    (TP=246, FP=104, FN=173)
================================================
2026-08-26 17:43:52,521 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:53,143 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:53,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:54,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:55,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:55,500 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:55,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:57,007 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:57,613 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:58,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:58,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:59,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:43:59,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:43:59,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:01,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:02,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:03,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:03,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:04,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:04,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:05,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:05,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:07,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:08,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:08,829 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:09,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:10,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:11,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:11,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:12,417 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:12,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:13,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:14,807 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:15,662 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:16,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:16,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:17,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:17,743 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:18,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:19,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:19,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:19,839 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:20,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:20,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:21,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:22,064 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:22,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:23,152 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:23,788 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:24,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:25,076 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:25,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:26,059 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:26,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:27,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:28,032 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:29,058 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:29,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:30,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:31,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:31,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:32,086 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:32,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:33,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:34,867 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:35,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:35,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:36,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:37,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:38,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:39,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:39,534 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:40,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:41,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:42,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:43,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:43,529 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:45,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:46,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:46,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:47,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:47,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:49,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:49,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:49,838 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:50,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:44:50,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:51,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:52,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:52,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:53,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:54,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:54,800 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:55,500 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:56,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:57,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:57,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:58,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:58,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:59,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:44:59,370 | INFO |
2026-08-26 17:44:59,371 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 700/1038 ================
样本总数: 700
  Gold 含因果: 373 | Pred 含因果: 472
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.781
  Precision: 0.733
  Recall   : 0.928
  F1       : 0.819
  (TP=346, TN=201, FP=126, FN=27)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 700
    Gold triples: 521 | Pred triples: 554
    Precision: 0.478
    Recall   : 0.509
    F1       : 0.493
    (TP=265, FP=289, FN=256)
  [anchor_window] (primary)
    样本数: 700
    Gold triples: 521 | Pred triples: 554
    Precision: 0.523
    Recall   : 0.557
    F1       : 0.540
    (TP=290, FP=264, FN=231)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 346
    Gold triples: 491 | Pred triples: 412
    Precision: 0.643
    Recall   : 0.540
    F1       : 0.587
    (TP=265, FP=147, FN=226)
  [anchor_window] (primary)
    样本数: 346
    Gold triples: 491 | Pred triples: 412
    Precision: 0.704
    Recall   : 0.591
    F1       : 0.642
    (TP=290, FP=122, FN=201)
================================================
2026-08-26 17:44:59,771 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:00,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:01,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:01,438 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:02,729 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:02,731 | WARNING | 生成失败：sample_id=629 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:45:03,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:04,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:05,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:06,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:06,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:07,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:07,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:08,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:09,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:10,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:10,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:12,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:13,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:13,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:14,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:15,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:15,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:16,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:17,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:18,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:19,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:19,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:20,741 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:21,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:22,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:23,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:23,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:24,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:24,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:25,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:26,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:26,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:26,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:27,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:28,031 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:28,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:29,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:31,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:31,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:31,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:32,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:33,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:45:33,788 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:34,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:35,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:35,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:35,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:36,627 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:38,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:38,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:39,371 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:39,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:41,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:42,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:42,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:43,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:43,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:43,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:44,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:45,058 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:45,662 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:46,063 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:46,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:47,449 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:48,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:48,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:49,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:49,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:50,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:50,728 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:51,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:51,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:52,280 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:52,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:53,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:53,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:54,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:54,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:55,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:56,104 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:57,000 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:58,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:58,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:59,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:45:59,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:00,529 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:01,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:02,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:03,007 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:03,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:03,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:04,589 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:05,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:06,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:07,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:07,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:07,922 | INFO |
2026-08-26 17:46:07,923 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 800/1038 ================
样本总数: 800
  Gold 含因果: 423 | Pred 含因果: 533
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.787
  Precision: 0.737
  Recall   : 0.929
  F1       : 0.822
  (TP=393, TN=237, FP=140, FN=30)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 800
    Gold triples: 591 | Pred triples: 629
    Precision: 0.479
    Recall   : 0.509
    F1       : 0.493
    (TP=301, FP=328, FN=290)
  [anchor_window] (primary)
    样本数: 800
    Gold triples: 591 | Pred triples: 629
    Precision: 0.529
    Recall   : 0.563
    F1       : 0.546
    (TP=333, FP=296, FN=258)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 393
    Gold triples: 558 | Pred triples: 471
    Precision: 0.639
    Recall   : 0.539
    F1       : 0.585
    (TP=301, FP=170, FN=257)
  [anchor_window] (primary)
    样本数: 393
    Gold triples: 558 | Pred triples: 471
    Precision: 0.707
    Recall   : 0.597
    F1       : 0.647
    (TP=333, FP=138, FN=225)
================================================
2026-08-26 17:46:08,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:09,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:10,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:11,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:11,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:11,817 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:12,391 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:12,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:46:13,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:13,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:14,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:15,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:16,382 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:17,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:17,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:17,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:18,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:19,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:19,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:20,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:20,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:21,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:22,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:22,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:23,680 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:24,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:25,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:25,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:26,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:27,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:27,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:28,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:28,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:29,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:29,963 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:30,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:30,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:31,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:31,799 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:32,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:33,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:34,281 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:34,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:35,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:35,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:36,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:37,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:38,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:39,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:40,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:40,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:41,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:42,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:42,794 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:43,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:44,555 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:45,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:46,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:47,679 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:48,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:48,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:49,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:50,289 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:51,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:51,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:52,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:53,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:53,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:54,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:54,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:55,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:55,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:56,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:58,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:59,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:46:59,699 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:00,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:00,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:01,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:02,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:02,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:03,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:47:04,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:04,589 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:05,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:06,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:07,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:07,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:08,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:10,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:10,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:11,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:11,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:12,328 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:13,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:13,745 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:14,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:15,534 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:16,439 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:16,827 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:16,829 | INFO |
2026-08-26 17:47:16,830 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 900/1038 ================
样本总数: 900
  Gold 含因果: 480 | Pred 含因果: 598
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.784
  Precision: 0.739
  Recall   : 0.921
  F1       : 0.820
  (TP=442, TN=264, FP=156, FN=38)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 900
    Gold triples: 669 | Pred triples: 706
    Precision: 0.483
    Recall   : 0.510
    F1       : 0.496
    (TP=341, FP=365, FN=328)
  [anchor_window] (primary)
    样本数: 900
    Gold triples: 669 | Pred triples: 706
    Precision: 0.541
    Recall   : 0.571
    F1       : 0.556
    (TP=382, FP=324, FN=287)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 442
    Gold triples: 627 | Pred triples: 530
    Precision: 0.643
    Recall   : 0.544
    F1       : 0.589
    (TP=341, FP=189, FN=286)
  [anchor_window] (primary)
    样本数: 442
    Gold triples: 627 | Pred triples: 530
    Precision: 0.721
    Recall   : 0.609
    F1       : 0.660
    (TP=382, FP=148, FN=245)
================================================
2026-08-26 17:47:17,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:17,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:18,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:19,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:19,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:20,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:21,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:21,962 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:22,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:23,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:23,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:24,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:25,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:25,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:26,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:26,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:27,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:28,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:28,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:29,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:29,699 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:30,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:31,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:32,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:33,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:33,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:34,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:35,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:35,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:36,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:37,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:37,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:38,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:38,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:39,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:39,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:40,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:40,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:41,295 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:42,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:42,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:43,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:43,905 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:44,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:47:45,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:46,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:46,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:47,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:47,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:47,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:48,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:49,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:49,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:50,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:50,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:51,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:51,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:52,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:52,762 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:53,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:53,787 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:54,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:54,567 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:55,293 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:55,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:57,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:57,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:58,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:59,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:47:59,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:00,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:01,006 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:01,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:02,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:03,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:03,995 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:04,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:05,271 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:06,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:06,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:07,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:08,046 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:08,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:09,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:10,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:11,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:12,119 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:12,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:13,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:14,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:15,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:15,774 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:16,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:16,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:17,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:17,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:18,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:18,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:19,211 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:20,296 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:20,297 | INFO |
2026-08-26 17:48:20,297 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test progress 1000/1038 ================
样本总数: 1000
  Gold 含因果: 529 | Pred 含因果: 660
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.785
  Precision: 0.738
  Recall   : 0.921
  F1       : 0.819
  (TP=487, TN=298, FP=173, FN=42)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1000
    Gold triples: 739 | Pred triples: 774
    Precision: 0.479
    Recall   : 0.502
    F1       : 0.490
    (TP=371, FP=403, FN=368)
  [anchor_window] (primary)
    样本数: 1000
    Gold triples: 739 | Pred triples: 774
    Precision: 0.539
    Recall   : 0.564
    F1       : 0.551
    (TP=417, FP=357, FN=322)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 487
    Gold triples: 692 | Pred triples: 580
    Precision: 0.640
    Recall   : 0.536
    F1       : 0.583
    (TP=371, FP=209, FN=321)
  [anchor_window] (primary)
    样本数: 487
    Gold triples: 692 | Pred triples: 580
    Precision: 0.719
    Recall   : 0.603
    F1       : 0.656
    (TP=417, FP=163, FN=275)
================================================
2026-08-26 17:48:20,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:21,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:22,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:22,221 | WARNING | 生成失败：sample_id=219 attempt=1/2 error=未找到 JSON 对象
2026-08-26 17:48:22,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:23,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:48:24,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:25,613 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:26,025 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:26,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:26,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:27,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:27,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:28,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:29,058 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:29,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:30,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:31,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:31,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:31,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:32,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:33,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:34,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:34,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:35,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:36,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:37,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:38,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:38,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:39,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:40,025 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:40,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:40,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:41,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:42,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:42,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:43,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:44,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:44,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:45,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:48:45,661 | INFO |
2026-08-26 17:48:45,661 | INFO | ================ Gemma 4 26B A4B QAT CNC fixed test final report ================
样本总数: 1038
  Gold 含因果: 548 | Pred 含因果: 682
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.790
  Precision: 0.742
  Recall   : 0.923
  F1       : 0.823
  (TP=506, TN=314, FP=176, FN=42)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1038
    Gold triples: 763 | Pred triples: 799
    Precision: 0.484
    Recall   : 0.507
    F1       : 0.496
    (TP=387, FP=412, FN=376)
  [anchor_window] (primary)
    样本数: 1038
    Gold triples: 763 | Pred triples: 799
    Precision: 0.541
    Recall   : 0.566
    F1       : 0.553
    (TP=432, FP=367, FN=331)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 506
    Gold triples: 716 | Pred triples: 602
    Precision: 0.643
    Recall   : 0.541
    F1       : 0.587
    (TP=387, FP=215, FN=329)
  [anchor_window] (primary)
    样本数: 506
    Gold triples: 716 | Pred triples: 602
    Precision: 0.718
    Recall   : 0.603
    F1       : 0.656
    (TP=432, FP=170, FN=284)
================================================
2026-08-26 17:48:45,663 | INFO | ================ 前 10 条样本判定 ================

--- id=1120 ---
text: They were attacking a student leader and a fighter .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2291 ---
text: Protesters have also surrounded the police headquarters twice in past weeks in noisy and emotionally charged protests in which young people spray-painted obscenities on its front wall and barricaded its entrances .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 2, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 2, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 2, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "in noisy and emotionally charged protests"
    },
    "relation": "caused",
    "effect": {
      "span": "Protesters have also surrounded the police headquarters twice in past weeks in which young people spray-painted obscenities on its front wall and barricaded its entrances"
    }
  },
  {
    "cause": {
      "span": "in noisy and emotionally charged protests"
    },
    "relation": "caused",
    "effect": {
      "span": "young people spray-painted obscenities on its front wall and barricaded its entrances"
    }
  }
]

--- id=2733 ---
text: Authorities also rejected a request to hold one on Sunday in Sheung Wan , near where police fired teargas and rubber bullets on demonstrators who had defaced China ’ s representative office in Hong Kong last week .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "demonstrators who had defaced China ’ s representative office in Hong Kong last week"
    },
    "relation": "caused",
    "effect": {
      "span": "police fired teargas and rubber bullets on demonstrators"
    }
  }
]

--- id=2124 ---
text: On Tuesday we went to picket at the Western Cape Provincial Legislature after we had gone over a month without teachers .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "we had gone over a month without teachers",
    "effect": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "after we had gone over a month without teachers"
    },
    "relation": "caused",
    "effect": {
      "span": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
    }
  }
]

--- id=450 ---
text: Protestors in Clashes With Police on Jammu-Pathankot NH During Eviction Drive 22nd February 2016 05:22 PM JAMMU : Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday , police said .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 2, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 2, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 2, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "During Eviction Drive"
    },
    "relation": "caused",
    "effect": {
      "span": "Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday"
    }
  },
  {
    "cause": {
      "span": "During Eviction Drive"
    },
    "relation": "caused",
    "effect": {
      "span": "Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday , police said"
    }
  }
]

--- id=777 ---
text: ANDHRA PRADESH ` Delay ' in compensation : ryots lay siege to MRO office March 14 , 2006 00:00 IST Staff Reporter Telugu Desam , CPI(M) leaders lead the protest VIJAYAWADA : Betel nut farmers from Garikaparru and Thotlavalluru villages under Thotlavalluru mandal laid siege to the Mandal Revenue Office on Monday .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "Delay ' in compensation"
    },
    "relation": "caused",
    "effect": {
      "span": "ryots lay siege to MRO office"
    }
  }
]

--- id=769 ---
text: The march was organised by the Federation of South African Women ( Fedsaw ) and led by Helen Joseph , Rahima Moosa , Sophie Williams and Lilian Ngoyi .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=542 ---
text: We totally support the ongoing strike since VAT imposed by the government is unjust but the business has to run if we are to recover losses , ” said a shop owner near Charminar .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 2, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 2, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 1, 'fn': 1}
gold_relations:
[
  {
    "cause": "VAT imposed by the government is unjust",
    "effect": "We totally support the ongoing strike"
  },
  {
    "cause": "if we are to recover losses",
    "effect": "the business has to run"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "VAT imposed by the government is unjust"
    },
    "relation": "caused",
    "effect": {
      "span": "We totally support the ongoing strike"
    }
  },
  {
    "cause": {
      "span": "we are to recover losses"
    },
    "relation": "caused",
    "effect": {
      "span": "the business has to run"
    }
  }
]

--- id=1420 ---
text: The protest went on for more than two hours and shops on the highway were shut during that time .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1368 ---
text: According to one villager , officials have frozen that money to prevent villagers funding a journey to Beijing to continue their petitioning .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "to prevent villagers funding a journey to Beijing to continue their petitioning",
    "effect": "officials have frozen that money"
  },
  {
    "cause": "to continue their petitioning",
    "effect": "villagers funding a journey to Beijing"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "to prevent villagers funding a journey to Beijing to continue their petitioning"
    },
    "relation": "caused",
    "effect": {
      "span": "officials have frozen that money"
    }
  }
]

2026-08-26 17:48:45,677 | INFO | Eval report saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\google-gemma-4-26b-a4b-qat_cnc_sft_test-n1038_prompt-v9.8_rag-knn_pattern-k1_20260826-174845.md
2026-08-26 17:48:45,697 | INFO | [eval 4/4] 开始 google/gemma-4-31b-qat
2026-08-26 17:49:01,351 | INFO | Pattern examples 已加载：path=D:\Master thesis\RAG Database\cnc_examples.jsonl examples=600
2026-08-26 17:49:01,361 | INFO | KNN cache 已加载：examples=600 path=D:\Master thesis\RAG Database\cnc_examples.jsonl embedding_device=cpu

2026-08-26 17:49:01,638 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:01,666 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:49:01,817 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:01,846 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:49:01,849 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-08-26 17:49:02,040 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:02,068 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-26 17:49:02,220 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:02,248 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-08-26 17:49:02,399 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:02,427 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-26 17:49:02,612 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:02,695 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-26 17:49:02,874 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:49:03,039 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:03,069 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 6321.41it/s]
2026-08-26 17:49:03,303 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:49:03,460 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:49:03,613 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:49:03,771 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-26 17:49:03,928 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:03,957 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:49:04,114 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:04,144 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:49:04,299 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:04,327 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-26 17:49:04,481 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:04,510 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-26 17:49:04,671 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-26 17:49:04,829 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-26 17:49:05,025 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-26 17:49:05,054 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-26 17:49:05,227 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-08-26 17:49:08,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:09,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:15,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:20,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:22,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:24,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:25,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:34,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:35,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:41,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:53,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:49:54,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:03,121 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:14,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:19,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:22,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:24,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:29,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:42,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:47,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:49,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:50:53,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:50:55,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:02,812 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:06,625 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:08,147 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:15,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:17,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:24,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:25,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:38,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:40,196 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:41,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:43,254 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:49,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:51,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:51:59,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:05,278 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:06,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:17,055 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:22,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:27,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:32,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:41,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:42,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:48,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:55,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:52:57,072 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:01,708 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:05,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:06,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:15,365 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:16,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:18,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:19,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:25,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:32,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:39,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:46,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:51,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:53:58,115 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:03,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:09,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:15,470 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:21,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:26,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:32,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:34,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:39,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:40,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:42,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:46,869 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:50,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:55,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:54:59,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:01,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:02,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:04,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:09,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:20,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:24,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:26,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:27,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:36,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:37,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:44,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:49,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:50,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:55,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:55:57,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:02,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:08,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:12,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:17,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:23,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 17:56:25,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:35,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:41,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:42,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:50,869 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:50,891 | INFO |
2026-08-26 17:56:50,893 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 100/1038 ================
样本总数: 100
  Gold 含因果: 57 | Pred 含因果: 64
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.830
  Precision: 0.812
  Recall   : 0.912
  F1       : 0.860
  (TP=52, TN=31, FP=12, FN=5)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 100
    Gold triples: 81 | Pred triples: 83
    Precision: 0.554
    Recall   : 0.568
    F1       : 0.561
    (TP=46, FP=37, FN=35)
  [anchor_window] (primary)
    样本数: 100
    Gold triples: 81 | Pred triples: 83
    Precision: 0.602
    Recall   : 0.617
    F1       : 0.610
    (TP=50, FP=33, FN=31)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 52
    Gold triples: 76 | Pred triples: 69
    Precision: 0.667
    Recall   : 0.605
    F1       : 0.634
    (TP=46, FP=23, FN=30)
  [anchor_window] (primary)
    样本数: 52
    Gold triples: 76 | Pred triples: 69
    Precision: 0.725
    Recall   : 0.658
    F1       : 0.690
    (TP=50, FP=19, FN=26)
================================================
2026-08-26 17:56:54,373 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:56:55,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:00,533 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:05,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:07,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:10,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:11,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:17,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:22,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:23,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:31,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:38,394 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:43,752 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:45,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:50,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:52,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:56,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:57:57,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:03,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:08,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:14,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:22,328 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:28,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:34,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:36,390 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:46,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:47,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:58:53,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:00,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:08,602 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:19,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:21,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:22,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:28,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:29,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:31,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:32,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:34,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:38,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:39,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:46,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:55,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 17:59:56,729 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:02,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:07,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:08,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:10,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:11,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:13,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:22,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:27,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:37,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:38,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:43,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:44,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:46,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:53,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:00:55,299 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:56,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:00:59,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:05,473 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:11,463 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:12,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:19,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:23,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:24,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:29,815 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:35,316 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:36,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:40,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:47,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:48,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:50,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:01:57,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:03,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:08,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:12,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:14,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:15,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:18,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:23,489 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:29,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:30,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:32,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:36,840 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:38,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:43,662 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:47,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:54,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:02:59,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:07,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:17,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:18,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:23,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:29,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:30,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:32,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:33,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:35,082 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:41,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:41,135 | INFO |
2026-08-26 18:03:41,136 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 200/1038 ================
样本总数: 200
  Gold 含因果: 107 | Pred 含因果: 123
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.840
  Precision: 0.805
  Recall   : 0.925
  F1       : 0.861
  (TP=99, TN=69, FP=24, FN=8)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 200
    Gold triples: 147 | Pred triples: 156
    Precision: 0.558
    Recall   : 0.592
    F1       : 0.574
    (TP=87, FP=69, FN=60)
  [anchor_window] (primary)
    样本数: 200
    Gold triples: 147 | Pred triples: 156
    Precision: 0.609
    Recall   : 0.646
    F1       : 0.627
    (TP=95, FP=61, FN=52)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 99
    Gold triples: 139 | Pred triples: 128
    Precision: 0.680
    Recall   : 0.626
    F1       : 0.652
    (TP=87, FP=41, FN=52)
  [anchor_window] (primary)
    样本数: 99
    Gold triples: 139 | Pred triples: 128
    Precision: 0.742
    Recall   : 0.683
    F1       : 0.712
    (TP=95, FP=33, FN=44)
================================================
2026-08-26 18:03:57,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:03:58,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:04,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:11,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:14,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:18,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:27,960 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:29,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:30,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:34,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:39,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:46,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:51,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:52,906 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:04:54,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:00,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:10,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:12,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:14,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:05:17,550 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:19,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:30,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:32,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:34,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:35,650 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:43,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:48,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:50,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:51,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:54,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:05:59,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:04,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:06,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:12,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:16,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:18,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:23,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:29,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:31,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:32,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:34,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:39,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:47,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:52,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:57,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:06:59,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:05,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:15,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:19,776 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:21,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:26,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:31,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:33,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:34,752 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:40,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:42,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:45,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:49,867 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:51,554 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:07:54,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:00,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:02,202 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:07,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:13,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:19,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:25,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:32,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:37,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:42,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:43,583 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:48,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:51,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:53,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:08:59,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:00,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:05,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:06,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:11,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:17,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:19,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:25,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:31,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:33,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:48,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:53,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:09:56,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:01,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:05,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:10,554 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:16,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:17,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:23,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:28,529 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:10:33,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:34,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:44,078 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:49,514 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:51,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:56,686 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:58,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:10:58,179 | INFO |
2026-08-26 18:10:58,180 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 300/1038 ================
样本总数: 300
  Gold 含因果: 155 | Pred 含因果: 188
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.810
  Precision: 0.761
  Recall   : 0.923
  F1       : 0.834
  (TP=143, TN=100, FP=45, FN=12)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 300
    Gold triples: 214 | Pred triples: 235
    Precision: 0.519
    Recall   : 0.570
    F1       : 0.543
    (TP=122, FP=113, FN=92)
  [anchor_window] (primary)
    样本数: 300
    Gold triples: 214 | Pred triples: 235
    Precision: 0.579
    Recall   : 0.636
    F1       : 0.606
    (TP=136, FP=99, FN=78)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 143
    Gold triples: 202 | Pred triples: 185
    Precision: 0.659
    Recall   : 0.604
    F1       : 0.630
    (TP=122, FP=63, FN=80)
  [anchor_window] (primary)
    样本数: 143
    Gold triples: 202 | Pred triples: 185
    Precision: 0.735
    Recall   : 0.673
    F1       : 0.703
    (TP=136, FP=49, FN=66)
================================================
2026-08-26 18:11:03,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:09,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:10,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:14,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:15,728 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:17,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:22,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:24,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:25,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:33,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:38,873 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:11:44,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:03,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:05,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:10,686 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:14,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:20,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:28,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:29,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:31,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:32,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:34,275 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:39,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:41,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:48,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:57,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:12:58,573 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:00,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:05,745 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:15,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:16,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:22,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:28,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:34,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:35,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:41,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:42,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:44,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:49,669 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:54,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:13:56,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:02,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:06,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:11,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:16,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:20,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:25,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:28,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:35,106 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:42,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:44,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:49,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:52,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:54,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:14:59,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:15:04,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:09,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:17,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:18,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:21,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:30,542 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:35,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:36,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:38,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:39,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:43,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:48,536 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:50,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:15:55,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:00,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:05,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:20,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:28,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:29,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:38,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:40,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:48,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:53,848 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:55,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:56,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:16:58,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:02,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:04,438 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:05,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:11,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:13,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:22,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:23,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:29,827 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:31,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:35,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:36,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:44,670 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:52,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:57,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:17:59,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:00,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:02,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:07,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:11,246 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:11,248 | INFO |
2026-08-26 18:18:11,248 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 400/1038 ================
样本总数: 400
  Gold 含因果: 202 | Pred 含因果: 249
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.823
  Precision: 0.763
  Recall   : 0.941
  F1       : 0.843
  (TP=190, TN=139, FP=59, FN=12)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 400
    Gold triples: 279 | Pred triples: 309
    Precision: 0.521
    Recall   : 0.577
    F1       : 0.548
    (TP=161, FP=148, FN=118)
  [anchor_window] (primary)
    样本数: 400
    Gold triples: 279 | Pred triples: 309
    Precision: 0.579
    Recall   : 0.642
    F1       : 0.609
    (TP=179, FP=130, FN=100)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 190
    Gold triples: 267 | Pred triples: 242
    Precision: 0.665
    Recall   : 0.603
    F1       : 0.633
    (TP=161, FP=81, FN=106)
  [anchor_window] (primary)
    样本数: 190
    Gold triples: 267 | Pred triples: 242
    Precision: 0.740
    Recall   : 0.670
    F1       : 0.703
    (TP=179, FP=63, FN=88)
================================================
2026-08-26 18:18:17,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:22,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:28,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:29,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:31,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:36,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:41,377 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:18:49,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:01,469 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:04,772 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:11,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:13,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:16,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:18,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:19,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:21,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:28,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:19:34,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:35,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:39,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:46,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:52,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:54,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:19:55,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:02,236 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:03,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:10,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:11,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:20,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:30,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:33,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:37,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:42,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:44,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:53,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:55,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:20:56,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:04,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:05,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:11,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:24,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:30,070 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:31,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:37,840 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:43,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:50,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:56,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:21:57,640 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:02,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:04,354 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:14,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:17,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:22,626 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:33,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:38,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:40,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:48,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:50,435 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:22:56,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:01,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:06,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:12,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:17,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:25,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:34,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:37,396 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:42,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:44,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:49,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:54,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:23:59,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:03,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:04,571 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:07,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:17,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:21,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:23,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:29,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:36,170 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:42,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:44,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:49,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:53,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:54,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:24:56,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:01,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:02,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:08,059 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:09,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:15,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:23,493 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:25:29,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:31,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:32,705 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:41,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:47,948 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:55,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:25:58,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:03,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:09,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:09,303 | INFO |
2026-08-26 18:26:09,303 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 500/1038 ================
样本总数: 500
  Gold 含因果: 266 | Pred 含因果: 319
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.822
  Precision: 0.777
  Recall   : 0.932
  F1       : 0.848
  (TP=248, TN=163, FP=71, FN=18)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 500
    Gold triples: 369 | Pred triples: 398
    Precision: 0.530
    Recall   : 0.572
    F1       : 0.550
    (TP=211, FP=187, FN=158)
  [anchor_window] (primary)
    样本数: 500
    Gold triples: 369 | Pred triples: 398
    Precision: 0.606
    Recall   : 0.653
    F1       : 0.628
    (TP=241, FP=157, FN=128)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 248
    Gold triples: 351 | Pred triples: 318
    Precision: 0.664
    Recall   : 0.601
    F1       : 0.631
    (TP=211, FP=107, FN=140)
  [anchor_window] (primary)
    样本数: 248
    Gold triples: 351 | Pred triples: 318
    Precision: 0.758
    Recall   : 0.687
    F1       : 0.720
    (TP=241, FP=77, FN=110)
================================================
2026-08-26 18:26:15,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:16,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:18,364 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:22,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:23,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:34,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:39,031 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:40,578 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:42,167 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:51,470 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:52,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:54,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:26:58,549 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:00,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:06,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:12,605 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:14,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:22,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:27,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:29,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:35,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:40,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:45,775 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:47,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:52,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:27:57,755 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:08,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:14,647 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:20,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:22,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:23,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:35,082 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:36,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:40,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:28:52,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:00,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:02,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:07,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:13,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:15,121 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:18,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:22,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:32,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:39,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:40,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:42,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:48,477 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:53,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:54,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:29:58,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:02,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:12,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:22,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:30:25,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:35,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:38,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:45,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:50,678 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:52,168 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:53,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:30:58,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:04,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:08,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:10,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:12,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:13,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:18,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:19,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:24,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:25,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:27,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:28,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:34,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:35,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:39,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:42,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:47,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:53,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:58,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:31:59,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:06,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:08,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:13,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:20,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:23,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:29,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:35,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:40,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:41,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:47,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:53,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:54,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:32:56,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:04,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:06,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:14,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:19,382 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:24,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:26,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:30,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:30,211 | INFO |
2026-08-26 18:33:30,212 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 600/1038 ================
样本总数: 600
  Gold 含因果: 317 | Pred 含因果: 383
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.823
  Precision: 0.775
  Recall   : 0.937
  F1       : 0.849
  (TP=297, TN=197, FP=86, FN=20)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 600
    Gold triples: 443 | Pred triples: 481
    Precision: 0.538
    Recall   : 0.585
    F1       : 0.561
    (TP=259, FP=222, FN=184)
  [anchor_window] (primary)
    样本数: 600
    Gold triples: 443 | Pred triples: 481
    Precision: 0.609
    Recall   : 0.661
    F1       : 0.634
    (TP=293, FP=188, FN=150)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 297
    Gold triples: 423 | Pred triples: 386
    Precision: 0.671
    Recall   : 0.612
    F1       : 0.640
    (TP=259, FP=127, FN=164)
  [anchor_window] (primary)
    样本数: 297
    Gold triples: 423 | Pred triples: 386
    Precision: 0.759
    Recall   : 0.693
    F1       : 0.724
    (TP=293, FP=93, FN=130)
================================================
2026-08-26 18:33:38,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:43,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:49,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:53,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:55,478 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:56,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:33:58,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:07,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:12,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:14,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:17,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:18,761 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:20,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:21,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:29,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:34:34,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:41,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:42,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:44,055 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:45,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:51,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:34:59,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:10,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:16,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:21,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:28,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:34,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:37,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:39,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:44,286 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:45,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:47,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:35:53,904 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:00,351 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:01,896 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:03,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:08,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:09,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:11,292 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:14,473 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:16,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:20,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:23,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:24,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:28,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:29,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:35,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:36,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:39,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:41,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:47,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:48,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:51,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:53,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:36:58,223 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:05,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:13,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:18,840 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:25,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:26,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:28,240 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:29,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:35,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:41,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:51,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:53,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:37:54,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:03,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:09,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:14,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:19,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:23,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:33,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:39,500 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:45,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:51,240 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:38:52,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:07,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:14,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:15,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:19,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:21,146 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:32,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:33,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:35,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:36,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:42,530 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:47,607 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:52,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:39:55,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:39:57,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:03,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:04,647 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:10,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:18,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:24,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:25,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:27,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:31,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:36,770 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:36,771 | INFO |
2026-08-26 18:40:36,771 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 700/1038 ================
样本总数: 700
  Gold 含因果: 373 | Pred 含因果: 444
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.821
  Precision: 0.779
  Recall   : 0.928
  F1       : 0.847
  (TP=346, TN=229, FP=98, FN=27)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 700
    Gold triples: 521 | Pred triples: 559
    Precision: 0.546
    Recall   : 0.585
    F1       : 0.565
    (TP=305, FP=254, FN=216)
  [anchor_window] (primary)
    样本数: 700
    Gold triples: 521 | Pred triples: 559
    Precision: 0.617
    Recall   : 0.662
    F1       : 0.639
    (TP=345, FP=214, FN=176)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 346
    Gold triples: 494 | Pred triples: 451
    Precision: 0.676
    Recall   : 0.617
    F1       : 0.646
    (TP=305, FP=146, FN=189)
  [anchor_window] (primary)
    样本数: 346
    Gold triples: 494 | Pred triples: 451
    Precision: 0.765
    Recall   : 0.698
    F1       : 0.730
    (TP=345, FP=106, FN=149)
================================================
2026-08-26 18:40:38,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:46,060 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:49,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:51,059 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:40:59,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:05,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:08,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:14,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:15,801 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:22,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:31,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:32,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:38,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:46,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:49,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:41:59,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:04,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:11,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:12,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:20,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:21,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:23,337 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:28,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:32,587 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:39,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:41,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:42:50,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:01,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:07,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:09,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:13,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:14,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:16,439 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:23,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:26,578 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:28,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:29,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:31,295 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:36,223 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:40,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:47,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:55,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:43:57,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:02,107 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:08,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:16,693 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:18,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:19,687 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:25,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:26,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:28,236 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:44:29,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:44,524 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:46,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:47,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:49,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:44:59,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:05,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:08,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:10,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:11,908 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:13,406 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:16,542 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:21,459 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:26,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:27,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:31,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:36,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:40,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:45,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:47,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:48,589 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:50,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:51,669 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:53,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:54,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:45:59,901 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:01,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:06,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:08,278 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:09,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:11,292 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:16,573 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:22,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:28,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:40,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:42,286 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:43,822 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:49,831 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:53,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:46:54,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:00,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:05,762 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:07,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:10,650 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:15,608 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:20,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:27,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:28,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:30,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:30,023 | INFO |
2026-08-26 18:47:30,024 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 800/1038 ================
样本总数: 800
  Gold 含因果: 423 | Pred 含因果: 501
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.820
  Precision: 0.778
  Recall   : 0.922
  F1       : 0.844
  (TP=390, TN=266, FP=111, FN=33)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 800
    Gold triples: 591 | Pred triples: 632
    Precision: 0.544
    Recall   : 0.582
    F1       : 0.563
    (TP=344, FP=288, FN=247)
  [anchor_window] (primary)
    样本数: 800
    Gold triples: 591 | Pred triples: 632
    Precision: 0.616
    Recall   : 0.658
    F1       : 0.636
    (TP=389, FP=243, FN=202)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 390
    Gold triples: 558 | Pred triples: 510
    Precision: 0.675
    Recall   : 0.616
    F1       : 0.644
    (TP=344, FP=166, FN=214)
  [anchor_window] (primary)
    样本数: 390
    Gold triples: 558 | Pred triples: 510
    Precision: 0.763
    Recall   : 0.697
    F1       : 0.728
    (TP=389, FP=121, FN=169)
================================================
2026-08-26 18:47:36,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:45,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:53,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:47:56,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:02,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:07,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:12,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:13,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:15,101 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:16,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:24,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:26,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:33,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:48:37,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:38,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:40,083 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:46,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:48,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:49,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:48:55,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:01,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:06,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:15,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:17,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:22,893 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:28,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:34,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:37,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:43,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:47,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:49,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:49:54,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:01,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:06,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:08,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:13,106 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:14,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:19,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:21,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:22,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:29,959 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:31,496 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:33,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:38,698 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:44,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:50:48,455 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:00,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:06,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:12,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:17,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:24,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:32,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:33,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:35,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:37,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:47,385 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:48,943 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:51:54,787 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:02,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:03,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:10,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:14,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:16,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:22,886 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:28,687 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:36,807 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:40,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:44,082 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:48,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:49,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:53,032 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:52:57,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:02,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:13,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:19,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:23,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:25,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:31,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:37,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:39,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:47,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:51,371 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:56,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:53:58,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:06,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:13,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:14,618 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:54:21,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:28,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:34,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:39,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:44,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:46,033 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:51,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:55,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:54:57,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:01,046 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:10,624 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:15,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:16,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:16,968 | INFO |
2026-08-26 18:55:16,969 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 900/1038 ================
样本总数: 900
  Gold 含因果: 480 | Pred 含因果: 571
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.819
  Precision: 0.778
  Recall   : 0.925
  F1       : 0.845
  (TP=444, TN=293, FP=127, FN=36)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 900
    Gold triples: 669 | Pred triples: 717
    Precision: 0.545
    Recall   : 0.584
    F1       : 0.564
    (TP=391, FP=326, FN=278)
  [anchor_window] (primary)
    样本数: 900
    Gold triples: 669 | Pred triples: 717
    Precision: 0.621
    Recall   : 0.665
    F1       : 0.642
    (TP=445, FP=272, FN=224)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 444
    Gold triples: 633 | Pred triples: 579
    Precision: 0.675
    Recall   : 0.618
    F1       : 0.645
    (TP=391, FP=188, FN=242)
  [anchor_window] (primary)
    样本数: 444
    Gold triples: 633 | Pred triples: 579
    Precision: 0.769
    Recall   : 0.703
    F1       : 0.734
    (TP=445, FP=134, FN=188)
================================================
2026-08-26 18:55:22,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:24,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:25,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:30,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:32,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:38,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:39,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:45,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:49,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:55:55,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:00,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:05,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:07,241 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:08,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:14,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:20,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:29,026 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:30,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:32,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:33,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:36,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:38,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:46,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:56:48,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:00,000 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:01,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:11,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:16,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:18,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:24,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:27,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:31,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:33,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:34,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:38,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:40,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:45,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:50,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:52,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:57:56,352 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:03,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:05,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:09,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:14,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:19,146 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:27,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:28,933 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:33,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:35,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 18:58:36,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:38,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:44,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:50,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:51,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:53,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:54,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:58:59,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:01,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:02,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:08,037 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:09,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:11,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:12,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:19,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:25,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:37,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:38,654 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:46,035 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:47,530 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:53,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 18:59:59,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:01,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:06,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:09,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:15,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:21,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:27,763 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:29,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:38,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:39,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:45,646 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:50,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:00:56,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:02,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:06,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:13,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:15,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:20,602 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:25,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:27,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:32,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:35,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:36,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:38,214 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:39,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:44,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:45,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:48,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:50,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:51,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:51,581 | INFO |
2026-08-26 19:01:51,581 | INFO | ================ Gemma 4 31B QAT CNC fixed test progress 1000/1038 ================
样本总数: 1000
  Gold 含因果: 529 | Pred 含因果: 628
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.817
  Precision: 0.775
  Recall   : 0.921
  F1       : 0.842
  (TP=487, TN=330, FP=141, FN=42)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1000
    Gold triples: 739 | Pred triples: 786
    Precision: 0.543
    Recall   : 0.578
    F1       : 0.560
    (TP=427, FP=359, FN=312)
  [anchor_window] (primary)
    样本数: 1000
    Gold triples: 739 | Pred triples: 786
    Precision: 0.622
    Recall   : 0.662
    F1       : 0.641
    (TP=489, FP=297, FN=250)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 487
    Gold triples: 696 | Pred triples: 631
    Precision: 0.677
    Recall   : 0.614
    F1       : 0.644
    (TP=427, FP=204, FN=269)
  [anchor_window] (primary)
    样本数: 487
    Gold triples: 696 | Pred triples: 631
    Precision: 0.775
    Recall   : 0.703
    F1       : 0.737
    (TP=489, FP=142, FN=207)
================================================
2026-08-26 19:01:53,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:01:58,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:04,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:11,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:18,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:24,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:26,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:27,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:29,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:34,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:40,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-26 19:02:43,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:45,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:02:50,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:01,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:03,181 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:04,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:06,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:15,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:22,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:24,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:29,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:34,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:38,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:44,496 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:45,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:47,534 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:49,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:50,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:52,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:53,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:03:59,930 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:04,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:05,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:07,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:16,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:21,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:26,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-26 19:04:26,676 | INFO |
2026-08-26 19:04:26,677 | INFO | ================ Gemma 4 31B QAT CNC fixed test final report ================
样本总数: 1038
  Gold 含因果: 548 | Pred 含因果: 649
  Primary extraction metric: anchor_window
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.820
  Precision: 0.778
  Recall   : 0.922
  F1       : 0.844
  (TP=505, TN=346, FP=144, FN=43)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1]
    样本数: 1038
    Gold triples: 763 | Pred triples: 811
    Precision: 0.545
    Recall   : 0.579
    F1       : 0.562
    (TP=442, FP=369, FN=321)
  [anchor_window] (primary)
    样本数: 1038
    Gold triples: 763 | Pred triples: 811
    Precision: 0.625
    Recall   : 0.664
    F1       : 0.644
    (TP=507, FP=304, FN=256)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1]
    样本数: 505
    Gold triples: 719 | Pred triples: 653
    Precision: 0.677
    Recall   : 0.615
    F1       : 0.644
    (TP=442, FP=211, FN=277)
  [anchor_window] (primary)
    样本数: 505
    Gold triples: 719 | Pred triples: 653
    Precision: 0.776
    Recall   : 0.705
    F1       : 0.739
    (TP=507, FP=146, FN=212)
================================================
2026-08-26 19:04:26,678 | INFO | ================ 前 10 条样本判定 ================

--- id=1120 ---
text: They were attacking a student leader and a fighter .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2291 ---
text: Protesters have also surrounded the police headquarters twice in past weeks in noisy and emotionally charged protests in which young people spray-painted obscenities on its front wall and barricaded its entrances .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2733 ---
text: Authorities also rejected a request to hold one on Sunday in Sheung Wan , near where police fired teargas and rubber bullets on demonstrators who had defaced China ’ s representative office in Hong Kong last week .
gold_has_causal=False | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 0}
gold_relations:
[]
pred_triples:
[
  {
    "cause": {
      "span": "demonstrators who had defaced China ’ s representative office in Hong Kong last week"
    },
    "relation": "caused",
    "effect": {
      "span": "police fired teargas and rubber bullets on demonstrators"
    }
  }
]

--- id=2124 ---
text: On Tuesday we went to picket at the Western Cape Provincial Legislature after we had gone over a month without teachers .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "we had gone over a month without teachers",
    "effect": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "after we had gone over a month without teachers ."
    },
    "relation": "caused",
    "effect": {
      "span": "On Tuesday we went to picket at the Western Cape Provincial Legislature"
    }
  }
]

--- id=450 ---
text: Protestors in Clashes With Police on Jammu-Pathankot NH During Eviction Drive 22nd February 2016 05:22 PM JAMMU : Clashes erupted on the Jammu-Pathankot national highway between police and protesters in Samba district of Jammu region on Monday , police said .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=777 ---
text: ANDHRA PRADESH ` Delay ' in compensation : ryots lay siege to MRO office March 14 , 2006 00:00 IST Staff Reporter Telugu Desam , CPI(M) leaders lead the protest VIJAYAWADA : Betel nut farmers from Garikaparru and Thotlavalluru villages under Thotlavalluru mandal laid siege to the Mandal Revenue Office on Monday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=769 ---
text: The march was organised by the Federation of South African Women ( Fedsaw ) and led by Helen Joseph , Rahima Moosa , Sophie Williams and Lilian Ngoyi .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=542 ---
text: We totally support the ongoing strike since VAT imposed by the government is unjust but the business has to run if we are to recover losses , ” said a shop owner near Charminar .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 2, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 2, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 2, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "VAT imposed by the government is unjust",
    "effect": "We totally support the ongoing strike"
  },
  {
    "cause": "if we are to recover losses",
    "effect": "the business has to run"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "since VAT imposed by the government is unjust"
    },
    "relation": "caused",
    "effect": {
      "span": "We totally support the ongoing strike"
    }
  },
  {
    "cause": {
      "span": "if we are to recover losses"
    },
    "relation": "caused",
    "effect": {
      "span": "the business has to run"
    }
  }
]

--- id=1420 ---
text: The protest went on for more than two hours and shops on the highway were shut during that time .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1368 ---
text: According to one villager , officials have frozen that money to prevent villagers funding a journey to Beijing to continue their petitioning .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "to prevent villagers funding a journey to Beijing to continue their petitioning",
    "effect": "officials have frozen that money"
  },
  {
    "cause": "to continue their petitioning",
    "effect": "villagers funding a journey to Beijing"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "to prevent villagers funding a journey to Beijing to continue their petitioning ."
    },
    "relation": "caused",
    "effect": {
      "span": "officials have frozen that money"
    }
  }
]

2026-08-26 19:04:26,696 | INFO | Eval report saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\google-gemma-4-31b-qat_cnc_sft_test-n1038_prompt-v9.8_rag-knn_pattern-k1_20260826-190426.md
2026-08-26 19:04:26,697 | INFO | Parse repair outputs saved: D:\Master thesis\results\eval_report\lmstudio_batch_base_test\google-gemma-4-31b-qat_cnc_sft_test-n1038_prompt-v9.8_rag-knn_pattern-k1_20260826-190426_parse_repairs.jsonl

,status,model,model_key,prompt,rag,temperature,context_length,max_tokens,reasoning,detection_precision,...,strict_all_precision,strict_all_recall,strict_all_f1,anchor_all_precision,anchor_all_recall,anchor_all_f1,strict_detected_only_f1,anchor_detected_only_f1,report_path,error
0,completed,Qwen3.6 35B A3B,qwen/qwen3.6-35b-a3b,v9.6,knn_pattern-k1,0.0,8192,2048,model_default_off,0.801056,...,0.492980,0.414155,0.450142,0.407176,0.342071,0.371795,0.534235,0.441251,D:\Master thesis\results\eval_report\lmstudio_...,
1,completed,Qwen3.6 27B No Thinking,local/qwen3.6-27b-no-thinking,v9.6,knn_pattern-k1,0.0,8192,2048,model_default_off,0.811215,...,0.552860,0.418087,0.476119,0.578856,0.437746,0.498507,0.577376,0.604525,D:\Master thesis\results\eval_report\lmstudio_...,
2,completed,Gemma 4 26B A4B QAT,google/gemma-4-26b-a4b-qat,v9.8,knn_pattern-k1,0.0,8192,2048,model_default_off,0.741935,...,0.484355,0.507208,0.495519,0.540676,0.566186,0.553137,0.587253,0.655539,D:\Master thesis\results\eval_report\lmstudio_...,
3,completed,Gemma 4 31B QAT,google/gemma-4-31b-qat,v9.8,knn_pattern-k1,0.0,8192,2048,model_default_off,0.778120,...,0.545006,0.579292,0.561626,0.625154,0.664482,0.644219,0.644315,0.739067,D:\Master thesis\results\eval_report\lmstudio_...,

## 阶段 3：Qwen validation-selected RAG3 完整 test 补跑

Qwen3.6 27B No Thinking 作为 Qwen 家族代表模型，在 CNC validation 上由主指标 `strict_token_f1` 选出的家族配置是 **v9.6 Fixed 10-shot + KNN+Pattern RAG k=3**。本节将该参数用于 Qwen3.6 35B A3B 与 Qwen3.6 27B No Thinking 两个 Qwen 模型的完整 `cnc_sft_test`，不会重跑两个 Gemma 模型或阶段 2 的既有结果。

动态检索严格返回 3 条 Pattern 和 3 条 KNN train-only examples，因此每条请求共有 16 条 examples。两个模型均以 `context_length=8192`、`parallel=1`、KV cache GPU offload 开启的配置依次加载，并在每完成 200 条样本后卸载、重载同一模型；各自的详细报告与家族补跑 summary CSV 都会保留。

In [ ]:
# ===== Qwen RAG3 test 配置与隔离预检（不加载 LLM） =====
from src.prompt_builder import build_messages, load_prompt_template
from src.retriever import ExactCountHybridRetriever, KNNRetriever, PatternRetriever

RUN_QWEN_FAMILY_RAG3_TEST = False  # 35B 已完成、27B 已中止；不要再次运行原双模型入口。
QWEN_FAMILY_RAG3_TEST_SUMMARY_PATH = (
    PROJECT_ROOT / REPORT_DIR / 'qwen_family_fixed_rag_k3_test_summary.csv'
)
QWEN_FAMILY_RAG3_TEST_RUNS: list[dict[str, Any]] = [
    {
        'run_id': 'qwen35a3b_fixed_rag_k3_test',
        'display_name': 'Qwen3.6 35B A3B',
        'model_key': 'qwen/qwen3.6-35b-a3b',
        'prompt_name': 'v9.6',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 3,
        'dynamic_examples': 6,
        'total_examples': 16,
        'primary_metric': 'strict_token_f1',
        'context_length': 8192,
        'parallel': 1,
        'reload_every_samples': 200,
        'offload_kv_cache_to_gpu': True,
        'label': 'Qwen3.6 35B A3B CNC test fixed_rag_k3',
    },
    {
        'run_id': 'qwen27_fixed_rag_k3_test',
        'display_name': 'Qwen3.6 27B No Thinking',
        'model_key': 'local/qwen3.6-27b-no-thinking',
        'prompt_name': 'v9.6',
        'use_rag': True,
        'rag_database': 'cnc',
        'rag_mode': 'knn_pattern',
        'rag_top_k': 3,
        'dynamic_examples': 6,
        'total_examples': 16,
        'primary_metric': 'strict_token_f1',
        'context_length': 8192,
        'parallel': 1,
        'reload_every_samples': 200,
        'offload_kv_cache_to_gpu': True,
        'label': 'Qwen3.6 27B No Thinking CNC test fixed_rag_k3',
    },
]

qwen_rag3_metadata_path, qwen_rag3_embeddings_path = _rag_paths_for_run(
    QWEN_FAMILY_RAG3_TEST_RUNS[0]
)
qwen_rag3_manifest = json.loads(
    (PROJECT_ROOT / 'RAG Database/cnc_split_manifest.json').read_text(encoding='utf-8')
)
if not qwen_rag3_manifest.get('train_only_support'):
    raise RuntimeError('CNC RAG manifest 未声明 train_only_support。')

qwen_rag3_template = load_prompt_template(QWEN_FAMILY_RAG3_TEST_RUNS[0]['prompt_name'])
if qwen_rag3_template.count('\nInput:\n') != 10:
    raise RuntimeError('v9.6 不包含恰好 10 个 fixed examples。')
if qwen_rag3_template.count('{rag_examples}') != 1:
    raise RuntimeError('v9.6 必须包含且只包含一个 {rag_examples} 占位符。')

QWEN_RAG3_RETRIEVER = ExactCountHybridRetriever(
    pattern_retriever=PatternRetriever(metadata_path=qwen_rag3_metadata_path),
    knn_retriever=KNNRetriever(
        metadata_path=qwen_rag3_metadata_path,
        embeddings_path=qwen_rag3_embeddings_path,
        device='cpu',
    ),
)
qwen_rag3_audit_text = 'Heavy rain caused flooding in the region.'
qwen_rag3_examples = QWEN_RAG3_RETRIEVER.retrieve(qwen_rag3_audit_text, top_k=3)
qwen_rag3_messages = build_messages(
    qwen_rag3_audit_text,
    use_rag=True,
    retriever=QWEN_RAG3_RETRIEVER,
    top_k=3,
    rag_mode='knn_pattern',
    prompt_name='v9.6',
)
inserted_examples = qwen_rag3_messages[0]['content'].count('\nExample ')
if len(qwen_rag3_examples) != 6 or inserted_examples != 6:
    raise RuntimeError(
        f'Qwen RAG3 预检未得到严格 6 条动态示例：'
        f'retrieved={len(qwen_rag3_examples)} inserted={inserted_examples}'
    )
display(pd.DataFrame(QWEN_FAMILY_RAG3_TEST_RUNS))
LOGGER.info(
    'Qwen 家族 RAG3 test 预检通过；summary 将保存到：%s',
    QWEN_FAMILY_RAG3_TEST_SUMMARY_PATH,
)

In [ ]:
# ===== 依次补跑两个 Qwen 的 Fixed + RAG k=3 完整 test =====
if not RUN_QWEN_FAMILY_RAG3_TEST:
    LOGGER.warning(
        'Qwen 家族 RAG3 test 补跑未启动。将 RUN_QWEN_FAMILY_RAG3_TEST 改为 True。'
    )
else:
    QWEN_FAMILY_RAG3_TEST_RESULTS = run_formal_batch(
        QWEN_FAMILY_RAG3_TEST_RUNS,
        existing_retrievers={
            run['run_id']: QWEN_RAG3_RETRIEVER
            for run in QWEN_FAMILY_RAG3_TEST_RUNS
        },
        require_all_smoke=False,
    )
    qwen_family_rag3_test_df = pd.DataFrame(QWEN_FAMILY_RAG3_TEST_RESULTS)
    if (
        len(qwen_family_rag3_test_df) != len(QWEN_FAMILY_RAG3_TEST_RUNS)
        or not qwen_family_rag3_test_df['status'].eq('completed').all()
    ):
        raise RuntimeError('两个 Qwen 的 RAG3 完整 test 未全部成功，不保存正式 summary。')
    QWEN_FAMILY_RAG3_TEST_SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    qwen_family_rag3_test_df.to_csv(
        QWEN_FAMILY_RAG3_TEST_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info(
        'Qwen 家族 RAG3 test summary 已保存：%s',
        QWEN_FAMILY_RAG3_TEST_SUMMARY_PATH,
    )
    display(qwen_family_rag3_test_df)

In [ ]:
# ===== Qwen3.6 27B No Thinking RAG3 专用补跑：每 100 条重载 =====
RUN_QWEN27_RAG3_RELOAD100_RERUN = False  # 已终止的完整补跑；保留历史配置但不再自动运行。
QWEN27_RAG3_RELOAD100_SUMMARY_PATH = (
    PROJECT_ROOT
    / REPORT_DIR
    / 'qwen27_fixed_rag_k3_test_reload100_rerun_summary.csv'
)
QWEN27_RAG3_RELOAD100_RERUN = next(
    run.copy()
    for run in QWEN_FAMILY_RAG3_TEST_RUNS
    if run['model_key'] == 'local/qwen3.6-27b-no-thinking'
)
QWEN27_RAG3_RELOAD100_RERUN.update({
    'run_id': 'qwen27_fixed_rag_k3_test_reload100_rerun',
    'reload_every_samples': 100,
    'label': 'Qwen3.6 27B No Thinking CNC test fixed_rag_k3 reload100 rerun',
})
display(pd.DataFrame([QWEN27_RAG3_RELOAD100_RERUN]))

if not RUN_QWEN27_RAG3_RELOAD100_RERUN:
    LOGGER.warning('Qwen 27B reload100 专用补跑未启动。')
else:
    QWEN27_RAG3_RELOAD100_RESULTS = run_formal_batch(
        [QWEN27_RAG3_RELOAD100_RERUN],
        existing_retrievers={
            QWEN27_RAG3_RELOAD100_RERUN['run_id']: QWEN_RAG3_RETRIEVER,
        },
        require_all_smoke=False,
    )
    qwen27_rag3_reload100_df = pd.DataFrame(QWEN27_RAG3_RELOAD100_RESULTS)
    if (
        len(qwen27_rag3_reload100_df) != 1
        or qwen27_rag3_reload100_df.iloc[0]['status'] != 'completed'
        or int(qwen27_rag3_reload100_df.iloc[0]['reload_every_samples']) != 100
    ):
        raise RuntimeError('Qwen 27B reload100 专用补跑未成功，不保存正式 summary。')
    QWEN27_RAG3_RELOAD100_SUMMARY_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )
    qwen27_rag3_reload100_df.to_csv(
        QWEN27_RAG3_RELOAD100_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info(
        'Qwen 27B reload100 专用补跑 summary 已保存：%s',
        QWEN27_RAG3_RELOAD100_SUMMARY_PATH,
    )
    display(qwen27_rag3_reload100_df)

In [ ]:
# ===== Qwen3.6 27B cache_prompt=False 定点诊断：固定 test 第 590–636 条 =====
RUN_QWEN27_CACHE_PROMPT_OFF_DIAGNOSTIC = True
QWEN27_CACHE_PROMPT_OFF_SUMMARY_PATH = (
    PROJECT_ROOT
    / REPORT_DIR
    / 'qwen27_fixed_rag_k3_cache_prompt_off_diagnostic_590_636_summary.csv'
)
QWEN27_CACHE_PROMPT_OFF_RUN = next(
    run.copy()
    for run in QWEN_FAMILY_RAG3_TEST_RUNS
    if run['model_key'] == 'local/qwen3.6-27b-no-thinking'
)
QWEN27_CACHE_PROMPT_OFF_RUN.update({
    'run_id': 'qwen27_fixed_rag_k3_cache_prompt_off_diagnostic_590_636',
    'reload_every_samples': 0,
    'llm_extra_body': {'cache_prompt': False},
    'label': 'Qwen3.6 27B No Thinking cache_prompt off diagnostic 590-636',
})
qwen27_cache_prompt_off_samples = load_dataset(DATASET_NAME, n=None)[589:636]
if len(qwen27_cache_prompt_off_samples) != 47:
    raise RuntimeError('cache_prompt 诊断子集应包含 47 条样本。')
if (
    str(qwen27_cache_prompt_off_samples[5]['id']) != '2677'
    or str(qwen27_cache_prompt_off_samples[41]['id']) != '110'
):
    raise RuntimeError('cache_prompt 诊断子集的两个已知触发位置不匹配。')
display(pd.DataFrame([{
    **QWEN27_CACHE_PROMPT_OFF_RUN,
    'sample_range_1_based': '590-636',
    'sample_count': len(qwen27_cache_prompt_off_samples),
}]))

if not RUN_QWEN27_CACHE_PROMPT_OFF_DIAGNOSTIC:
    LOGGER.warning('Qwen 27B cache_prompt=False 定点诊断未启动。')
else:
    QWEN27_CACHE_PROMPT_OFF_RESULTS = run_formal_batch(
        [QWEN27_CACHE_PROMPT_OFF_RUN],
        existing_retrievers={
            QWEN27_CACHE_PROMPT_OFF_RUN['run_id']: QWEN_RAG3_RETRIEVER,
        },
        samples_override=qwen27_cache_prompt_off_samples,
        require_all_smoke=False,
    )
    qwen27_cache_prompt_off_df = pd.DataFrame(QWEN27_CACHE_PROMPT_OFF_RESULTS)
    if (
        len(qwen27_cache_prompt_off_df) != 1
        or qwen27_cache_prompt_off_df.iloc[0]['status'] != 'completed'
        or bool(qwen27_cache_prompt_off_df.iloc[0]['cache_prompt'])
    ):
        raise RuntimeError('Qwen 27B cache_prompt=False 定点诊断未成功，不保存 summary。')
    QWEN27_CACHE_PROMPT_OFF_SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    qwen27_cache_prompt_off_df.to_csv(
        QWEN27_CACHE_PROMPT_OFF_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info(
        'Qwen 27B cache_prompt=False 定点诊断 summary 已保存：%s',
        QWEN27_CACHE_PROMPT_OFF_SUMMARY_PATH,
    )
    display(qwen27_cache_prompt_off_df)

In [ ]:
# ===== Qwen3.6 27B 正式续跑：复用前 500 条，仅运行 501–1038 =====
RUN_QWEN27_REUSE500_TAIL = True
QWEN27_REUSE500_SUMMARY_PATH = (
    PROJECT_ROOT
    / REPORT_DIR
    / 'qwen27_fixed_rag_k3_test_reuse500_cache_prompt_off_tail_summary.csv'
)

# 来自 2026-08-27 13:29:50 的 progress 500/1038；全部保留为原始计数，避免由三位小数反推。
QWEN27_PREFIX500_COUNTS = {
    'n_samples': 500,
    'n_causal_gold': 266,
    'n_causal_pred': 281,
    'detection_tp': 228,
    'detection_tn': 181,
    'detection_fp': 53,
    'detection_fn': 38,
    'all_n_eval_samples': 500,
    'all_n_gold_triples': 369,
    'all_n_pred_triples': 313,
    'strict_all_tp': 175,
    'strict_all_fp': 138,
    'strict_all_fn': 194,
    'anchor_all_tp': 184,
    'anchor_all_fp': 129,
    'anchor_all_fn': 185,
    'detected_n_eval_samples': 228,
    'detected_n_gold_triples': 325,
    'detected_n_pred_triples': 254,
    'strict_detected_tp': 175,
    'strict_detected_fp': 79,
    'strict_detected_fn': 150,
    'anchor_detected_tp': 184,
    'anchor_detected_fp': 70,
    'anchor_detected_fn': 141,
}

QWEN27_REUSE500_RUN = next(
    run.copy()
    for run in QWEN_FAMILY_RAG3_TEST_RUNS
    if run['model_key'] == 'local/qwen3.6-27b-no-thinking'
)
QWEN27_REUSE500_RUN.update({
    'run_id': 'qwen27_fixed_rag_k3_test_reuse500_cache_prompt_off_tail',
    'reload_every_samples': 100,
    'llm_extra_body': {'cache_prompt': False},
    'label': 'Qwen3.6 27B No Thinking CNC test fixed_rag_k3 samples 501-1038',
})

qwen27_all_test_samples = load_dataset(DATASET_NAME, n=None)
qwen27_prefix500_samples = qwen27_all_test_samples[:500]
qwen27_tail_samples = qwen27_all_test_samples[500:]
if len(qwen27_all_test_samples) != 1038 or len(qwen27_tail_samples) != 538:
    raise RuntimeError('固定 test 顺序或样本数已变化，不能复用原前 500 条计数。')
if (
    str(qwen27_prefix500_samples[-1]['id']) != '30'
    or str(qwen27_tail_samples[0]['id']) != '1076'
    or sum(bool(sample['has_causal']) for sample in qwen27_prefix500_samples) != 266
    or sum(len(sample['relations']) for sample in qwen27_prefix500_samples) != 369
):
    raise RuntimeError('前 500 条数据与已保存 progress 计数不匹配，停止续跑。')
if 'detection_tp' not in _summary_row.__code__.co_consts:
    raise RuntimeError('请先重新运行“正式批量评测辅助函数”代码块，再执行本续跑。')

display(pd.DataFrame([{
    **QWEN27_REUSE500_RUN,
    'reused_sample_range': '1-500',
    'new_sample_range': '501-1038',
    'new_sample_count': len(qwen27_tail_samples),
}]))

def _prf_from_counts(tp: int, fp: int, fn: int) -> dict[str, float]:
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return {'precision': precision, 'recall': recall, 'f1': f1}

if not RUN_QWEN27_REUSE500_TAIL:
    LOGGER.warning('Qwen 27B 复用前 500 条的正式续跑未启动。')
else:
    QWEN27_REUSE500_TAIL_RESULTS = run_formal_batch(
        [QWEN27_REUSE500_RUN],
        existing_retrievers={
            QWEN27_REUSE500_RUN['run_id']: QWEN_RAG3_RETRIEVER,
        },
        samples_override=qwen27_tail_samples,
        require_all_smoke=False,
    )
    qwen27_tail_row = QWEN27_REUSE500_TAIL_RESULTS[0]
    if qwen27_tail_row['status'] != 'completed' or bool(qwen27_tail_row['cache_prompt']):
        raise RuntimeError('Qwen 27B 后 538 条未在 cache_prompt=False 下成功完成。')

    missing_count_fields = sorted(set(QWEN27_PREFIX500_COUNTS) - set(qwen27_tail_row))
    if missing_count_fields:
        raise RuntimeError(f'续跑结果缺少原始计数字段：{missing_count_fields}')
    qwen27_combined_counts = {
        key: int(prefix_value) + int(qwen27_tail_row[key])
        for key, prefix_value in QWEN27_PREFIX500_COUNTS.items()
    }
    if qwen27_combined_counts['n_samples'] != len(qwen27_all_test_samples):
        raise RuntimeError('合并后的样本总数不等于完整 test。')
    if qwen27_combined_counts['n_causal_gold'] != sum(
        bool(sample['has_causal']) for sample in qwen27_all_test_samples
    ):
        raise RuntimeError('合并后的 gold causal 总数不一致。')
    if qwen27_combined_counts['all_n_gold_triples'] != sum(
        len(sample['relations']) for sample in qwen27_all_test_samples
    ):
        raise RuntimeError('合并后的 gold triple 总数不一致。')
    if qwen27_combined_counts['detected_n_eval_samples'] != qwen27_combined_counts['detection_tp']:
        raise RuntimeError('合并后的 detected_only 样本数与 Detection TP 不一致。')

    qwen27_detection = _prf_from_counts(
        qwen27_combined_counts['detection_tp'],
        qwen27_combined_counts['detection_fp'],
        qwen27_combined_counts['detection_fn'],
    )
    qwen27_strict_all = _prf_from_counts(
        qwen27_combined_counts['strict_all_tp'],
        qwen27_combined_counts['strict_all_fp'],
        qwen27_combined_counts['strict_all_fn'],
    )
    qwen27_anchor_all = _prf_from_counts(
        qwen27_combined_counts['anchor_all_tp'],
        qwen27_combined_counts['anchor_all_fp'],
        qwen27_combined_counts['anchor_all_fn'],
    )
    qwen27_strict_detected = _prf_from_counts(
        qwen27_combined_counts['strict_detected_tp'],
        qwen27_combined_counts['strict_detected_fp'],
        qwen27_combined_counts['strict_detected_fn'],
    )
    qwen27_anchor_detected = _prf_from_counts(
        qwen27_combined_counts['anchor_detected_tp'],
        qwen27_combined_counts['anchor_detected_fp'],
        qwen27_combined_counts['anchor_detected_fn'],
    )

    qwen27_combined_row = {
        'status': 'completed_composite',
        'model': QWEN27_REUSE500_RUN['display_name'],
        'model_key': QWEN27_REUSE500_RUN['model_key'],
        'prompt': QWEN27_REUSE500_RUN['prompt_name'],
        'rag': f"{QWEN27_REUSE500_RUN['rag_mode']}-k{QWEN27_REUSE500_RUN['rag_top_k']}",
        'temperature': TEMPERATURE,
        'context_length': int(QWEN27_REUSE500_RUN.get('context_length', CONTEXT_LENGTH)),
        'max_tokens': MAX_TOKENS,
        'parallel': QWEN27_REUSE500_RUN.get('parallel', 'model_default'),
        'reload_every_samples': 100,
        'cache_prompt': 'default samples 1-500; false samples 501-1038',
        'reused_prefix_samples': 500,
        'new_tail_samples': len(qwen27_tail_samples),
        'detection_accuracy': (
            qwen27_combined_counts['detection_tp'] + qwen27_combined_counts['detection_tn']
        ) / qwen27_combined_counts['n_samples'],
        'detection_precision': qwen27_detection['precision'],
        'detection_recall': qwen27_detection['recall'],
        'detection_f1': qwen27_detection['f1'],
        'strict_all_precision': qwen27_strict_all['precision'],
        'strict_all_recall': qwen27_strict_all['recall'],
        'strict_all_f1': qwen27_strict_all['f1'],
        'anchor_all_precision': qwen27_anchor_all['precision'],
        'anchor_all_recall': qwen27_anchor_all['recall'],
        'anchor_all_f1': qwen27_anchor_all['f1'],
        'strict_detected_only_precision': qwen27_strict_detected['precision'],
        'strict_detected_only_recall': qwen27_strict_detected['recall'],
        'strict_detected_only_f1': qwen27_strict_detected['f1'],
        'anchor_detected_only_precision': qwen27_anchor_detected['precision'],
        'anchor_detected_only_recall': qwen27_anchor_detected['recall'],
        'anchor_detected_only_f1': qwen27_anchor_detected['f1'],
        **qwen27_combined_counts,
        'prefix_evidence': 'notebook progress 500/1038 at 2026-08-27 13:29:50',
        'tail_report_path': qwen27_tail_row.get('report_path', ''),
    }
    qwen27_combined_df = pd.DataFrame([qwen27_combined_row])
    QWEN27_REUSE500_SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    qwen27_combined_df.to_csv(
        QWEN27_REUSE500_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info('Qwen 27B 复用前 500 条的完整 test summary 已保存：%s', QWEN27_REUSE500_SUMMARY_PATH)
    display(qwen27_combined_df[[
        'model',
        'detection_precision', 'detection_recall', 'detection_f1',
        'strict_all_precision', 'strict_all_recall', 'strict_all_f1',
        'anchor_all_precision', 'anchor_all_recall', 'anchor_all_f1',
        'strict_detected_only_f1', 'anchor_detected_only_f1',
    ]])