# CNC RAG 消融实验：Phase 2（Qwen3.6 27B No Thinking）

本 notebook 使用 `local/qwen3.6-27b-no-thinking`，在固定 `cnc_sft_validation`（500 条）上复现与 Gemma 31B 相同的 Phase 2 消融配置，以独立确定 Qwen 的 k 值。

| 配置 | k | 动态示例 | 总示例 |
|---|---:|---:|---:|
| fixed | 0 | 0 | 10 |
| RAG only | 1 / 3 / 5 | 2k | 2 / 6 / 10 |
| fixed + random | 1 / 3 / 5 | 2k | 12 / 16 / 20 |
| fixed + RAG | 1 / 3 / 5 | 2k | 12 / 16 / 20 |

`2k` 来自 Pattern top-k + KNN top-k。若两路结果重叠，检索器会从后续候选补足，确保与 random 的数量严格一致。

RAG 与 random 使用同一份 600 条 train-only CNC support；它与 validation/test 均无 ID 重叠。该 support 全部为正因果样本，而 fixed 10 examples 包含 5 正、5 负，因此 RAG-only 与 fixed 的数量在 k=5 时匹配，但类别构成不同。

模型只加载一次，10 个配置依次运行，最后自动卸载。每完成一个配置都会保存独立 Markdown 报告并增量更新汇总 CSV。

In [1]:
# ===== 全局配置 =====
import json
import logging
import sys
from collections.abc import Iterable, Iterator
from html import escape
from pathlib import Path
from typing import Any

import pandas as pd
from IPython.display import HTML, display

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == 'notebooks':
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

if 'master_thesis' not in sys.executable.lower():
    raise RuntimeError('请切换到 Master_thesis kernel，重启 kernel 后从第一格重新运行。')

from src.data_io import load_dataset
from src.eval_pipeline import EvalRunConfig, run_stream_eval
from src.llm_client import LLMClient
from src.prompt_builder import build_messages, load_prompt_template
from src.retriever import (
    DeterministicRandomRetriever,
    ExactCountHybridRetriever,
    KNNRetriever,
    PatternRetriever,
    load_examples_from_jsonl,
    resolve_rag_cache_paths,
)

logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')
LOGGER = logging.getLogger('lmstudio_rag_ablation_phase2_qwen27')
logging.getLogger('src.llm_client').setLevel(logging.WARNING)


def _notebook_progress(
    iterable: Iterable[Any],
    *,
    total: int,
    desc: str,
) -> Iterator[Any]:
    safe_desc = escape(desc)
    safe_total = max(total, 1)

    def render(completed: int) -> HTML:
        percent = min(completed / safe_total * 100, 100.0)
        return HTML(
            f"<div style='width:100%'>"
            f"<div>{safe_desc}: {completed}/{total} ({percent:.1f}%)</div>"
            f"<progress value='{completed}' max='{safe_total}' "
            f"style='width:100%;height:18px'></progress></div>"
        )

    handle = display(render(0), display_id=True)
    for completed, item in enumerate(iterable, 1):
        yield item
        if handle is not None:
            handle.update(render(completed))


LMSTUDIO_BASE_URL = 'http://127.0.0.1:1234/v1'
LMSTUDIO_API_KEY = 'lm-studio'
MODEL_KEY = 'local/qwen3.6-27b-no-thinking'
MODEL_DISPLAY_NAME = 'Qwen3.6 27B No Thinking'
MODEL_LOAD_TIMEOUT = 1200
LLM_TIMEOUT = 600
LLM_RETRY_TIMES = 3
CONTEXT_LENGTH = 8192
MODEL_PARALLEL = 1
OFFLOAD_KV_CACHE_TO_GPU = True
MAX_TOKENS = 2048
TEMPERATURE = 0.0

DATASET_NAME = 'cnc_sft_validation'
EVAL_SAMPLE_N = None  # None = 完整 validation 500 条。
EVAL_PROGRESS_EVERY = 500
EVAL_MAX_WORKERS = 1
K_VALUES = (1, 3, 5)
RANDOM_SEED = 42
FIXED_PROMPT = 'v9.6'
ZERO_SHOT_PROMPT = 'v9.6_zero_shot'
REPORT_DIR = Path('results') / 'eval_report' / 'rag_ablation' / 'phase2_qwen27'
RUN_PHASE2 = False  # 原始十组已完成；补跑只使用 notebook 末尾的专用开关。

EXPERIMENT_RUNS: list[dict[str, Any]] = [
    {
        'run_id': 'fixed',
        'configuration': 'fixed',
        'k': 0,
        'prompt_name': FIXED_PROMPT,
        'retriever_kind': 'none',
        'rag_mode': 'off',
        'dynamic_examples': 0,
        'total_examples': 10,
    },
]
for k in K_VALUES:
    EXPERIMENT_RUNS.append({
        'run_id': f'rag_only_k{k}',
        'configuration': 'RAG only',
        'k': k,
        'prompt_name': ZERO_SHOT_PROMPT,
        'retriever_kind': 'rag',
        'rag_mode': 'knn_pattern',
        'dynamic_examples': 2 * k,
        'total_examples': 2 * k,
    })
for k in K_VALUES:
    EXPERIMENT_RUNS.append({
        'run_id': f'fixed_random_k{k}',
        'configuration': 'fixed + random',
        'k': k,
        'prompt_name': FIXED_PROMPT,
        'retriever_kind': 'random',
        'rag_mode': 'random',
        'dynamic_examples': 2 * k,
        'total_examples': 10 + 2 * k,
    })
for k in K_VALUES:
    EXPERIMENT_RUNS.append({
        'run_id': f'fixed_rag_k{k}',
        'configuration': 'fixed + RAG',
        'k': k,
        'prompt_name': FIXED_PROMPT,
        'retriever_kind': 'rag',
        'rag_mode': 'knn_pattern',
        'dynamic_examples': 2 * k,
        'total_examples': 10 + 2 * k,
    })

display(pd.DataFrame(EXPERIMENT_RUNS))

,run_id,configuration,k,prompt_name,retriever_kind,rag_mode,dynamic_examples,total_examples
0,fixed,fixed,0,v9.6,none,off,0,10
1,rag_only_k1,RAG only,1,v9.6_zero_shot,rag,knn_pattern,2,2
2,rag_only_k3,RAG only,3,v9.6_zero_shot,rag,knn_pattern,6,6
3,rag_only_k5,RAG only,5,v9.6_zero_shot,rag,knn_pattern,10,10
4,fixed_random_k1,fixed + random,1,v9.6,random,random,2,12
5,fixed_random_k3,fixed + random,3,v9.6,random,random,6,16
6,fixed_random_k5,fixed + random,5,v9.6,random,random,10,20
7,fixed_rag_k1,fixed + RAG,1,v9.6,rag,knn_pattern,2,12
8,fixed_rag_k3,fixed + RAG,3,v9.6,rag,knn_pattern,6,16
9,fixed_rag_k5,fixed + RAG,5,v9.6,rag,knn_pattern,10,20

In [2]:
# ===== 模型、数据隔离、prompt 与 2k 数量预检（不加载 LLM） =====
manager = LLMClient(
    provider='lmstudio',
    base_url=LMSTUDIO_BASE_URL,
    model=MODEL_KEY,
    api_key=LMSTUDIO_API_KEY,
    temperature=TEMPERATURE,
    max_tokens=MAX_TOKENS,
    context_length=CONTEXT_LENGTH,
    reasoning='off',
    timeout=MODEL_LOAD_TIMEOUT,
    retry_times=LLM_RETRY_TIMES,
)

inventory_by_key = {
    str(item['key']): item
    for item in manager.list_local_models()
    if item.get('key')
}
if MODEL_KEY not in inventory_by_key:
    raise RuntimeError(f'LM Studio 中找不到目标模型：{MODEL_KEY}')
model_item = inventory_by_key[MODEL_KEY]
reasoning_default = model_item.get('capabilities', {}).get('reasoning', {}).get('default')
if reasoning_default != 'off':
    raise RuntimeError(f'{MODEL_KEY} 的 Enable Thinking 默认值不是 off：{reasoning_default}')
display(pd.DataFrame([{
    'model': MODEL_DISPLAY_NAME,
    'model_key': MODEL_KEY,
    'quantization': model_item.get('quantization', {}).get('name'),
    'params': model_item.get('params_string'),
    'reasoning_default': reasoning_default,
    'loaded_instances': len(model_item.get('loaded_instances', [])),
}]))

validation_samples = load_dataset(DATASET_NAME, n=EVAL_SAMPLE_N)
validation_ids = {str(sample['id']) for sample in validation_samples}
metadata_path, embeddings_path = resolve_rag_cache_paths('cnc')
support_examples = load_examples_from_jsonl(metadata_path)
support_ids = {str(example['sample_id']) for example in support_examples}
overlap = validation_ids.intersection(support_ids)
if overlap:
    raise RuntimeError(f'CNC RAG support 与 validation 有 {len(overlap)} 个精确 ID 重叠。')
if any(not example.get('triples') for example in support_examples):
    raise RuntimeError('CNC RAG support 中存在没有 causal triples 的样本。')

manifest = json.loads(
    (PROJECT_ROOT / 'RAG Database/cnc_split_manifest.json').read_text(encoding='utf-8')
)
if not manifest.get('train_only_support'):
    raise RuntimeError('CNC RAG manifest 未声明 train_only_support。')
if int(manifest.get('summary', {}).get('validation_sample_overlap', -1)) != 0:
    raise RuntimeError('CNC RAG manifest 显示 validation overlap 非零。')

fixed_template = load_prompt_template(FIXED_PROMPT)
zero_template = load_prompt_template(ZERO_SHOT_PROMPT)
if fixed_template.count('\nInput:\n') != 10:
    raise RuntimeError('v9.6 fixed prompt 不包含恰好 10 个 fixed examples。')
if zero_template.count('\nInput:\n') != 0:
    raise RuntimeError('v9.6 zero-shot prompt 仍包含 fixed examples。')
if fixed_template.count('{rag_examples}') != 1:
    raise RuntimeError('v9.6 必须包含且只包含一个 {rag_examples} 占位符。')
if zero_template.count('{rag_examples}') != 1:
    raise RuntimeError('v9.6 zero-shot prompt 必须包含且只包含一个 {rag_examples} 占位符。')

RAG_RETRIEVER = ExactCountHybridRetriever(
    pattern_retriever=PatternRetriever(metadata_path=metadata_path),
    knn_retriever=KNNRetriever(
        metadata_path=metadata_path,
        embeddings_path=embeddings_path,
        device='cpu',
    ),
)
RANDOM_RETRIEVER = DeterministicRandomRetriever(
    metadata_path=metadata_path,
    seed=RANDOM_SEED,
)

audit_text = 'Heavy rain caused flooding in the region.'
count_rows: list[dict[str, Any]] = []
for k in K_VALUES:
    rag_examples = RAG_RETRIEVER.retrieve(audit_text, top_k=k)
    random_examples = RANDOM_RETRIEVER.retrieve(audit_text, top_k=k)
    count_rows.append({
        'k': k,
        'expected_each': 2 * k,
        'rag_examples': len(rag_examples),
        'random_examples': len(random_examples),
    })
    for retriever_kind, retriever, rag_mode in (
        ('rag', RAG_RETRIEVER, 'knn_pattern'),
        ('random', RANDOM_RETRIEVER, 'random'),
    ):
        messages = build_messages(
            audit_text,
            use_rag=True,
            retriever=retriever,
            top_k=k,
            rag_mode=rag_mode,
            prompt_name=FIXED_PROMPT,
        )
        system_prompt = messages[0]['content']
        inserted_examples = system_prompt.count('\nExample ')
        if inserted_examples != 2 * k or '{rag_examples}' in system_prompt:
            raise RuntimeError(
                f'v9.6 动态示例注入失败：{retriever_kind=} {k=} '
                f'expected={2 * k} actual={inserted_examples}'
            )
display(pd.DataFrame(count_rows))
LOGGER.info(
    '预检通过：validation=%s support=%s overlap=0 fixed=10 zero-shot=0；RAG/random 均严格返回 2k。',
    len(validation_samples),
    len(support_examples),
)

,model,model_key,quantization,params,reasoning_default,loaded_instances
0,Qwen3.6 27B No Thinking,local/qwen3.6-27b-no-thinking,Q4_K_M,27B,off,0

2026-08-27 00:40:13,808 | INFO | Pattern examples 已加载：path=D:\Master thesis\RAG Database\cnc_examples.jsonl examples=600
2026-08-27 00:40:13,820 | INFO | KNN cache 已加载：examples=600 path=D:\Master thesis\RAG Database\cnc_examples.jsonl embedding_device=cpu
D:\Anaconda3\envs\Master_thesis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-27 00:40:24,890 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:24,938 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-27 00:40:25,092 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:25,143 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-27 00:40:25,149 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-08-27 00:40:25,327 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:25,357 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-27 00:40:25,519 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:25,570 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-08-27 00:40:25,721 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:25,749 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-08-27 00:40:25,913 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:25,961 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-27 00:40:26,116 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-27 00:40:26,271 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:26,321 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 7075.00it/s]
2026-08-27 00:40:26,637 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-08-27 00:40:26,800 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-27 00:40:26,956 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-27 00:40:27,109 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-08-27 00:40:27,262 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:27,312 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-27 00:40:27,467 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:27,496 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-27 00:40:27,652 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:27,680 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-08-27 00:40:27,837 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:27,865 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-27 00:40:28,026 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-27 00:40:28,181 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-27 00:40:28,389 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 00:40:28,476 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-27 00:40:28,687 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"

   k  expected_each  rag_examples  random_examples
0  1              2             2                2
1  3              6             6                6
2  5             10            10               10

2026-08-27 00:40:28,969 | INFO | 预检通过：validation=500 support=600 overlap=0 fixed=10 zero-shot=0；RAG/random 均严格返回 2k。

In [3]:
# ===== Phase 2 评测辅助函数 =====
SUMMARY_PATH = PROJECT_ROOT / REPORT_DIR / 'phase2_qwen27_summary.csv'


def _retriever_for_run(run: dict[str, Any]) -> Any:
    if run['retriever_kind'] == 'none':
        return None
    if run['retriever_kind'] == 'random':
        return RANDOM_RETRIEVER
    if run['retriever_kind'] == 'rag':
        return RAG_RETRIEVER
    raise ValueError(f"未知 retriever_kind：{run['retriever_kind']}")


def _summary_row(
    run: dict[str, Any],
    report: dict[str, Any],
    *,
    context_length: int = CONTEXT_LENGTH,
    parallel: int = MODEL_PARALLEL,
) -> dict[str, Any]:
    detection = report['detection']
    strict = report['extraction']['strict_token_f1']
    anchor = report['extraction']['anchor_window']
    return {
        'status': 'completed',
        'run_id': run['run_id'],
        'configuration': run['configuration'],
        'k': run['k'],
        'dynamic_examples': run['dynamic_examples'],
        'total_examples': run['total_examples'],
        'split': 'validation',
        'model': MODEL_DISPLAY_NAME,
        'model_key': MODEL_KEY,
        'prompt': run['prompt_name'],
        'rag_mode': run['rag_mode'],
        'random_seed': RANDOM_SEED if run['retriever_kind'] == 'random' else '',
        'temperature': TEMPERATURE,
        'context_length': context_length,
        'max_tokens': MAX_TOKENS,
        'parallel': parallel,
        'offload_kv_cache_to_gpu': OFFLOAD_KV_CACHE_TO_GPU,
        'reasoning': 'model_default_off',
        'detection_accuracy': detection['accuracy'],
        'detection_precision': detection['precision'],
        'detection_recall': detection['recall'],
        'detection_f1': detection['f1'],
        'strict_all_precision': strict['all_samples']['precision'],
        'strict_all_recall': strict['all_samples']['recall'],
        'strict_all_f1': strict['all_samples']['f1'],
        'anchor_all_precision': anchor['all_samples']['precision'],
        'anchor_all_recall': anchor['all_samples']['recall'],
        'anchor_all_f1': anchor['all_samples']['f1'],
        'strict_detected_only_f1': strict['detected_only']['f1'],
        'anchor_detected_only_f1': anchor['detected_only']['f1'],
        'report_path': report.get('report_path', ''),
        'error': '',
    }


def _save_summary(
    rows: list[dict[str, Any]],
    summary_path: Path = SUMMARY_PATH,
) -> None:
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(summary_path, index=False, encoding='utf-8-sig')
    LOGGER.info('Phase 2 增量汇总已保存：%s', summary_path)


def run_phase2(
    experiment_runs: list[dict[str, Any]],
    *,
    summary_path: Path = SUMMARY_PATH,
    context_length: int = CONTEXT_LENGTH,
    parallel: int = MODEL_PARALLEL,
) -> list[dict[str, Any]]:
    samples = load_dataset(DATASET_NAME, n=EVAL_SAMPLE_N)
    rows: list[dict[str, Any]] = []
    manager.unload_all_models()
    load_result = manager.load_model(
        MODEL_KEY,
        context_length=context_length,
        parallel=parallel,
        offload_kv_cache_to_gpu=OFFLOAD_KV_CACHE_TO_GPU,
    )
    load_config = load_result.get('load_config', {})
    actual_context = int(load_config.get('context_length', 0))
    actual_parallel = int(load_config.get('parallel', 0))
    actual_kv_cache_gpu = load_config.get('offload_kv_cache_to_gpu') is True
    if (
        actual_context != context_length
        or actual_parallel != parallel
        or actual_kv_cache_gpu != OFFLOAD_KV_CACHE_TO_GPU
    ):
        manager.unload_all_models()
        raise RuntimeError(
            '模型实际加载配置与目标不一致：'
            f'context={actual_context}/{context_length}, '
            f'parallel={actual_parallel}/{parallel}, '
            f'kv_cache_gpu={actual_kv_cache_gpu}/{OFFLOAD_KV_CACHE_TO_GPU}。'
        )
    instance_id = str(load_result['instance_id'])
    loaded_instance = next(
        (
            instance
            for model_item in manager.list_local_models()
            if model_item.get('key') == MODEL_KEY
            for instance in model_item.get('loaded_instances', [])
            if isinstance(instance, dict) and instance.get('id') == instance_id
        ),
        None,
    )
    inventory_config = (
        loaded_instance.get('config', {})
        if isinstance(loaded_instance, dict)
        else {}
    )
    inventory_context = int(inventory_config.get('context_length', 0))
    inventory_parallel = int(inventory_config.get('parallel', 0))
    if inventory_context != context_length or inventory_parallel != parallel:
        manager.unload_all_models()
        raise RuntimeError(
            'LM Studio inventory 中的实例配置与目标不一致：'
            f'context={inventory_context}/{context_length}, '
            f'parallel={inventory_parallel}/{parallel}。'
        )
    LOGGER.info(
        'LM Studio 实例已确认：id=%s context=%s parallel=%s',
        instance_id,
        inventory_context,
        inventory_parallel,
    )
    client = LLMClient(
        provider='lmstudio',
        base_url=LMSTUDIO_BASE_URL,
        model=instance_id,
        api_key=LMSTUDIO_API_KEY,
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
        context_length=context_length,
        timeout=LLM_TIMEOUT,
        retry_times=LLM_RETRY_TIMES,
    )

    try:
        for position, run in enumerate(experiment_runs, 1):
            LOGGER.info(
                '[Phase 2 %s/%s] 开始 %s',
                position,
                len(experiment_runs),
                run['run_id'],
            )
            try:
                use_rag = run['retriever_kind'] != 'none'
                retriever = _retriever_for_run(run)
                eval_config = EvalRunConfig(
                    project_root=PROJECT_ROOT,
                    model=instance_id,
                    dataset=DATASET_NAME,
                    prompt_name=str(run['prompt_name']),
                    use_rag=use_rag,
                    rag_mode=str(run['rag_mode']),
                    rag_top_k=int(run['k']),
                    temperature=TEMPERATURE,
                    max_tokens=MAX_TOKENS,
                    primary_metric='strict_token_f1',
                    progress_every=EVAL_PROGRESS_EVERY,
                    max_workers=EVAL_MAX_WORKERS,
                    llm_provider='lmstudio',
                    llm_base_url=LMSTUDIO_BASE_URL,
                    context_length=context_length,
                    reasoning_effort=None,
                    llm_extra_body=None,
                    api_key_source='lmstudio-default',
                    save_report=True,
                    report_dir=REPORT_DIR,
                    report_detail_limit=200,
                    report_detail_mode='errors',
                    report_error_metric='strict_token_f1',
                    metadata_path=metadata_path if use_rag else None,
                    embeddings_path=(
                        embeddings_path if run['retriever_kind'] == 'rag' else None
                    ),
                )
                report = run_stream_eval(
                    samples=samples,
                    label=f"{MODEL_DISPLAY_NAME} CNC validation {run['run_id']}",
                    client=client,
                    config=eval_config,
                    existing_retriever=retriever,
                    progress_factory=_notebook_progress,
                    emit=LOGGER.info,
                )
                rows.append(
                    _summary_row(
                        run,
                        report,
                        context_length=context_length,
                        parallel=parallel,
                    )
                )
            except Exception as exc:
                LOGGER.exception('[Phase 2 %s/%s] %s 失败', position, len(experiment_runs), run['run_id'])
                rows.append({
                    'status': 'failed',
                    'run_id': run['run_id'],
                    'configuration': run['configuration'],
                    'k': run['k'],
                    'dynamic_examples': run['dynamic_examples'],
                    'total_examples': run['total_examples'],
                    'split': 'validation',
                    'model': MODEL_DISPLAY_NAME,
                    'model_key': MODEL_KEY,
                    'prompt': run['prompt_name'],
                    'rag_mode': run['rag_mode'],
                    'error': f'{type(exc).__name__}: {exc}',
                })
            _save_summary(rows, summary_path)
    finally:
        manager.unload_all_models()
    return rows

In [ ]:
# ===== 运行 Phase 2：Qwen3.6 27B 的 10 个消融配置 =====
if not RUN_PHASE2:
    LOGGER.warning('Phase 2 未启动。确认预检结果后，将 RUN_PHASE2 改为 True。')
else:
    PHASE2_RESULTS = run_phase2(EXPERIMENT_RUNS)
    phase2_summary_df = pd.DataFrame(PHASE2_RESULTS)
    display(phase2_summary_df)

## 修正后补跑：仅重跑六组 fixed + dynamic 配置

原始 `v9.6` 缺少 `{rag_examples}` 占位符，导致先前的 `fixed + random` 与 `fixed + RAG` 没有真正注入动态示例。修正 prompt 后，本节仅补跑受影响的六组；`fixed` 与三组 `RAG only` 结果仍然有效，不重复运行。补跑汇总单独保存，不覆盖原始十组汇总。

In [4]:
# ===== 修正后补跑配置：只包含六组受占位符问题影响的实验 =====
RERUN_RUN_IDS = (
    'fixed_random_k1',
    'fixed_random_k3',
    'fixed_random_k5',
    'fixed_rag_k1',
    'fixed_rag_k3',
    'fixed_rag_k5',
)
RERUN_SUMMARY_PATH = (
    PROJECT_ROOT / REPORT_DIR / 'phase2_qwen27_rerun_summary.csv'
)
CORRECTED_SUMMARY_PATH = (
    PROJECT_ROOT / REPORT_DIR / 'phase2_qwen27_corrected_summary.csv'
)
VALID_ORIGINAL_RUN_IDS = ('fixed', 'rag_only_k1', 'rag_only_k3', 'rag_only_k5')
RUN_PHASE2_RERUN = False  # 前五组已完成；不要再次运行原六组入口。

runs_by_id = {run['run_id']: run for run in EXPERIMENT_RUNS}
RERUN_EXPERIMENT_RUNS = [runs_by_id[run_id] for run_id in RERUN_RUN_IDS]
if len(RERUN_EXPERIMENT_RUNS) != 6:
    raise RuntimeError('补跑配置必须恰好包含六组。')
if any(run['retriever_kind'] == 'none' for run in RERUN_EXPERIMENT_RUNS):
    raise RuntimeError('补跑中不应包含 fixed 或 RAG-only 基线。')
if load_prompt_template(FIXED_PROMPT).count('{rag_examples}') != 1:
    raise RuntimeError('v9.6 的 {rag_examples} 占位符修正尚未生效。')

display(pd.DataFrame(RERUN_EXPERIMENT_RUNS))
print(f'补跑汇总将保存到：{RERUN_SUMMARY_PATH}')
print(f'修正版完整汇总将保存到：{CORRECTED_SUMMARY_PATH}')

,run_id,configuration,k,prompt_name,retriever_kind,rag_mode,dynamic_examples,total_examples
0,fixed_random_k1,fixed + random,1,v9.6,random,random,2,12
1,fixed_random_k3,fixed + random,3,v9.6,random,random,6,16
2,fixed_random_k5,fixed + random,5,v9.6,random,random,10,20
3,fixed_rag_k1,fixed + RAG,1,v9.6,rag,knn_pattern,2,12
4,fixed_rag_k3,fixed + RAG,3,v9.6,rag,knn_pattern,6,16
5,fixed_rag_k5,fixed + RAG,5,v9.6,rag,knn_pattern,10,20

补跑汇总将保存到：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
修正版完整汇总将保存到：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_corrected_summary.csv

In [5]:
# ===== 执行修正后的六组补跑 =====
if not RUN_PHASE2_RERUN:
    LOGGER.warning('补跑未启动。确认配置后，将 RUN_PHASE2_RERUN 改为 True。')
else:
    PHASE2_RERUN_RESULTS = run_phase2(
        RERUN_EXPERIMENT_RUNS,
        summary_path=RERUN_SUMMARY_PATH,
    )
    phase2_rerun_summary_df = pd.DataFrame(PHASE2_RERUN_RESULTS)
    display(phase2_rerun_summary_df)

    original_summary_df = pd.read_csv(SUMMARY_PATH)
    valid_original_df = original_summary_df[
        original_summary_df['run_id'].isin(VALID_ORIGINAL_RUN_IDS)
    ].copy()
    if set(valid_original_df['run_id']) != set(VALID_ORIGINAL_RUN_IDS):
        raise RuntimeError('原始汇总中缺少 fixed 或 RAG-only 有效结果，无法合并。')
    corrected_summary_df = pd.concat(
        [valid_original_df, phase2_rerun_summary_df],
        ignore_index=True,
    )
    run_order = [run['run_id'] for run in EXPERIMENT_RUNS]
    corrected_summary_df['_run_order'] = pd.Categorical(
        corrected_summary_df['run_id'],
        categories=run_order,
        ordered=True,
    )
    corrected_summary_df = (
        corrected_summary_df.sort_values('_run_order')
        .drop(columns='_run_order')
        .reset_index(drop=True)
    )
    CORRECTED_SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    corrected_summary_df.to_csv(
        CORRECTED_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info('修正版完整十组汇总已保存：%s', CORRECTED_SUMMARY_PATH)
    display(corrected_summary_df)

2026-08-27 00:40:59,603 | INFO | [Phase 2 1/6] 开始 fixed_random_k1

2026-08-27 00:41:01,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:04,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:07,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:07,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:08,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:10,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:13,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:13,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:14,571 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:15,246 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:17,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:18,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:19,439 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:20,076 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:20,848 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:21,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:22,348 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:22,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:23,624 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:24,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:24,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:25,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:28,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:29,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:29,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:32,293 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:33,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:35,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:40,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:40,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:43,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:43,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:46,677 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:47,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:48,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:49,449 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:52,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:52,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:55,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:56,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:56,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:57,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:41:59,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:00,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:00,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:03,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:05,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:08,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:10,682 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:11,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:14,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:16,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:17,293 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:17,927 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:18,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:22,258 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:25,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:25,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:27,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:28,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:33,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:33,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:34,552 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:35,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:35,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:38,277 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:38,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:39,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:40,355 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:40,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:42,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:43,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:45,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:48,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:42:50,718 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:53,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:55,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:42:59,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:01,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:02,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:02,936 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:03,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:04,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:10,950 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:13,214 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:16,006 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:21,095 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:21,743 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:24,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:27,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:30,869 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:33,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:34,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:34,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:38,770 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:42,578 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:45,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:46,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:47,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:47,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:48,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:49,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:49,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:50,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:51,047 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:54,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:56,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:59,156 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:43:59,772 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:02,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:02,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:05,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:05,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:06,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:06,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:09,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:14,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:16,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:16,586 | WARNING | 生成失败：sample_id=2007 attempt=1/2 error=未找到 JSON 对象
2026-08-27 00:44:18,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:18,307 | WARNING | 生成失败：sample_id=2007 attempt=2/2 error=未找到 JSON 对象
2026-08-27 00:44:18,308 | ERROR | 生成兜底：sample_id=2007 error=未找到 JSON 对象
2026-08-27 00:44:18,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:19,796 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:20,595 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:24,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:25,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:25,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:28,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:34,031 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:36,973 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:37,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:38,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:40,189 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:40,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:41,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:46,388 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:48,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:52,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:53,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:44:56,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:00,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:00,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:01,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:02,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:03,354 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:04,105 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:07,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:45:09,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:10,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:10,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:13,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:16,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:16,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:17,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:20,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:23,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:23,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:26,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:29,002 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:31,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:34,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:38,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:38,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:43,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:46,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:47,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:49,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:50,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:52,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:53,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:53,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:54,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:55,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:55,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:56,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:57,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:45:58,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:00,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:03,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:04,076 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:04,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:07,020 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:07,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:10,745 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:13,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:14,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:16,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:17,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:18,123 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:20,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:23,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:24,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:28,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:28,820 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:29,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:32,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:32,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:33,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:34,076 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:34,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:35,406 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:38,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:40,621 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:41,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:43,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:44,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:45,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:46,037 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:47,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:54,650 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:55,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:57,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:46:59,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:00,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:01,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:02,107 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:04,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:05,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:08,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:09,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:10,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:47:12,772 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:14,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:17,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:18,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:19,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:19,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:20,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:21,064 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:21,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:22,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:24,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:29,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:31,739 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:34,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:34,802 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:35,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:36,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:37,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:38,624 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:41,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:43,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:46,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:48,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:49,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:52,296 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:52,997 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:55,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:47:58,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:00,646 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:03,235 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:05,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:07,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:12,322 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:13,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:13,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:14,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:16,979 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:17,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:20,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:22,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:25,245 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:25,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:26,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:28,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:29,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:30,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:30,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:31,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:33,691 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:36,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:39,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:41,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:41,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:44,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:47,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:49,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:50,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:50,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:51,678 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:52,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:52,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:55,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:58,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:48:58,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:03,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:05,624 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:06,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:06,987 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:07,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:11,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:11,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:15,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:15,736 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:18,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:49:20,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:25,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:26,124 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:29,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:29,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:31,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:33,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:36,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:38,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:39,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:40,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:42,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:45,436 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:47,680 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:50,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:50,951 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:51,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:52,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:52,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:53,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:56,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:49:57,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:00,281 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:00,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:01,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:02,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:02,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:03,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:04,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:06,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:07,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:10,654 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:11,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:12,005 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:12,608 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:15,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:15,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:18,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:20,886 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:21,501 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:22,086 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:22,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:23,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:23,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:26,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:27,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:27,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:30,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:33,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:35,956 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:38,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:38,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:39,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:40,202 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:40,821 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:41,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:44,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:45,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:48,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:50,740 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:53,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:54,160 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:57,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:50:59,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:00,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:04,743 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:08,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:09,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:11,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:14,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:17,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:19,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:20,206 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:20,821 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:51:25,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:26,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:28,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:31,202 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:31,800 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:32,384 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:34,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:35,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:35,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:36,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:37,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:37,798 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:38,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:39,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:39,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:42,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:43,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:44,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:44,925 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:47,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:48,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:48,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:49,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:50,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:52,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:55,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:56,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:59,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:51:59,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:00,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:03,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:03,738 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:06,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:10,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:13,181 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:18,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:19,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:20,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:20,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:21,552 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:22,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:22,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:25,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:27,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:30,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:32,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:33,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:36,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:39,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:39,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:43,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:46,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:46,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:49,035 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:52,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:54,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:55,601 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:56,246 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:56,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:59,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:52:59,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:00,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:03,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:04,313 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:04,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:07,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:08,590 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:09,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:09,947 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:10,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:11,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:13,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:14,344 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:18,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:53:19,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:19,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:23,493 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:24,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:26,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:29,394 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:30,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:30,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:31,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:32,223 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:32,807 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:35,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:37,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:41,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:41,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:42,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:44,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:45,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:46,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:48,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:49,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:51,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:52,147 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:52,738 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:55,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:58,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:59,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:53:59,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:04,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:05,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:06,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:06,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:07,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:07,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:10,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:13,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:15,830 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:16,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:18,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:21,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:21,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:22,277 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:23,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:25,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:28,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:30,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:31,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:34,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:35,228 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:38,522 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:39,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:41,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:44,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:44,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:45,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:49,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:51,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:54,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:54,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:55,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:55,474 | INFO |
2026-08-27 00:54:55,474 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k1 progress 500/500 ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 227
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.830
  Precision: 0.894
  Recall   : 0.769
  F1       : 0.827
  (TP=203, TN=212, FP=24, FN=61)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 257
    Precision: 0.572
    Recall   : 0.402
    F1       : 0.472
    (TP=147, FP=110, FN=219)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 257
    Precision: 0.580
    Recall   : 0.407
    F1       : 0.478
    (TP=149, FP=108, FN=217)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 203
    Gold triples: 298 | Pred triples: 226
    Precision: 0.650
    Recall   : 0.493
    F1       : 0.561
    (TP=147, FP=79, FN=151)
  [anchor_window]
    样本数: 203
    Gold triples: 298 | Pred triples: 226
    Precision: 0.659
    Recall   : 0.500
    F1       : 0.569
    (TP=149, FP=77, FN=149)
================================================
2026-08-27 00:54:55,476 | INFO |
2026-08-27 00:54:55,477 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k1 final report ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 227
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.830
  Precision: 0.894
  Recall   : 0.769
  F1       : 0.827
  (TP=203, TN=212, FP=24, FN=61)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 257
    Precision: 0.572
    Recall   : 0.402
    F1       : 0.472
    (TP=147, FP=110, FN=219)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 257
    Precision: 0.580
    Recall   : 0.407
    F1       : 0.478
    (TP=149, FP=108, FN=217)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 203
    Gold triples: 298 | Pred triples: 226
    Precision: 0.650
    Recall   : 0.493
    F1       : 0.561
    (TP=147, FP=79, FN=151)
  [anchor_window]
    样本数: 203
    Gold triples: 298 | Pred triples: 226
    Precision: 0.659
    Recall   : 0.500
    F1       : 0.569
    (TP=149, FP=77, FN=149)
================================================

2026-08-27 00:54:55,477 | INFO | ================ 前 10 条样本判定 ================

--- id=141 ---
text: The previously banned march was sanctioned by the police at the last minute and is one of several protests this weekend in Hong Kong .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1386 ---
text: Contentious issue The Greater Hyderabad Cab and Bus Operators Association went on strike demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003 .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003",
    "effect": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003"
    },
    "relation": "caused",
    "effect": {
      "span": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
    }
  }
]

--- id=2991 ---
text: Today 's incident , comes barely days after the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley , and has cast a shadow over the February 16 Lok Sabhapolls in the state .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 2}
gold_relations:
[
  {
    "cause": "the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley",
    "effect": "Today 's incident"
  },
  {
    "cause": "Today 's incident",
    "effect": "has cast a shadow over the February 16 Lok Sabhapolls in the state"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "Today 's incident"
    },
    "relation": "caused",
    "effect": {
      "span": "cast a shadow over the February 16 Lok Sabhapolls in the state"
    }
  }
]

--- id=2634 ---
text: ALAPPUZHA : House of YC president attacked December 15 , 2016 00:00 IST The house of Kayamkulam Bharanikkavu Youth Congress ( YC ) mandalam president Salman was attacked by unknown persons on Wednesday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=802 ---
text: The march started from the Martyrs ' Column at Palayam and concluded before the Secretariat .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=88 ---
text: Some schools which had to postpone their mid-term examinations due to the bandh have the additional task of conducting the tests before resuming the classes .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "the bandh",
    "effect": "Some schools which had to postpone their mid-term examinations"
  },
  {
    "cause": "Some schools which had to postpone their mid-term examinations",
    "effect": "have the additional task of conducting the tests before resuming the classes"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the bandh"
    },
    "relation": "caused",
    "effect": {
      "span": "Some schools which had to postpone their mid-term examinations"
    }
  }
]

--- id=1835 ---
text: Two men have been arrested for the murder of two ANC branch leaders on the KwaZulu-Natal south coast , police said on Tuesday .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast",
    "effect": "Two men have been arrested"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast"
    },
    "relation": "caused",
    "effect": {
      "span": "Two men have been arrested"
    }
  }
]

--- id=1032 ---
text: He cited instances in 2005 when the Bajrang Dal activists allegedly assaulted employees who were going out on tour followed by attacks on churches in September 2008 and the 2009 Amnesia pub attack ..
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1548 ---
text: The division bench of Bombay High Court comprising justices Ranjana Desai and R V More while dismissing the plea of state government earlier this year had said " we are of the view that the view taken by learned Sessions Judge so far as involvement of the duo in this case is concerned , cannot be called unreasonable , palpably false , manifestly erroneous and demonstratively unsustainable which merits our interference . "
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2714 ---
text: Demonstrators dismantled roadside barriers and built makeshift barricades between them and the police .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]
2026-08-27 00:54:55,491 | INFO | Eval report saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-random-k1_20260827-005455.md
2026-08-27 00:54:55,492 | INFO | Generation failure outputs saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-random-k1_20260827-005455_generation_failures.jsonl
2026-08-27 00:54:55,501 | INFO | Phase 2 增量汇总已保存：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
2026-08-27 00:54:55,502 | INFO | [Phase 2 2/6] 开始 fixed_random_k3

2026-08-27 00:54:56,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:54:59,529 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:02,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:03,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:03,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:06,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:09,515 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:10,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:11,163 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:12,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:13,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:14,136 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:15,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:15,865 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:16,807 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:19,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:20,055 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:20,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:21,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:22,773 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:23,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:24,596 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:27,795 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:28,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:29,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:32,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:33,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:36,398 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:40,896 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:41,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:44,660 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:45,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:48,730 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:49,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:50,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:53,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:56,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:55:57,019 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:00,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:01,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:02,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:02,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:05,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:06,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:07,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:10,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:12,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:15,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:18,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:19,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:24,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:26,963 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:28,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:29,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:30,099 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:34,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:37,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:38,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:40,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:41,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:47,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:48,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:49,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:50,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:51,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:54,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:55,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:56,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:57,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:56:58,266 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:00,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:01,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:04,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:07,761 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 00:57:10,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:12,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:15,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:19,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:22,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:23,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:24,573 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:25,470 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:26,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:33,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:36,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:39,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:45,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:46,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:49,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:52,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:55,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:59,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:57:59,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:01,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:04,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:08,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:12,488 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:13,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:14,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:15,434 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:16,589 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:17,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:18,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:19,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:20,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:23,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:26,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:29,724 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:32,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:35,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:36,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:38,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:39,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:40,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:41,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:43,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:49,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:52,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:53,329 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:54,371 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:55,359 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:58:59,678 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:00,642 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:01,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:04,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:10,605 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:14,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:15,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:16,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:18,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:19,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:20,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:25,575 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:28,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:33,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:33,946 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:37,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:41,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:42,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:45,063 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:46,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:47,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:48,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:51,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:54,248 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:55,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:56,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 00:59:59,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:00:00,422 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:03,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:04,071 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:07,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:10,549 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:11,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:14,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:17,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:19,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:23,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:25,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:26,995 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:30,329 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:33,743 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:34,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:37,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:38,561 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:41,031 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:41,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:42,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:43,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:44,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:45,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:46,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:47,719 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:48,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:51,625 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:54,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:57,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:00:58,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:00,771 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:01,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:05,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:06,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:07,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:09,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:10,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:11,860 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:14,880 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:20,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:21,745 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:26,020 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:27,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:28,078 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:30,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:31,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:32,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:35,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:36,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:36,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:39,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:42,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:43,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:46,762 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:47,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:48,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:49,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:01:52,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:00,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:01,210 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:03,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:06,413 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:07,256 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:08,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:09,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:12,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:13,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:18,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:19,095 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:20,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:23,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:25,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:28,765 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:29,662 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:02:30,497 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:31,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:32,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:33,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:34,085 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:34,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:37,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:43,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:45,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:49,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:50,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:50,829 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:51,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:52,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:53,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:56,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:02:59,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:02,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:05,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:06,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:09,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:10,213 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:13,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:16,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:19,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:22,115 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:23,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:26,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:30,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:31,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:33,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:34,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:37,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:37,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:41,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:43,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:46,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:49,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:49,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:52,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:53,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:54,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:55,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:56,167 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:03:58,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:02,115 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:04,777 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:07,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:08,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:11,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:14,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:17,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:17,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:18,812 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:19,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:20,840 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:21,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:24,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:27,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:28,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:33,435 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:36,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:37,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:38,146 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:39,133 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:43,073 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:43,906 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:48,992 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:49,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:52,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:04:55,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:00,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:01,526 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:05,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:05:06,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:08,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:10,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:13,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:14,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:15,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:16,686 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:19,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:22,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:25,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:28,279 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:29,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:30,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:30,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:31,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:32,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:36,081 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:38,383 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:41,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:42,181 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:43,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:43,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:44,976 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:46,025 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:46,873 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:51,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:51,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:55,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:56,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:57,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:05:58,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:00,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:01,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:04,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:07,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:08,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:09,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:10,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:10,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:11,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:14,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:15,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:16,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:19,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:22,317 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:25,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:28,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:28,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:29,919 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:30,767 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:31,782 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:32,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:36,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:37,183 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:39,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:42,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:45,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:46,206 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:49,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:51,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:52,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:06:57,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:02,699 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:06,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:09,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:12,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:15,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:17,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:18,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:19,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:24,693 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:25,618 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:28,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:31,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:07:32,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:32,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:35,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:36,352 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:37,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:38,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:39,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:40,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:41,405 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:42,292 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:43,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:46,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:47,511 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:48,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:49,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:52,555 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:54,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:55,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:56,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:07:57,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:00,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:03,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:04,715 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:07,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:08,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:09,912 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:12,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:13,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:16,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:20,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:23,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:29,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:30,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:31,815 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:34,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:35,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:36,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:37,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:40,198 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:43,217 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:46,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:48,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:49,908 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:52,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:55,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:08:56,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:00,567 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:03,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:04,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:07,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:11,020 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:13,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:14,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:15,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:17,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:19,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:20,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:23,181 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:26,598 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:27,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:28,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:31,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:32,663 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:33,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:34,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:35,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:36,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:39,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:40,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:44,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:45,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:46,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:50,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:51,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:09:54,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:57,155 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:58,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:09:59,132 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:00,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:01,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:02,000 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:04,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:07,231 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:11,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:12,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:13,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:15,766 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:16,687 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:17,524 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:19,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:20,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:23,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:24,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:25,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:28,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:31,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:32,059 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:32,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:38,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:39,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:40,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:41,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:42,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:43,127 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:45,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:48,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:51,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:52,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:54,911 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:57,607 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:58,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:10:59,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:00,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:03,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:08,263 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:11,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:12,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:16,919 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:17,967 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:20,951 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:21,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:24,613 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:27,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:28,103 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:29,057 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:33,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:35,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:38,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:39,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:40,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:40,430 | INFO |
2026-08-27 01:11:40,430 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k3 progress 500/500 ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 235
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.834
  Precision: 0.885
  Recall   : 0.788
  F1       : 0.834
  (TP=208, TN=209, FP=27, FN=56)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 270
    Precision: 0.567
    Recall   : 0.418
    F1       : 0.481
    (TP=153, FP=117, FN=213)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 270
    Precision: 0.574
    Recall   : 0.423
    F1       : 0.487
    (TP=155, FP=115, FN=211)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 208
    Gold triples: 302 | Pred triples: 234
    Precision: 0.654
    Recall   : 0.507
    F1       : 0.571
    (TP=153, FP=81, FN=149)
  [anchor_window]
    样本数: 208
    Gold triples: 302 | Pred triples: 234
    Precision: 0.662
    Recall   : 0.513
    F1       : 0.578
    (TP=155, FP=79, FN=147)
================================================
2026-08-27 01:11:40,432 | INFO |
2026-08-27 01:11:40,432 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k3 final report ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 235
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.834
  Precision: 0.885
  Recall   : 0.788
  F1       : 0.834
  (TP=208, TN=209, FP=27, FN=56)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 270
    Precision: 0.567
    Recall   : 0.418
    F1       : 0.481
    (TP=153, FP=117, FN=213)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 270
    Precision: 0.574
    Recall   : 0.423
    F1       : 0.487
    (TP=155, FP=115, FN=211)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 208
    Gold triples: 302 | Pred triples: 234
    Precision: 0.654
    Recall   : 0.507
    F1       : 0.571
    (TP=153, FP=81, FN=149)
  [anchor_window]
    样本数: 208
    Gold triples: 302 | Pred triples: 234
    Precision: 0.662
    Recall   : 0.513
    F1       : 0.578
    (TP=155, FP=79, FN=147)
================================================

2026-08-27 01:11:40,434 | INFO | ================ 前 10 条样本判定 ================

--- id=141 ---
text: The previously banned march was sanctioned by the police at the last minute and is one of several protests this weekend in Hong Kong .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1386 ---
text: Contentious issue The Greater Hyderabad Cab and Bus Operators Association went on strike demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003 .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003",
    "effect": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003"
    },
    "relation": "caused",
    "effect": {
      "span": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
    }
  }
]

--- id=2991 ---
text: Today 's incident , comes barely days after the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley , and has cast a shadow over the February 16 Lok Sabhapolls in the state .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 2}
gold_relations:
[
  {
    "cause": "the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley",
    "effect": "Today 's incident"
  },
  {
    "cause": "Today 's incident",
    "effect": "has cast a shadow over the February 16 Lok Sabhapolls in the state"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "Today 's incident"
    },
    "relation": "caused",
    "effect": {
      "span": "cast a shadow over the February 16 Lok Sabhapolls in the state"
    }
  }
]

--- id=2634 ---
text: ALAPPUZHA : House of YC president attacked December 15 , 2016 00:00 IST The house of Kayamkulam Bharanikkavu Youth Congress ( YC ) mandalam president Salman was attacked by unknown persons on Wednesday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=802 ---
text: The march started from the Martyrs ' Column at Palayam and concluded before the Secretariat .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=88 ---
text: Some schools which had to postpone their mid-term examinations due to the bandh have the additional task of conducting the tests before resuming the classes .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "the bandh",
    "effect": "Some schools which had to postpone their mid-term examinations"
  },
  {
    "cause": "Some schools which had to postpone their mid-term examinations",
    "effect": "have the additional task of conducting the tests before resuming the classes"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the bandh"
    },
    "relation": "caused",
    "effect": {
      "span": "Some schools which had to postpone their mid-term examinations"
    }
  }
]

--- id=1835 ---
text: Two men have been arrested for the murder of two ANC branch leaders on the KwaZulu-Natal south coast , police said on Tuesday .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast",
    "effect": "Two men have been arrested"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast"
    },
    "relation": "caused",
    "effect": {
      "span": "Two men have been arrested"
    }
  }
]

--- id=1032 ---
text: He cited instances in 2005 when the Bajrang Dal activists allegedly assaulted employees who were going out on tour followed by attacks on churches in September 2008 and the 2009 Amnesia pub attack ..
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1548 ---
text: The division bench of Bombay High Court comprising justices Ranjana Desai and R V More while dismissing the plea of state government earlier this year had said " we are of the view that the view taken by learned Sessions Judge so far as involvement of the duo in this case is concerned , cannot be called unreasonable , palpably false , manifestly erroneous and demonstratively unsustainable which merits our interference . "
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2714 ---
text: Demonstrators dismantled roadside barriers and built makeshift barricades between them and the police .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]
2026-08-27 01:11:40,446 | INFO | Eval report saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-random-k3_20260827-011140.md
2026-08-27 01:11:40,452 | INFO | Phase 2 增量汇总已保存：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
2026-08-27 01:11:40,453 | INFO | [Phase 2 3/6] 开始 fixed_random_k5

2026-08-27 01:11:41,573 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:44,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:47,839 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:49,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:50,119 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:53,014 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:56,046 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:57,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:58,107 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:11:59,201 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:02,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:03,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:04,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:05,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:06,951 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:09,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:10,514 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:11,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:12,763 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:13,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:15,029 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:16,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:19,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:21,015 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:22,141 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:25,243 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:26,431 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:29,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:34,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:35,535 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:38,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:39,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:42,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:44,012 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:45,150 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:47,703 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:50,908 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:52,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:55,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:56,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:57,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:12:58,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:01,753 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:02,877 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:04,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:07,259 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:10,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:13,039 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:15,934 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:16,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:20,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:23,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:24,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:25,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:26,935 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:31,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:34,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:35,776 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:38,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:39,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:42,945 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:45,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:46,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:47,914 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:49,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:52,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:53,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:54,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:55,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:56,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:13:59,530 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:00,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:03,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:07,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:14:09,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:12,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:15,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:19,883 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:22,977 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:24,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:25,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:28,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:29,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:37,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:40,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:43,480 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:49,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:50,448 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:53,758 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:14:56,771 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:00,826 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:04,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:05,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:06,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:11,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:15,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:19,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:20,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:22,189 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:23,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:24,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:26,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:27,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:28,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:29,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:33,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:36,739 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:39,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:42,943 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:46,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:47,061 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:49,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:50,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:51,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:53,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:15:55,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:02,352 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:05,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:06,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:07,489 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:08,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:13,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:14,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:15,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:20,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:27,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:31,299 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:32,579 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:33,687 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:36,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:36,339 | WARNING | 生成失败：sample_id=2758 attempt=1/2 error=未找到 JSON 对象
2026-08-27 01:16:38,365 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:38,366 | WARNING | 生成失败：sample_id=2758 attempt=2/2 error=未找到 JSON 对象
2026-08-27 01:16:38,367 | ERROR | 生成兜底：sample_id=2758 error=未找到 JSON 对象
2026-08-27 01:16:39,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:41,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:46,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:50,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:51,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:52,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:16:56,817 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:00,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:01,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:03,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:04,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:05,990 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:07,113 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:10,647 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:17:13,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:14,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:15,807 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:19,473 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:20,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:23,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:24,623 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:28,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:31,605 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:32,872 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:36,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:38,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:41,691 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:45,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:50,038 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:51,258 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:54,803 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:58,503 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:17:59,609 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:02,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:03,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:06,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:07,627 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:08,723 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:09,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:11,102 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:12,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:13,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:14,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:15,741 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:18,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:21,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:23,142 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:24,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:26,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:29,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:33,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:36,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:36,651 | WARNING | 生成失败：sample_id=2736 attempt=1/2 error=未找到 JSON 对象
2026-08-27 01:18:39,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:39,210 | WARNING | 生成失败：sample_id=2736 attempt=2/2 error=未找到 JSON 对象
2026-08-27 01:18:39,210 | ERROR | 生成兜底：sample_id=2736 error=未找到 JSON 对象
2026-08-27 01:18:40,406 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:43,469 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:44,594 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:45,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:49,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:55,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:18:56,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:00,897 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:02,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:03,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:06,387 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:07,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:08,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:11,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:12,464 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:13,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:16,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:19,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:20,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:24,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:25,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:26,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:27,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:30,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:38,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:39,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:42,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:45,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:46,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:50,007 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:51,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:19:54,573 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:19:55,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:00,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:01,915 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:03,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:06,419 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:09,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:12,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:13,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:15,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:16,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:17,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:18,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:19,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:20,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:23,447 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:28,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:31,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:34,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:37,809 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:38,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:39,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:41,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:42,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:45,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:49,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:51,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:55,021 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:56,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:20:59,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:00,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:03,940 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:07,479 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:10,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:13,353 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:14,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:17,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:22,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:23,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:25,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:26,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:29,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:30,734 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:34,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:37,224 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:40,085 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:42,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:43,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:46,790 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:48,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:49,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:50,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:51,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:54,350 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:21:58,055 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:00,929 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:03,869 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:05,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:08,537 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:11,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:14,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:15,619 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:16,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:18,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:19,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:20,357 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:23,442 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:26,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:27,905 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:32,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:35,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:37,088 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:38,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:39,197 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:43,246 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:22:44,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:48,017 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:49,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:51,774 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:54,821 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:22:59,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:01,025 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:04,781 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:06,043 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:08,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:11,459 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:14,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:17,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:18,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:19,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:23,243 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:26,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:29,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:32,242 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:33,382 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:34,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:35,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:36,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:37,534 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:41,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:44,047 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:47,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:48,420 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:49,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:50,847 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:52,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:53,097 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:54,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:23:57,294 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:00,050 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:03,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:04,764 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:06,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:07,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:10,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:11,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:14,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:17,433 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:18,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:19,534 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:20,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:21,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:22,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:25,817 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:27,201 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:28,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:31,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:34,508 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:37,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:40,650 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:41,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:43,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:44,107 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:45,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:46,599 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:50,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:51,329 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:54,303 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:24:56,964 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:00,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:01,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:04,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:07,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:08,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:13,311 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:18,396 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:22,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:25,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:28,343 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:25:31,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:34,464 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:35,416 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:36,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:41,686 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:42,917 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:45,883 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:48,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:49,718 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:50,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:53,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:54,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:55,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:25:57,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:00,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:01,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:04,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:05,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:06,652 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:10,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:11,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:12,394 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:13,630 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:16,779 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:17,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:18,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:20,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:21,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:24,453 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:27,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:28,829 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:32,201 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:33,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:34,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:37,385 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:38,411 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:41,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:45,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:49,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:55,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:56,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:26:57,423 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:00,475 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:01,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:02,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:03,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:06,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:09,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:13,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:16,002 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:17,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:20,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:23,521 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:26,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:30,606 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:33,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:35,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:37,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:41,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:44,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:46,187 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:47,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:48,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:51,326 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:52,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:55,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:58,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:27:59,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:01,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:04,606 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:05,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:06,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:08,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:09,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:28:10,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:13,124 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:14,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:19,005 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:19,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:21,261 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:25,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:26,644 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:29,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:32,821 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:33,974 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:35,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:36,396 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:37,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:38,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:41,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:42,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:46,752 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:47,831 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:53,323 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:55,932 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:57,008 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:28:58,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:00,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:01,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:04,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:05,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:06,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:09,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:12,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:13,910 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:15,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:20,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:21,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:23,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:24,217 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:25,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:26,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:29,369 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:32,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:35,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:36,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:39,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:42,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:43,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:44,151 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:45,258 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:48,211 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:51,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:54,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:29:55,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:00,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:02,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:05,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:08,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:11,252 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:14,037 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:15,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:16,184 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:20,502 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:23,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:26,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:27,675 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:28,814 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:28,816 | INFO |
2026-08-27 01:30:28,817 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k5 progress 500/500 ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 241
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.830
  Precision: 0.871
  Recall   : 0.795
  F1       : 0.832
  (TP=210, TN=205, FP=31, FN=54)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 275
    Precision: 0.560
    Recall   : 0.421
    F1       : 0.480
    (TP=154, FP=121, FN=212)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 275
    Precision: 0.567
    Recall   : 0.426
    F1       : 0.487
    (TP=156, FP=119, FN=210)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 210
    Gold triples: 305 | Pred triples: 236
    Precision: 0.653
    Recall   : 0.505
    F1       : 0.569
    (TP=154, FP=82, FN=151)
  [anchor_window]
    样本数: 210
    Gold triples: 305 | Pred triples: 236
    Precision: 0.661
    Recall   : 0.511
    F1       : 0.577
    (TP=156, FP=80, FN=149)
================================================

2026-08-27 01:30:28,818 | INFO |
2026-08-27 01:30:28,819 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_random_k5 final report ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 241
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.830
  Precision: 0.871
  Recall   : 0.795
  F1       : 0.832
  (TP=210, TN=205, FP=31, FN=54)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 275
    Precision: 0.560
    Recall   : 0.421
    F1       : 0.480
    (TP=154, FP=121, FN=212)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 275
    Precision: 0.567
    Recall   : 0.426
    F1       : 0.487
    (TP=156, FP=119, FN=210)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 210
    Gold triples: 305 | Pred triples: 236
    Precision: 0.653
    Recall   : 0.505
    F1       : 0.569
    (TP=154, FP=82, FN=151)
  [anchor_window]
    样本数: 210
    Gold triples: 305 | Pred triples: 236
    Precision: 0.661
    Recall   : 0.511
    F1       : 0.577
    (TP=156, FP=80, FN=149)
================================================
2026-08-27 01:30:28,820 | INFO | ================ 前 10 条样本判定 ================

--- id=141 ---
text: The previously banned march was sanctioned by the police at the last minute and is one of several protests this weekend in Hong Kong .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1386 ---
text: Contentious issue The Greater Hyderabad Cab and Bus Operators Association went on strike demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003 .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003",
    "effect": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003"
    },
    "relation": "caused",
    "effect": {
      "span": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
    }
  }
]

--- id=2991 ---
text: Today 's incident , comes barely days after the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley , and has cast a shadow over the February 16 Lok Sabhapolls in the state .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 2}
gold_relations:
[
  {
    "cause": "the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley",
    "effect": "Today 's incident"
  },
  {
    "cause": "Today 's incident",
    "effect": "has cast a shadow over the February 16 Lok Sabhapolls in the state"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "Today 's incident"
    },
    "relation": "caused",
    "effect": {
      "span": "cast a shadow over the February 16 Lok Sabhapolls in the state"
    }
  }
]

--- id=2634 ---
text: ALAPPUZHA : House of YC president attacked December 15 , 2016 00:00 IST The house of Kayamkulam Bharanikkavu Youth Congress ( YC ) mandalam president Salman was attacked by unknown persons on Wednesday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=802 ---
text: The march started from the Martyrs ' Column at Palayam and concluded before the Secretariat .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=88 ---
text: Some schools which had to postpone their mid-term examinations due to the bandh have the additional task of conducting the tests before resuming the classes .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 2}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 2}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "the bandh",
    "effect": "Some schools which had to postpone their mid-term examinations"
  },
  {
    "cause": "Some schools which had to postpone their mid-term examinations",
    "effect": "have the additional task of conducting the tests before resuming the classes"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "due to the bandh"
    },
    "relation": "caused",
    "effect": {
      "span": "Some schools which had to postpone their mid-term examinations"
    }
  }
]

--- id=1835 ---
text: Two men have been arrested for the murder of two ANC branch leaders on the KwaZulu-Natal south coast , police said on Tuesday .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast",
    "effect": "Two men have been arrested"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast"
    },
    "relation": "caused",
    "effect": {
      "span": "Two men have been arrested"
    }
  }
]

--- id=1032 ---
text: He cited instances in 2005 when the Bajrang Dal activists allegedly assaulted employees who were going out on tour followed by attacks on churches in September 2008 and the 2009 Amnesia pub attack ..
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1548 ---
text: The division bench of Bombay High Court comprising justices Ranjana Desai and R V More while dismissing the plea of state government earlier this year had said " we are of the view that the view taken by learned Sessions Judge so far as involvement of the duo in this case is concerned , cannot be called unreasonable , palpably false , manifestly erroneous and demonstratively unsustainable which merits our interference . "
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2714 ---
text: Demonstrators dismantled roadside barriers and built makeshift barricades between them and the police .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]
2026-08-27 01:30:28,834 | INFO | Eval report saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-random-k5_20260827-013028.md
2026-08-27 01:30:28,835 | INFO | Generation failure outputs saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-random-k5_20260827-013028_generation_failures.jsonl

2026-08-27 01:30:28,840 | INFO | Phase 2 增量汇总已保存：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
2026-08-27 01:30:28,841 | INFO | [Phase 2 4/6] 开始 fixed_rag_k1

2026-08-27 01:30:29,602 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:32,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:35,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:36,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:36,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:39,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:42,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:43,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:43,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:44,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:45,661 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:46,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:49,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:49,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:50,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:53,058 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:55,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:56,286 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:56,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:57,691 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:30:58,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:00,962 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:05,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:06,317 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:07,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:09,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:10,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:12,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:18,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:19,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:21,656 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:22,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:25,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:26,002 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:26,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:27,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:30,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:30,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:33,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:34,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:35,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:36,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:38,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:39,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:39,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:42,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:44,963 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:49,465 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:51,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:52,603 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:31:57,339 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:00,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:00,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:01,559 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:02,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:06,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:09,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:10,172 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:12,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:13,365 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:18,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:20,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:21,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:22,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:23,003 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:25,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:26,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:28,800 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:29,586 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:30,253 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:32,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:33,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:36,356 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:39,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:32:41,556 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:45,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:49,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:53,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:56,541 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:57,209 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:57,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:58,694 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:32:59,466 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:07,443 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:09,868 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:12,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:18,626 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:19,461 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:24,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:27,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:30,953 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:33,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:34,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:35,190 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:39,403 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:43,488 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:46,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:47,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:48,405 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:49,191 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:49,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:50,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:51,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:52,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:52,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:56,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:33:59,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:01,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:04,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:06,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:07,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:10,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:10,799 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:11,474 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:12,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:14,591 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:20,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:22,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:23,180 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:23,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:26,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:30,281 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:31,159 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:31,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:34,647 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:40,671 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:43,618 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:44,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:45,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:47,876 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:48,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:49,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:54,542 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:34:57,098 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:02,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:02,950 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:06,395 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:10,026 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:10,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:13,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:15,552 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:16,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:19,208 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:22,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:25,331 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:26,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:26,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:30,309 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:35:31,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:33,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:34,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:38,115 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:41,047 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:41,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:45,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:47,438 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:49,844 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:53,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:57,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:35:58,107 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:02,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:06,090 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:06,710 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:09,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:11,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:14,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:14,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:15,688 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:16,426 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:17,229 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:17,903 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:18,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:19,370 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:22,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:24,867 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:27,883 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:30,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:31,067 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:33,510 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:35,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:39,091 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:42,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:43,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:45,668 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:46,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:47,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:49,468 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:55,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:55,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:36:59,998 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:00,814 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:01,643 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:04,388 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:05,176 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:05,858 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:06,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:07,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:07,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:10,716 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:13,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:14,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:17,046 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:17,769 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:18,697 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:19,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:20,285 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:29,472 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:30,277 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:32,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:35,240 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:36,074 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:37,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:37,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:40,818 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:41,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:46,130 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:46,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:47,839 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:50,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:54,313 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:57,321 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:58,006 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:37:58,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:37:59,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:01,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:02,712 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:03,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:04,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:06,859 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:13,926 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:16,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:19,013 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:21,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:22,463 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:24,641 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:26,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:27,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:27,779 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:30,389 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:32,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:35,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:36,482 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:39,342 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:40,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:43,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:46,463 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:48,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:51,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:52,255 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:54,943 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:38:59,690 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:00,507 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:01,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:01,909 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:04,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:05,315 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:08,313 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:10,983 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:39:13,550 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:02,332 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 01:40:02,333 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'Model unloaded.'}
2026-08-27 01:40:11,778 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:12,486 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:14,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:15,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:16,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:17,082 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:17,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:20,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:23,700 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:26,300 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:27,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:28,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:30,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:33,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:36,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:36,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:37,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:38,183 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:38,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:39,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:44,257 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:47,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:47,825 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:52,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:54,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:55,675 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:56,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:40:57,216 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:00,905 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:01,597 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:04,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:07,569 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:10,196 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:12,746 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:17,421 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:41:18,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:21,584 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:22,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:24,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:27,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:29,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:32,289 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:32,984 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:33,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:36,939 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:39,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:41,878 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:44,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:45,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:46,036 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:46,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:47,404 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:48,082 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:51,336 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:53,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:56,528 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:57,265 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:57,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:58,577 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:41:59,436 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:00,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:00,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:03,460 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:04,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:07,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:07,875 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:08,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:09,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:11,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:12,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:15,517 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:17,906 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:18,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:19,335 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:19,923 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:20,604 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:21,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:24,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:24,636 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:25,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:27,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:30,602 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:33,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:35,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:38,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:39,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:39,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:40,751 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:41,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:44,672 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:45,347 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:48,089 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:50,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:53,140 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:53,757 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:56,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:59,040 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:42:59,918 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:02,924 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:06,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:07,378 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:10,205 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:12,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:15,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:18,415 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:19,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:19,958 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:24,784 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:25,521 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:43:28,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:30,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:31,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:32,084 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:34,390 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:35,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:36,055 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:36,771 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:37,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:38,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:39,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:39,957 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:40,770 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:43,960 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:44,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:47,120 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:47,955 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:50,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:53,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:54,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:55,126 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:55,850 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:43:58,612 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:01,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:02,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:05,372 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:06,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:06,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:09,401 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:10,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:12,489 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:16,883 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:19,617 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:25,175 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:25,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:26,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:27,481 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:30,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:31,428 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:32,110 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:34,538 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:37,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:39,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:42,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:42,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:45,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:48,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:49,408 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:54,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:56,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:44:57,648 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:00,045 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:03,563 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:06,221 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:06,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:07,701 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:08,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:10,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:11,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:12,318 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:15,681 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:16,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:19,169 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:22,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:22,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:23,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:24,580 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:25,380 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:26,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:28,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:29,193 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:33,425 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:34,056 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:34,645 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:45:38,568 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:39,374 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:42,092 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:44,726 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:45,649 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:46,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:47,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:48,087 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:48,711 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:51,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:53,330 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:57,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:58,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:45:58,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:01,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:01,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:02,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:04,779 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:05,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:08,157 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:08,837 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:09,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:12,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:15,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:15,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:16,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:21,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:22,418 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:23,293 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:24,049 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:24,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:25,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:28,128 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:31,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:34,381 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:35,277 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:37,550 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:39,937 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:40,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:41,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:42,144 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:44,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:49,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:51,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:52,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:57,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:46:58,432 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:01,622 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:04,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:06,849 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:09,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:09,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:10,555 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:14,427 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:16,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:19,536 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:20,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:21,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:21,070 | INFO |
2026-08-27 01:47:21,071 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_rag_k1 progress 500/500 ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 248
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.840
  Precision: 0.871
  Recall   : 0.818
  F1       : 0.844
  (TP=216, TN=204, FP=32, FN=48)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 293
    Precision: 0.563
    Recall   : 0.451
    F1       : 0.501
    (TP=165, FP=128, FN=201)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 293
    Precision: 0.549
    Recall   : 0.440
    F1       : 0.489
    (TP=161, FP=132, FN=205)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 216
    Gold triples: 313 | Pred triples: 252
    Precision: 0.655
    Recall   : 0.527
    F1       : 0.584
    (TP=165, FP=87, FN=148)
  [anchor_window]
    样本数: 216
    Gold triples: 313 | Pred triples: 252
    Precision: 0.639
    Recall   : 0.514
    F1       : 0.570
    (TP=161, FP=91, FN=152)
================================================
2026-08-27 01:47:21,073 | INFO |
2026-08-27 01:47:21,074 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_rag_k1 final report ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 248
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.840
  Precision: 0.871
  Recall   : 0.818
  F1       : 0.844
  (TP=216, TN=204, FP=32, FN=48)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 293
    Precision: 0.563
    Recall   : 0.451
    F1       : 0.501
    (TP=165, FP=128, FN=201)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 293
    Precision: 0.549
    Recall   : 0.440
    F1       : 0.489
    (TP=161, FP=132, FN=205)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 216
    Gold triples: 313 | Pred triples: 252
    Precision: 0.655
    Recall   : 0.527
    F1       : 0.584
    (TP=165, FP=87, FN=148)
  [anchor_window]
    样本数: 216
    Gold triples: 313 | Pred triples: 252
    Precision: 0.639
    Recall   : 0.514
    F1       : 0.570
    (TP=161, FP=91, FN=152)
================================================

2026-08-27 01:47:21,074 | INFO | ================ 前 10 条样本判定 ================

--- id=141 ---
text: The previously banned march was sanctioned by the police at the last minute and is one of several protests this weekend in Hong Kong .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1386 ---
text: Contentious issue The Greater Hyderabad Cab and Bus Operators Association went on strike demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003 .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003",
    "effect": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003"
    },
    "relation": "caused",
    "effect": {
      "span": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
    }
  }
]

--- id=2991 ---
text: Today 's incident , comes barely days after the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley , and has cast a shadow over the February 16 Lok Sabhapolls in the state .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 2}
gold_relations:
[
  {
    "cause": "the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley",
    "effect": "Today 's incident"
  },
  {
    "cause": "Today 's incident",
    "effect": "has cast a shadow over the February 16 Lok Sabhapolls in the state"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "Today 's incident"
    },
    "relation": "caused",
    "effect": {
      "span": "cast a shadow over the February 16 Lok Sabhapolls in the state"
    }
  }
]

--- id=2634 ---
text: ALAPPUZHA : House of YC president attacked December 15 , 2016 00:00 IST The house of Kayamkulam Bharanikkavu Youth Congress ( YC ) mandalam president Salman was attacked by unknown persons on Wednesday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=802 ---
text: The march started from the Martyrs ' Column at Palayam and concluded before the Secretariat .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=88 ---
text: Some schools which had to postpone their mid-term examinations due to the bandh have the additional task of conducting the tests before resuming the classes .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 2}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 1, 'fn': 2}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "the bandh",
    "effect": "Some schools which had to postpone their mid-term examinations"
  },
  {
    "cause": "Some schools which had to postpone their mid-term examinations",
    "effect": "have the additional task of conducting the tests before resuming the classes"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the bandh"
    },
    "relation": "caused",
    "effect": {
      "span": "Some schools which had to postpone their mid-term examinations have the additional task of conducting the tests before resuming the classes"
    }
  }
]

--- id=1835 ---
text: Two men have been arrested for the murder of two ANC branch leaders on the KwaZulu-Natal south coast , police said on Tuesday .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast",
    "effect": "Two men have been arrested"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast"
    },
    "relation": "caused",
    "effect": {
      "span": "Two men have been arrested"
    }
  }
]

--- id=1032 ---
text: He cited instances in 2005 when the Bajrang Dal activists allegedly assaulted employees who were going out on tour followed by attacks on churches in September 2008 and the 2009 Amnesia pub attack ..
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1548 ---
text: The division bench of Bombay High Court comprising justices Ranjana Desai and R V More while dismissing the plea of state government earlier this year had said " we are of the view that the view taken by learned Sessions Judge so far as involvement of the duo in this case is concerned , cannot be called unreasonable , palpably false , manifestly erroneous and demonstratively unsustainable which merits our interference . "
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2714 ---
text: Demonstrators dismantled roadside barriers and built makeshift barricades between them and the police .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]
2026-08-27 01:47:21,086 | INFO | Eval report saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-knn_pattern-k1_20260827-014721.md
2026-08-27 01:47:21,092 | INFO | Phase 2 增量汇总已保存：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
2026-08-27 01:47:21,093 | INFO | [Phase 2 5/6] 开始 fixed_rag_k3

2026-08-27 01:47:22,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:25,138 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:28,118 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:29,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:30,100 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:32,714 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:35,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:36,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:37,684 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:38,533 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:41,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:42,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:45,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:46,341 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:47,525 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:48,499 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:51,203 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:52,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:53,020 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:53,946 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:55,085 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:47:57,823 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:02,452 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:03,577 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:04,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:07,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:08,484 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:11,357 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:16,908 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:17,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:20,742 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:21,921 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:25,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:26,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:27,093 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:29,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:32,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:33,505 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:36,744 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:38,006 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:38,986 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:40,007 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:42,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:43,607 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:44,732 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:47,731 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:50,478 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:53,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:56,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:48:57,519 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:02,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:05,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:06,635 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:07,740 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:08,816 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:12,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:16,312 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:17,282 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:19,866 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:21,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:25,919 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:28,385 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:29,297 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:30,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:31,364 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:34,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:35,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:36,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:37,376 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:38,267 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:41,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:41,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:45,051 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:48,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:49:50,839 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:53,633 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:49:56,219 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:00,558 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:03,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:04,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:05,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:06,634 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:07,574 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:15,570 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:18,230 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:21,446 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:27,117 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:28,195 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:33,478 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:36,913 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:40,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:43,891 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:44,843 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:45,894 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:50,302 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:54,673 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:58,454 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:50:59,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:00,307 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:01,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:04,027 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:05,077 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:06,028 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:08,885 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:09,853 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:13,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:16,402 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:19,139 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:21,674 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:25,722 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:26,572 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:29,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:30,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:31,199 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:32,354 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:34,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:41,065 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:43,709 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:44,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:45,870 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:48,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:52,548 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:53,614 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:54,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:51:59,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:05,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:09,083 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:10,237 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:11,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:14,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:15,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:16,562 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:21,902 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:24,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:25,789 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:28,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:32,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:35,930 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:36,824 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:39,629 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:42,273 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:43,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:46,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:50,145 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:53,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:54,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:52:54,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:00,892 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:53:03,680 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:04,763 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:05,705 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:09,363 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:12,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:13,676 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:17,006 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:19,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:22,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:25,787 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:30,194 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:31,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:36,154 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:40,009 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:40,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:43,396 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:44,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:47,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:48,116 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:49,114 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:50,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:51,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:52,392 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:54,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:55,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:53:57,048 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:00,122 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:03,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:06,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:07,393 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:10,095 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:12,863 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:16,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:19,545 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:20,805 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:23,664 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:24,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:25,806 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:28,544 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:34,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:35,459 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:39,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:41,004 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:42,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:45,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:46,313 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:47,272 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:49,842 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:50,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:51,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:54,815 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:57,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:54:58,914 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:01,755 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:02,848 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:03,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:04,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:06,018 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:15,410 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:16,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:19,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:21,527 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:22,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:23,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:24,854 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:28,179 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:29,164 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:33,991 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:35,041 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:37,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:41,011 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:43,834 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:47,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:48,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:55:49,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:50,368 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:52,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:53,999 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:55,094 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:56,020 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:55:58,989 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:04,491 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:07,137 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:09,996 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:12,886 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:13,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:16,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:17,565 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:18,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:21,797 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:24,659 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:27,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:30,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:31,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:34,856 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:35,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:39,274 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:42,819 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:45,349 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:48,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:49,288 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:52,149 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:57,249 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:58,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:56:59,424 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:00,532 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:03,495 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:04,471 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:07,707 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:10,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:13,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:14,441 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:15,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:18,034 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:18,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:20,064 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:21,158 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:22,276 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:25,078 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:28,620 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:31,476 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:36,846 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:38,096 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:41,227 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:43,835 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:46,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:47,324 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:48,327 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:49,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:50,320 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:51,245 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:56,682 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:57:59,733 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:00,793 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:05,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:08,462 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:09,540 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:10,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:11,653 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:15,637 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:16,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:20,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:23,270 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:24,409 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:27,238 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:32,333 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:33,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:36,900 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 01:58:39,655 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:42,226 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:44,931 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:48,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:49,222 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:50,162 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:51,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:54,567 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:58:57,390 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:00,108 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:03,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:04,225 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:05,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:06,207 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:07,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:08,445 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:12,035 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:14,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:17,864 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:18,916 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:19,808 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:20,786 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:22,010 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:23,024 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:23,952 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:28,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:29,827 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:33,178 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:34,314 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:35,269 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:38,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:41,365 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:42,407 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:45,632 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:48,212 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:49,290 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:50,262 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:51,215 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:52,200 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:54,792 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:57,899 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:58,864 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 01:59:59,817 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:02,748 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:05,777 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:08,944 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:11,585 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:14,639 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:15,477 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:16,458 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:17,611 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:18,721 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:22,287 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:23,271 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:26,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:28,467 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:31,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:32,651 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:35,895 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:38,451 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:39,560 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:44,430 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:49,414 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:52,971 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:55,936 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:00:58,933 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:01,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:04,847 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:05,747 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:06,884 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:11,978 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:13,053 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:15,960 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:18,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 02:01:19,760 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:20,756 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:23,893 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:24,922 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:26,068 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:27,211 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:28,346 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:29,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:30,483 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:31,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:32,669 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:36,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:37,066 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:39,841 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:40,871 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:43,928 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:46,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:47,874 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:49,044 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:50,153 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:53,291 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:56,352 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:01:57,600 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:00,845 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:02,001 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:03,080 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:06,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:07,236 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:11,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:16,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:19,616 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:25,509 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:26,492 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:27,553 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:30,798 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:31,982 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:33,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:34,131 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:36,762 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:39,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:42,638 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:45,399 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:46,325 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:49,367 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:52,516 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:55,702 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:02:58,980 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:03,520 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:04,400 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:08,886 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:12,631 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:15,546 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:18,557 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:19,576 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:20,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:23,165 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:24,148 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:25,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:29,765 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:30,626 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:31,720 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:35,220 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:36,218 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:37,334 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:39,888 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:40,993 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:42,069 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:44,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:45,855 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:50,429 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:53,030 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:53,987 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:58,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:03:59,394 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 02:04:02,379 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:05,345 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:06,485 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:07,592 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:08,687 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:09,813 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:10,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:13,338 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:15,873 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:20,166 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:21,075 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:28,112 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:30,577 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:31,504 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:32,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:34,593 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:35,685 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:38,498 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:39,439 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:40,304 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:43,361 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:46,388 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:47,310 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:48,247 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:53,754 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:54,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:55,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:56,737 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:57,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:04:58,780 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:01,683 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:05,052 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:08,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:09,857 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:12,371 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:15,042 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:15,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:16,862 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:17,988 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:20,942 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:25,627 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:28,610 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:29,717 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:34,970 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:36,244 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:39,985 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:42,861 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:45,692 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:48,181 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:49,173 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:50,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:54,526 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:05:57,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:00,204 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:03,185 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:04,264 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:04,265 | INFO |
2026-08-27 02:06:04,265 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_rag_k3 progress 500/500 ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 259
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.850
  Precision: 0.865
  Recall   : 0.848
  F1       : 0.857
  (TP=224, TN=201, FP=35, FN=40)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 309
    Precision: 0.579
    Recall   : 0.489
    F1       : 0.530
    (TP=179, FP=130, FN=187)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 309
    Precision: 0.563
    Recall   : 0.475
    F1       : 0.516
    (TP=174, FP=135, FN=192)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 224
    Gold triples: 320 | Pred triples: 266
    Precision: 0.673
    Recall   : 0.559
    F1       : 0.611
    (TP=179, FP=87, FN=141)
  [anchor_window]
    样本数: 224
    Gold triples: 320 | Pred triples: 266
    Precision: 0.654
    Recall   : 0.544
    F1       : 0.594
    (TP=174, FP=92, FN=146)
================================================
2026-08-27 02:06:04,267 | INFO |
2026-08-27 02:06:04,268 | INFO | ================ Qwen3.6 27B No Thinking CNC validation fixed_rag_k3 final report ================
样本总数: 500
  Gold 含因果: 264 | Pred 含因果: 259
  Primary extraction metric: strict_token_f1
  strict_token_f1 阈值: 0.800
  anchor_window 阈值: 0.900

[Layer 1] Detection
  Accuracy : 0.850
  Precision: 0.865
  Recall   : 0.848
  F1       : 0.857
  (TP=224, TN=201, FP=35, FN=40)

[Layer 2A] Extraction all_samples
  说明: 忽略 has_causal 字段，在全部样本上匹配 pred triples 与 gold relations。
  [strict_token_f1] (primary)
    样本数: 500
    Gold triples: 366 | Pred triples: 309
    Precision: 0.579
    Recall   : 0.489
    F1       : 0.530
    (TP=179, FP=130, FN=187)
  [anchor_window]
    样本数: 500
    Gold triples: 366 | Pred triples: 309
    Precision: 0.563
    Recall   : 0.475
    F1       : 0.516
    (TP=174, FP=135, FN=192)

[Layer 2B] Extraction detected_only
  说明: 只在 gold=True 且 pred=True 的样本上评估 span 质量，主要作为诊断视图。
  [strict_token_f1] (primary)
    样本数: 224
    Gold triples: 320 | Pred triples: 266
    Precision: 0.673
    Recall   : 0.559
    F1       : 0.611
    (TP=179, FP=87, FN=141)
  [anchor_window]
    样本数: 224
    Gold triples: 320 | Pred triples: 266
    Precision: 0.654
    Recall   : 0.544
    F1       : 0.594
    (TP=174, FP=92, FN=146)
================================================

2026-08-27 02:06:04,269 | INFO | ================ 前 10 条样本判定 ================

--- id=141 ---
text: The previously banned march was sanctioned by the police at the last minute and is one of several protests this weekend in Hong Kong .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1386 ---
text: Contentious issue The Greater Hyderabad Cab and Bus Operators Association went on strike demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003 .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003",
    "effect": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "demanding exemption from payment of Value Added Tax ( VAT ) with retrospective effect from 2003"
    },
    "relation": "caused",
    "effect": {
      "span": "The Greater Hyderabad Cab and Bus Operators Association went on strike"
    }
  }
]

--- id=2991 ---
text: Today 's incident , comes barely days after the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley , and has cast a shadow over the February 16 Lok Sabhapolls in the state .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 0, 'fp': 1, 'fn': 2}
gold_relations:
[
  {
    "cause": "the massacre of 23 Kashmiri Pandits by militants at Wandhama in the Ganderbal area of the Kashmir Valley",
    "effect": "Today 's incident"
  },
  {
    "cause": "Today 's incident",
    "effect": "has cast a shadow over the February 16 Lok Sabhapolls in the state"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "Today 's incident"
    },
    "relation": "caused",
    "effect": {
      "span": "cast a shadow over the February 16 Lok Sabhapolls in the state"
    }
  }
]

--- id=2634 ---
text: ALAPPUZHA : House of YC president attacked December 15 , 2016 00:00 IST The house of Kayamkulam Bharanikkavu Youth Congress ( YC ) mandalam president Salman was attacked by unknown persons on Wednesday .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=802 ---
text: The march started from the Martyrs ' Column at Palayam and concluded before the Secretariat .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=88 ---
text: Some schools which had to postpone their mid-term examinations due to the bandh have the additional task of conducting the tests before resuming the classes .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 1}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 1}
gold_relations:
[
  {
    "cause": "the bandh",
    "effect": "Some schools which had to postpone their mid-term examinations"
  },
  {
    "cause": "Some schools which had to postpone their mid-term examinations",
    "effect": "have the additional task of conducting the tests before resuming the classes"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the bandh"
    },
    "relation": "caused",
    "effect": {
      "span": "Some schools which had to postpone their mid-term examinations"
    }
  }
]

--- id=1835 ---
text: Two men have been arrested for the murder of two ANC branch leaders on the KwaZulu-Natal south coast , police said on Tuesday .
gold_has_causal=True | pred_has_causal=True
token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 1, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 1, 'fp': 0, 'fn': 0}
gold_relations:
[
  {
    "cause": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast",
    "effect": "Two men have been arrested"
  }
]
pred_triples:
[
  {
    "cause": {
      "span": "the murder of two ANC branch leaders on the KwaZulu-Natal south coast"
    },
    "relation": "caused",
    "effect": {
      "span": "Two men have been arrested"
    }
  }
]

--- id=1032 ---
text: He cited instances in 2005 when the Bajrang Dal activists allegedly assaulted employees who were going out on tour followed by attacks on churches in September 2008 and the 2009 Amnesia pub attack ..
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=1548 ---
text: The division bench of Bombay High Court comprising justices Ranjana Desai and R V More while dismissing the plea of state government earlier this year had said " we are of the view that the view taken by learned Sessions Judge so far as involvement of the duo in this case is concerned , cannot be called unreasonable , palpably false , manifestly erroneous and demonstratively unsustainable which merits our interference . "
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]

--- id=2714 ---
text: Demonstrators dismantled roadside barriers and built makeshift barricades between them and the police .
gold_has_causal=False | pred_has_causal=False
token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
primary_metric: strict_token_f1
strict_token_f1 counts: {'tp': 0, 'fp': 0, 'fn': 0}
anchor_window counts: {'tp': 0, 'fp': 0, 'fn': 0}
gold_relations:
[]
pred_triples:
[]
2026-08-27 02:06:04,281 | INFO | Eval report saved: D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\local-qwen3.6-27b-no-thinking_cnc_sft_validation-n500_prompt-v9.6_rag-knn_pattern-k3_20260827-020604.md
2026-08-27 02:06:04,287 | INFO | Phase 2 增量汇总已保存：D:\Master thesis\results\eval_report\rag_ablation\phase2_qwen27\phase2_qwen27_rerun_summary.csv
2026-08-27 02:06:04,288 | INFO | [Phase 2 6/6] 开始 fixed_rag_k5

2026-08-27 02:06:05,512 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:08,804 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:08,805 | WARNING | 生成失败：sample_id=1386 attempt=1/2 error=未找到 JSON 对象
2026-08-27 02:06:11,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:11,360 | WARNING | 生成失败：sample_id=1386 attempt=2/2 error=未找到 JSON 对象
2026-08-27 02:06:11,360 | ERROR | 生成兜底：sample_id=1386 error=未找到 JSON 对象
2026-08-27 02:06:11,487 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:11,489 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:12,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:12,540 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:14,588 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:14,589 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:14,590 | WARNING | 生成失败：sample_id=2991 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:14,728 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:14,730 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:15,783 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:15,783 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:17,828 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:17,830 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:17,830 | WARNING | 生成失败：sample_id=2991 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:17,831 | ERROR | 生成兜底：sample_id=2991 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4196>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:17,968 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:17,969 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:19,022 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:19,023 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:21,070 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:21,071 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:21,072 | WARNING | 生成失败：sample_id=2634 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:21,211 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:21,212 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:22,260 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:22,261 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:24,308 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:24,310 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:24,310 | WARNING | 生成失败：sample_id=2634 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:24,311 | ERROR | 生成兜底：sample_id=2634 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4145>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:25,755 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:28,811 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:31,911 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:33,250 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:33,440 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:33,441 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}

2026-08-27 02:06:34,490 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:34,491 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:36,539 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:36,540 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:36,541 | WARNING | 生成失败：sample_id=1548 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:36,735 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:36,737 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:37,791 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:37,792 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:39,836 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:06:39,837 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:39,838 | WARNING | 生成失败：sample_id=1548 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:39,838 | ERROR | 生成兜底：sample_id=1548 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4295>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:06:41,109 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:44,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:45,695 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:48,882 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:50,174 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:51,531 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:54,161 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:57,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:58,547 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:06:59,768 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:00,965 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:02,366 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:05,319 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:05,450 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:05,451 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:06,506 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:06,507 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:08,566 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:08,567 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:08,567 | WARNING | 生成失败：sample_id=2342 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:08,705 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:08,705 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:09,759 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:09,760 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:18,785 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:18,786 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:18,787 | WARNING | 生成失败：sample_id=2342 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:18,787 | ERROR | 生成兜底：sample_id=2342 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4133>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:20,889 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:22,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:26,564 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 02:07:28,582 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:28,725 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:28,726 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:29,777 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:29,778 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:31,832 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:31,833 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:31,833 | WARNING | 生成失败：sample_id=1542 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:31,972 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:31,973 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:33,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:33,024 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:35,079 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:35,080 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:35,080 | WARNING | 生成失败：sample_id=1542 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:35,081 | ERROR | 生成兜底：sample_id=1542 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4214>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:35,234 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:35,236 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:36,284 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:36,286 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:38,340 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:38,341 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:38,341 | WARNING | 生成失败：sample_id=1527 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:38,494 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:38,495 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:39,543 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:39,545 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:48,625 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:48,626 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:48,626 | WARNING | 生成失败：sample_id=1527 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:48,627 | ERROR | 生成兜底：sample_id=1527 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4321>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:50,518 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:52,360 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:52,362 | WARNING | 生成失败：sample_id=1309 attempt=1/2 error=未找到 JSON 对象
2026-08-27 02:07:52,761 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:07:52,762 | WARNING | 生成失败：sample_id=1309 attempt=2/2 error=未找到 JSON 对象
2026-08-27 02:07:52,763 | ERROR | 生成兜底：sample_id=1309 error=未找到 JSON 对象
2026-08-27 02:07:52,890 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:52,892 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:53,941 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:53,942 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}

2026-08-27 02:07:55,994 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:55,995 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:55,996 | WARNING | 生成失败：sample_id=597 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:56,134 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:56,135 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:57,177 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:57,178 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:59,233 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:07:59,234 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:59,235 | WARNING | 生成失败：sample_id=597 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:07:59,236 | ERROR | 生成兜底：sample_id=597 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4147>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:02,810 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:02,812 | WARNING | 生成失败：sample_id=1440 attempt=1/2 error=未找到 JSON 对象
2026-08-27 02:08:04,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:04,729 | WARNING | 生成失败：sample_id=1440 attempt=2/2 error=未找到 JSON 对象
2026-08-27 02:08:04,729 | ERROR | 生成兜底：sample_id=1440 error=未找到 JSON 对象
2026-08-27 02:08:06,689 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:08,666 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:11,975 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:15,949 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:19,437 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:23,749 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:23,911 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:23,912 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:24,966 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:24,967 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:27,016 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:27,017 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:27,017 | WARNING | 生成失败：sample_id=1220 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:27,171 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:27,172 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:28,232 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:28,234 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:30,301 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:30,302 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:30,303 | WARNING | 生成失败：sample_id=1220 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:30,303 | ERROR | 生成兜底：sample_id=1220 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4108>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:08:32,412 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:34,305 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:37,852 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:39,752 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:41,682 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:45,920 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:49,628 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:53,362 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:56,981 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:08:59,111 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 02:08:59,239 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:08:59,240 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:00,306 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:00,307 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:02,358 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:02,359 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:02,359 | WARNING | 生成失败：sample_id=2459 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:02,500 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:02,501 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:03,567 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:03,568 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:05,632 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:05,633 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:05,634 | WARNING | 生成失败：sample_id=2459 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:05,635 | ERROR | 生成兜底：sample_id=2459 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4178>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:09,750 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:11,713 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:13,706 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:15,704 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:17,938 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:17,940 | WARNING | 生成失败：sample_id=2006 attempt=1/2 error=未找到 JSON 对象
2026-08-27 02:09:18,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:18,728 | WARNING | 生成失败：sample_id=2006 attempt=2/2 error=未找到 JSON 对象
2026-08-27 02:09:18,729 | ERROR | 生成兜底：sample_id=2006 error=未找到 JSON 对象
2026-08-27 02:09:22,946 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:24,881 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:28,386 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:30,182 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:30,183 | WARNING | 生成失败：sample_id=1174 attempt=1/2 error=未找到 JSON 对象
2026-08-27 02:09:30,523 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:30,524 | WARNING | 生成失败：sample_id=1174 attempt=2/2 error=未找到 JSON 对象
2026-08-27 02:09:30,525 | ERROR | 生成兜底：sample_id=1174 error=未找到 JSON 对象
2026-08-27 02:09:34,658 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:38,023 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:39,833 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:41,727 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:41,825 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:41,826 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:42,887 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:42,889 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:44,954 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:44,955 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:44,955 | WARNING | 生成失败：sample_id=1862 attempt=1/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:45,062 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:45,063 | WARNING | LLM 调用失败：attempt=1/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:46,128 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:46,129 | WARNING | LLM 调用失败：attempt=2/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:48,188 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 400 Bad Request"
2026-08-27 02:09:48,189 | WARNING | LLM 调用失败：attempt=3/3 error=Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}

2026-08-27 02:09:48,189 | WARNING | 生成失败：sample_id=1862 attempt=2/2 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:48,190 | ERROR | 生成兜底：sample_id=1862 error=LLM 调用失败，已重试 3 次：Error code: 400 - {'error': 'The number of tokens to keep from the initial prompt is greater than the context length (n_keep: 4105>= n_ctx: 4096). Try to load the model with a larger context length, or provide a shorter input.'}
2026-08-27 02:09:52,298 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:54,268 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:56,283 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:09:59,667 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:10:01,577 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:10:05,375 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-27 02:10:07,152 | INFO | HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions "HTTP/1.1 200 OK"

KeyboardInterrupt:

## `fixed_rag_k5` 单独补跑

前一次运行期间，LM Studio 对部分约 4.1k–4.3k prompt tokens 的请求返回 `n_ctx=4096`，造成密集 HTTP 400 和 False 兜底，随后人工终止。该次未形成完整报告，也没有写入补跑汇总。本节只重跑 `fixed_rag_k5`，强制使用已通过长 prompt smoke 的 `context_length=8192, parallel=4`，并在加载响应和 LM Studio inventory 两处核对实例配置。

In [ ]:
# ===== fixed_rag_k5 专用补跑配置 =====
FIXED_RAG_K5_CONTEXT_LENGTH = 8192
FIXED_RAG_K5_PARALLEL = 4
FIXED_RAG_K5_SUMMARY_PATH = (
    PROJECT_ROOT / REPORT_DIR / 'phase2_qwen27_fixed_rag_k5_rerun_summary.csv'
)
RUN_FIXED_RAG_K5_RERUN = False  # 确认配置后手动改为 True。

FIXED_RAG_K5_RUN = runs_by_id['fixed_rag_k5'].copy()
display(pd.DataFrame([{
    **FIXED_RAG_K5_RUN,
    'context_length': FIXED_RAG_K5_CONTEXT_LENGTH,
    'parallel': FIXED_RAG_K5_PARALLEL,
}]))
LOGGER.info('单组补跑汇总将保存到：%s', FIXED_RAG_K5_SUMMARY_PATH)

In [ ]:
# ===== 只执行 fixed_rag_k5，并更新六组补跑与完整十组汇总 =====
if not RUN_FIXED_RAG_K5_RERUN:
    LOGGER.warning(
        'fixed_rag_k5 补跑未启动。将 RUN_FIXED_RAG_K5_RERUN 改为 True。'
    )
else:
    FIXED_RAG_K5_RESULTS = run_phase2(
        [FIXED_RAG_K5_RUN],
        summary_path=FIXED_RAG_K5_SUMMARY_PATH,
        context_length=FIXED_RAG_K5_CONTEXT_LENGTH,
        parallel=FIXED_RAG_K5_PARALLEL,
    )
    fixed_rag_k5_df = pd.DataFrame(FIXED_RAG_K5_RESULTS)
    if (
        len(fixed_rag_k5_df) != 1
        or fixed_rag_k5_df.iloc[0]['run_id'] != 'fixed_rag_k5'
        or fixed_rag_k5_df.iloc[0]['status'] != 'completed'
    ):
        raise RuntimeError('fixed_rag_k5 未完整成功，不更新正式汇总。')
    display(fixed_rag_k5_df)

    previous_rerun_df = pd.read_csv(RERUN_SUMMARY_PATH)
    previous_rerun_df = previous_rerun_df[
        previous_rerun_df['run_id'] != 'fixed_rag_k5'
    ]
    phase2_rerun_summary_df = pd.concat(
        [previous_rerun_df, fixed_rag_k5_df],
        ignore_index=True,
    )
    if set(phase2_rerun_summary_df['run_id']) != set(RERUN_RUN_IDS):
        raise RuntimeError('合并后的补跑汇总不是预期的六组配置。')
    phase2_rerun_summary_df['_run_order'] = pd.Categorical(
        phase2_rerun_summary_df['run_id'],
        categories=list(RERUN_RUN_IDS),
        ordered=True,
    )
    phase2_rerun_summary_df = (
        phase2_rerun_summary_df.sort_values('_run_order')
        .drop(columns='_run_order')
        .reset_index(drop=True)
    )
    phase2_rerun_summary_df.to_csv(
        RERUN_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )

    original_summary_df = pd.read_csv(SUMMARY_PATH)
    valid_original_df = original_summary_df[
        original_summary_df['run_id'].isin(VALID_ORIGINAL_RUN_IDS)
    ].copy()
    if set(valid_original_df['run_id']) != set(VALID_ORIGINAL_RUN_IDS):
        raise RuntimeError('原始汇总中缺少 fixed 或 RAG-only 有效结果。')
    corrected_summary_df = pd.concat(
        [valid_original_df, phase2_rerun_summary_df],
        ignore_index=True,
    )
    run_order = [run['run_id'] for run in EXPERIMENT_RUNS]
    corrected_summary_df['_run_order'] = pd.Categorical(
        corrected_summary_df['run_id'],
        categories=run_order,
        ordered=True,
    )
    corrected_summary_df = (
        corrected_summary_df.sort_values('_run_order')
        .drop(columns='_run_order')
        .reset_index(drop=True)
    )
    corrected_summary_df.to_csv(
        CORRECTED_SUMMARY_PATH,
        index=False,
        encoding='utf-8-sig',
    )
    LOGGER.info('六组补跑汇总已更新：%s', RERUN_SUMMARY_PATH)
    LOGGER.info('修正版完整十组汇总已更新：%s', CORRECTED_SUMMARY_PATH)
    display(corrected_summary_df)